//! Rust client for [novamem](https://github.com/azrtydxb/novamem), a tiered
//! memory service for agents.
//!
//! ```no_run
//! # async fn demo() -> Result<(), novamem::Error> {
//! use novamem::{types::{CaptureRequest, SearchRequest}, Client, Config};
//!
//! let c = Client::new(Config {
//!     base_url: "https://novamem.example.com".into(),
//!     token: std::env::var("NOVAMEM_TOKEN").unwrap_or_default(),
//!     ..Config::default()
//! })?;
//! c.capture(CaptureRequest { content: "User prefers dark roast".into(), ..Default::default() }).await?;
//! match c.search(SearchRequest { query: "coffee preference".into(), k: Some(5), ..Default::default() }).await {
//!     Err(e) if e.is_unavailable() => { /* "I could not look." Say so; do not claim ignorance. */ }
//!     Err(e) => return Err(e),
//!     Ok(r) if r.results.is_empty() => { /* "Nothing is stored about that." This one is knowledge. */ }
//!     Ok(_) => {}
//! }
//! # Ok(()) }
//! ```
//!
//! This crate never retries on your behalf, and every call is bounded by
//! [`Config::timeout`] even when the caller sets no deadline.

mod client;
mod error;
mod time;
mod transport;
#[rustfmt::skip] // generated by clients/gen: formatting it would fight the generator
pub mod types;

pub use client::{Admin, Client, Management};
pub use error::Error;
pub use transport::{Config, DEFAULT_TIMEOUT, MAX_RESPONSE_BYTES};
