// Code generated by clients/gen. DO NOT EDIT.
//
// Wire types for the novamem API, generated from docs/api/openapi.json.
// Unset optional fields (and empty optional strings) are left out of
// requests; required ones are always sent, as null when they are None.
// Unknown response fields are ignored, and an enum value this SDK does not
// know decodes as `Unknown` rather than failing the call.

#![allow(clippy::all)]
// Formatting a generated file would fight the generator; rustfmt alone
// sets the `rustfmt` cfg, so the compiler never sees this attribute.
#![cfg_attr(rustfmt, rustfmt_skip)]

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub(crate) fn none_or_empty(v: &Option<String>) -> bool {
    v.as_deref().map_or(true, str::is_empty)
}


#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ActiveProject {
    #[serde(rename = "active", default)]
    pub active: Option<ActiveProjectActive>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ActiveProjectActive {
    #[serde(rename = "id", default, skip_serializing_if = "none_or_empty")]
    pub id: Option<String>,
    #[serde(rename = "name", default, skip_serializing_if = "none_or_empty")]
    pub name: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AdminUser {
    #[serde(rename = "createdAt", default)]
    pub created_at: String,
    #[serde(rename = "email", default)]
    pub email: String,
    #[serde(rename = "entryCount", default)]
    pub entry_count: i32,
    #[serde(rename = "id", default)]
    pub id: String,
    #[serde(rename = "name", default)]
    pub name: Option<String>,
    #[serde(rename = "role", default)]
    pub role: String,
    #[serde(rename = "tokenCount", default)]
    pub token_count: i32,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AdminUserList {
    #[serde(rename = "users", default)]
    pub users: Vec<AdminUser>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AdoptionReport {
    #[serde(rename = "diagnostics", default)]
    pub diagnostics: Vec<serde_json::Map<String, serde_json::Value>>,
    #[serde(rename = "features", default, skip_serializing_if = "Option::is_none")]
    pub features: Option<serde_json::Map<String, serde_json::Value>>,
    #[serde(rename = "mcp", default)]
    pub mcp: serde_json::Map<String, serde_json::Value>,
    #[serde(rename = "refresh", default, skip_serializing_if = "Option::is_none")]
    pub refresh: Option<serde_json::Map<String, serde_json::Value>>,
    #[serde(rename = "requestedClient", default)]
    pub requested_client: String,
    #[serde(rename = "requiredTools", default, skip_serializing_if = "Option::is_none")]
    pub required_tools: Option<Vec<String>>,
    #[serde(rename = "server", default)]
    pub server: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CaptureRequest {
    #[serde(rename = "agentName", default, skip_serializing_if = "none_or_empty")]
    pub agent_name: Option<String>,
    #[serde(rename = "capturedFrom", default, skip_serializing_if = "none_or_empty")]
    pub captured_from: Option<String>,
    #[serde(rename = "confidence", default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    #[serde(rename = "content", default)]
    pub content: String,
    #[serde(rename = "expiresAt", default, skip_serializing_if = "none_or_empty")]
    pub expires_at: Option<String>,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Map<String, serde_json::Value>>,
    #[serde(rename = "namespace", default, skip_serializing_if = "none_or_empty")]
    pub namespace: Option<String>,
    #[serde(rename = "project", default, skip_serializing_if = "none_or_empty")]
    pub project: Option<String>,
    #[serde(rename = "sensitivity", default, skip_serializing_if = "Option::is_none")]
    pub sensitivity: Option<CaptureRequestSensitivity>,
    #[serde(rename = "source", default, skip_serializing_if = "none_or_empty")]
    pub source: Option<String>,
    #[serde(rename = "sourceType", default, skip_serializing_if = "none_or_empty")]
    pub source_type: Option<String>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CaptureRequestSensitivity {
    #[default]
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "sensitive")]
    Sensitive,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CaptureResult {
    #[serde(rename = "deduplicated", default, skip_serializing_if = "Option::is_none")]
    pub deduplicated: Option<bool>,
    #[serde(rename = "embedded", default, skip_serializing_if = "Option::is_none")]
    pub embedded: Option<bool>,
    #[serde(rename = "id", default)]
    pub id: Option<String>,
    #[serde(rename = "rejected", default, skip_serializing_if = "none_or_empty")]
    pub rejected: Option<String>,
    #[serde(rename = "superseded", default, skip_serializing_if = "Option::is_none")]
    pub superseded: Option<Vec<String>>,
    #[serde(rename = "updated", default, skip_serializing_if = "Option::is_none")]
    pub updated: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ChangeFeed {
    #[serde(rename = "changes", default)]
    pub changes: Vec<ChangeFeedChangesItem>,
    #[serde(rename = "nextSeq", default, skip_serializing_if = "Option::is_none")]
    pub next_seq: Option<i64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ChangeFeedChangesItem {
    #[serde(rename = "at", default, skip_serializing_if = "none_or_empty")]
    pub at: Option<String>,
    #[serde(rename = "change", default, skip_serializing_if = "Option::is_none")]
    pub change: Option<ChangeFeedChangesItemChange>,
    #[serde(rename = "detail", default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Map<String, serde_json::Value>>,
    #[serde(rename = "entryId", default, skip_serializing_if = "none_or_empty")]
    pub entry_id: Option<String>,
    #[serde(rename = "projectId", default, skip_serializing_if = "none_or_empty")]
    pub project_id: Option<String>,
    #[serde(rename = "seq", default, skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ChangeFeedChangesItemChange {
    #[default]
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "updated")]
    Updated,
    #[serde(rename = "superseded")]
    Superseded,
    #[serde(rename = "deleted")]
    Deleted,
    #[serde(rename = "expired")]
    Expired,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ContextPrefix {
    #[serde(rename = "prefix", default)]
    pub prefix: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ContextRequest {
    #[serde(rename = "asOf", default, skip_serializing_if = "none_or_empty")]
    pub as_of: Option<String>,
    #[serde(rename = "decompose", default, skip_serializing_if = "Option::is_none")]
    pub decompose: Option<bool>,
    #[serde(rename = "expandSourceChunks", default, skip_serializing_if = "Option::is_none")]
    pub expand_source_chunks: Option<bool>,
    #[serde(rename = "includeNamespaces", default, skip_serializing_if = "Option::is_none")]
    pub include_namespaces: Option<Vec<String>>,
    #[serde(rename = "includeProjects", default, skip_serializing_if = "Option::is_none")]
    pub include_projects: Option<Vec<String>>,
    #[serde(rename = "k", default, skip_serializing_if = "Option::is_none")]
    pub k: Option<i32>,
    #[serde(rename = "maxSensitivity", default, skip_serializing_if = "Option::is_none")]
    pub max_sensitivity: Option<ContextRequestMaxSensitivity>,
    #[serde(rename = "maxTokens", default, skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<i32>,
    #[serde(rename = "message", default)]
    pub message: String,
    #[serde(rename = "namespace", default, skip_serializing_if = "none_or_empty")]
    pub namespace: Option<String>,
    #[serde(rename = "project", default, skip_serializing_if = "none_or_empty")]
    pub project: Option<String>,
    #[serde(rename = "weights", default, skip_serializing_if = "Option::is_none")]
    pub weights: Option<ContextRequestWeights>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ContextRequestMaxSensitivity {
    #[default]
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "sensitive")]
    Sensitive,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ContextRequestWeights {
    #[serde(rename = "entity", default, skip_serializing_if = "Option::is_none")]
    pub entity: Option<f64>,
    #[serde(rename = "graph", default, skip_serializing_if = "Option::is_none")]
    pub graph: Option<f64>,
    #[serde(rename = "keyword", default, skip_serializing_if = "Option::is_none")]
    pub keyword: Option<f64>,
    #[serde(rename = "recency", default, skip_serializing_if = "Option::is_none")]
    pub recency: Option<f64>,
    #[serde(rename = "vector", default, skip_serializing_if = "Option::is_none")]
    pub vector: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DecayResult {
    #[serde(rename = "demoted", default)]
    pub demoted: f64,
    #[serde(rename = "expired", default)]
    pub expired: f64,
    #[serde(rename = "promoted", default)]
    pub promoted: f64,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EntryList {
    #[serde(rename = "results", default)]
    pub results: Vec<MemoryEntry>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EvaluateReport {
    #[serde(rename = "cases", default)]
    pub cases: Vec<EvaluateReportCasesItem>,
    #[serde(rename = "passed", default)]
    pub passed: bool,
    #[serde(rename = "suite", default)]
    pub suite: String,
    #[serde(rename = "summary", default)]
    pub summary: EvaluateReportSummary,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EvaluateReportCasesItem {
    #[serde(rename = "name", default, skip_serializing_if = "none_or_empty")]
    pub name: Option<String>,
    #[serde(rename = "passed", default, skip_serializing_if = "Option::is_none")]
    pub passed: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EvaluateReportSummary {
    #[serde(rename = "failed", default, skip_serializing_if = "Option::is_none")]
    pub failed: Option<f64>,
    #[serde(rename = "passed", default, skip_serializing_if = "Option::is_none")]
    pub passed: Option<f64>,
    #[serde(rename = "total", default, skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExportPage {
    #[serde(rename = "entries", default)]
    pub entries: Vec<ExportedEntry>,
    #[serde(rename = "nextAfterId", default)]
    pub next_after_id: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ExportedEntry {
    #[serde(rename = "agentName", default)]
    pub agent_name: Option<String>,
    #[serde(rename = "capturedFrom", default)]
    pub captured_from: Option<String>,
    #[serde(rename = "confidence", default)]
    pub confidence: f64,
    #[serde(rename = "content", default)]
    pub content: String,
    #[serde(rename = "createdAt", default)]
    pub created_at: String,
    #[serde(rename = "id", default)]
    pub id: String,
    #[serde(rename = "metadata", default)]
    pub metadata: serde_json::Map<String, serde_json::Value>,
    #[serde(rename = "namespace", default)]
    pub namespace: String,
    #[serde(rename = "projectId", default)]
    pub project_id: Option<String>,
    #[serde(rename = "source", default)]
    pub source: String,
    #[serde(rename = "sourceType", default)]
    pub source_type: Option<String>,
    #[serde(rename = "updatedAt", default)]
    pub updated_at: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ForgetRequest {
    #[serde(rename = "id", default)]
    pub id: String,
    #[serde(rename = "project", default, skip_serializing_if = "none_or_empty")]
    pub project: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ForgetResult {
    #[serde(rename = "coldDeleteOk", default, skip_serializing_if = "Option::is_none")]
    pub cold_delete_ok: Option<bool>,
    #[serde(rename = "deleted", default)]
    pub deleted: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Health {
    #[serde(rename = "ok", default)]
    pub ok: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct HygieneReport {
    #[serde(rename = "contradictionCandidates", default, skip_serializing_if = "Option::is_none")]
    pub contradiction_candidates: Option<Vec<serde_json::Value>>,
    #[serde(rename = "duplicateClusters", default, skip_serializing_if = "Option::is_none")]
    pub duplicate_clusters: Option<Vec<serde_json::Value>>,
    #[serde(rename = "lowValue", default, skip_serializing_if = "Option::is_none")]
    pub low_value: Option<Vec<serde_json::Value>>,
    #[serde(rename = "orphanCandidates", default, skip_serializing_if = "Option::is_none")]
    pub orphan_candidates: Option<Vec<serde_json::Value>>,
    #[serde(rename = "stale", default, skip_serializing_if = "Option::is_none")]
    pub stale: Option<Vec<serde_json::Value>>,
    #[serde(rename = "summary", default)]
    pub summary: HygieneReportSummary,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct HygieneReportSummary {
    #[serde(rename = "contradictionCandidates", default, skip_serializing_if = "Option::is_none")]
    pub contradiction_candidates: Option<f64>,
    #[serde(rename = "duplicateClusters", default, skip_serializing_if = "Option::is_none")]
    pub duplicate_clusters: Option<f64>,
    #[serde(rename = "lowValue", default, skip_serializing_if = "Option::is_none")]
    pub low_value: Option<f64>,
    #[serde(rename = "orphanCandidates", default, skip_serializing_if = "Option::is_none")]
    pub orphan_candidates: Option<f64>,
    #[serde(rename = "scanned", default, skip_serializing_if = "Option::is_none")]
    pub scanned: Option<f64>,
    #[serde(rename = "stale", default, skip_serializing_if = "Option::is_none")]
    pub stale: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ImportResult {
    #[serde(rename = "deduplicated", default)]
    pub deduplicated: i32,
    #[serde(rename = "failed", default)]
    pub failed: Vec<ImportResultFailedItem>,
    #[serde(rename = "imported", default)]
    pub imported: i32,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ImportResultFailedItem {
    #[serde(rename = "error", default)]
    pub error: String,
    #[serde(rename = "index", default)]
    pub index: i32,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MemberAdded {
    #[serde(rename = "added", default)]
    pub added: bool,
    #[serde(rename = "userId", default)]
    pub user_id: String,
    #[serde(rename = "username", default)]
    pub username: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MemberList {
    #[serde(rename = "members", default)]
    pub members: Vec<MemberListMembersItem>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MemberListMembersItem {
    #[serde(rename = "joinedAt", default, skip_serializing_if = "none_or_empty")]
    pub joined_at: Option<String>,
    #[serde(rename = "role", default, skip_serializing_if = "none_or_empty")]
    pub role: Option<String>,
    #[serde(rename = "userId", default, skip_serializing_if = "none_or_empty")]
    pub user_id: Option<String>,
    #[serde(rename = "username", default, skip_serializing_if = "none_or_empty")]
    pub username: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MemberRemoved {
    #[serde(rename = "removed", default)]
    pub removed: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MemoryEntry {
    #[serde(rename = "content", default)]
    pub content: String,
    #[serde(rename = "id", default)]
    pub id: String,
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Map<String, serde_json::Value>>,
    #[serde(rename = "namespace", default, skip_serializing_if = "none_or_empty")]
    pub namespace: Option<String>,
    #[serde(rename = "project", default, skip_serializing_if = "none_or_empty")]
    pub project: Option<String>,
    #[serde(rename = "score", default, skip_serializing_if = "Option::is_none")]
    pub score: Option<f64>,
    #[serde(rename = "signals", default, skip_serializing_if = "Option::is_none")]
    pub signals: Option<MemoryEntrySignals>,
    #[serde(rename = "source", default, skip_serializing_if = "none_or_empty")]
    pub source: Option<String>,
    #[serde(rename = "tier", default, skip_serializing_if = "Option::is_none")]
    pub tier: Option<MemoryEntryTier>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MemoryEntrySignals {
    #[serde(rename = "entity", default, skip_serializing_if = "Option::is_none")]
    pub entity: Option<f64>,
    #[serde(rename = "graph", default, skip_serializing_if = "Option::is_none")]
    pub graph: Option<f64>,
    #[serde(rename = "keyword", default, skip_serializing_if = "Option::is_none")]
    pub keyword: Option<f64>,
    #[serde(rename = "recency", default, skip_serializing_if = "Option::is_none")]
    pub recency: Option<f64>,
    #[serde(rename = "vector", default, skip_serializing_if = "Option::is_none")]
    pub vector: Option<f64>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MemoryEntryTier {
    #[default]
    #[serde(rename = "warm")]
    Warm,
    #[serde(rename = "cold")]
    Cold,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MintTokenRequest {
    #[serde(rename = "expiresInDays", default, skip_serializing_if = "Option::is_none")]
    pub expires_in_days: Option<i32>,
    #[serde(rename = "label", default, skip_serializing_if = "none_or_empty")]
    pub label: Option<String>,
    #[serde(rename = "project", default, skip_serializing_if = "none_or_empty")]
    pub project: Option<String>,
    #[serde(rename = "scope", default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<MintTokenRequestScope>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MintTokenRequestScope {
    #[default]
    #[serde(rename = "full")]
    Full,
    #[serde(rename = "read_only")]
    ReadOnly,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MintedToken {
    #[serde(rename = "createdAt", default, skip_serializing_if = "none_or_empty")]
    pub created_at: Option<String>,
    #[serde(rename = "expiresAt", default, skip_serializing_if = "none_or_empty")]
    pub expires_at: Option<String>,
    #[serde(rename = "projectId", default, skip_serializing_if = "none_or_empty")]
    pub project_id: Option<String>,
    #[serde(rename = "scope", default, skip_serializing_if = "none_or_empty")]
    pub scope: Option<String>,
    #[serde(rename = "token", default)]
    pub token: String,
    #[serde(rename = "userId", default, skip_serializing_if = "none_or_empty")]
    pub user_id: Option<String>,
    #[serde(rename = "warning", default, skip_serializing_if = "none_or_empty")]
    pub warning: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct NeighborsRequest {
    #[serde(rename = "depth", default, skip_serializing_if = "Option::is_none")]
    pub depth: Option<i32>,
    #[serde(rename = "id", default)]
    pub id: String,
    #[serde(rename = "includeNamespaces", default, skip_serializing_if = "Option::is_none")]
    pub include_namespaces: Option<Vec<String>>,
    #[serde(rename = "includeProjects", default, skip_serializing_if = "Option::is_none")]
    pub include_projects: Option<Vec<String>>,
    #[serde(rename = "k", default, skip_serializing_if = "Option::is_none")]
    pub k: Option<i32>,
    #[serde(rename = "maxSensitivity", default, skip_serializing_if = "Option::is_none")]
    pub max_sensitivity: Option<NeighborsRequestMaxSensitivity>,
    #[serde(rename = "project", default, skip_serializing_if = "none_or_empty")]
    pub project: Option<String>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum NeighborsRequestMaxSensitivity {
    #[default]
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "sensitive")]
    Sensitive,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ObserveResult {
    #[serde(rename = "logChars", default, skip_serializing_if = "Option::is_none")]
    pub log_chars: Option<f64>,
    #[serde(rename = "observed", default, skip_serializing_if = "Option::is_none")]
    pub observed: Option<f64>,
    #[serde(rename = "reflected", default, skip_serializing_if = "Option::is_none")]
    pub reflected: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Project {
    #[serde(rename = "createdAt", default, skip_serializing_if = "none_or_empty")]
    pub created_at: Option<String>,
    #[serde(rename = "id", default)]
    pub id: String,
    #[serde(rename = "name", default)]
    pub name: String,
    #[serde(rename = "ownerUserId", default, skip_serializing_if = "none_or_empty")]
    pub owner_user_id: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ProjectDeleted {
    #[serde(rename = "coldCollectionsDropped", default, skip_serializing_if = "Option::is_none")]
    pub cold_collections_dropped: Option<Vec<String>>,
    #[serde(rename = "deleted", default)]
    pub deleted: bool,
    #[serde(rename = "entriesRemoved", default, skip_serializing_if = "Option::is_none")]
    pub entries_removed: Option<f64>,
    #[serde(rename = "graphCleared", default, skip_serializing_if = "Option::is_none")]
    pub graph_cleared: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ProjectList {
    #[serde(rename = "projects", default)]
    pub projects: Vec<ProjectListItem>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ProjectListItem {
    #[serde(rename = "createdAt", default, skip_serializing_if = "none_or_empty")]
    pub created_at: Option<String>,
    #[serde(rename = "id", default)]
    pub id: String,
    #[serde(rename = "name", default)]
    pub name: String,
    #[serde(rename = "ownerUserId", default, skip_serializing_if = "none_or_empty")]
    pub owner_user_id: Option<String>,
    #[serde(rename = "role", default)]
    pub role: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ProvisionUserRequest {
    #[serde(rename = "email", default)]
    pub email: String,
    #[serde(rename = "name", default, skip_serializing_if = "none_or_empty")]
    pub name: Option<String>,
    #[serde(rename = "password", default)]
    pub password: String,
    #[serde(rename = "tokenExpiresInDays", default, skip_serializing_if = "Option::is_none")]
    pub token_expires_in_days: Option<i32>,
    #[serde(rename = "tokenLabel", default, skip_serializing_if = "none_or_empty")]
    pub token_label: Option<String>,
    #[serde(rename = "tokenScope", default, skip_serializing_if = "Option::is_none")]
    pub token_scope: Option<ProvisionUserRequestTokenScope>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ProvisionUserRequestTokenScope {
    #[default]
    #[serde(rename = "full")]
    Full,
    #[serde(rename = "read_only")]
    ReadOnly,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ProvisionedUser {
    #[serde(rename = "email", default)]
    pub email: String,
    #[serde(rename = "token", default, skip_serializing_if = "none_or_empty")]
    pub token: Option<String>,
    #[serde(rename = "userId", default)]
    pub user_id: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct QuotaResult {
    #[serde(rename = "quota", default)]
    pub quota: QuotaResultQuota,
    #[serde(rename = "userId", default)]
    pub user_id: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct QuotaResultQuota {
    #[serde(rename = "maxEntries", default)]
    pub max_entries: Option<i32>,
    #[serde(rename = "writesPerMinute", default)]
    pub writes_per_minute: Option<i32>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RecentRequest {
    #[serde(rename = "contentMode", default, skip_serializing_if = "Option::is_none")]
    pub content_mode: Option<RecentRequestContentMode>,
    #[serde(rename = "includeNamespaces", default, skip_serializing_if = "Option::is_none")]
    pub include_namespaces: Option<Vec<String>>,
    #[serde(rename = "includeProjects", default, skip_serializing_if = "Option::is_none")]
    pub include_projects: Option<Vec<String>>,
    #[serde(rename = "k", default, skip_serializing_if = "Option::is_none")]
    pub k: Option<i32>,
    #[serde(rename = "maxSensitivity", default, skip_serializing_if = "Option::is_none")]
    pub max_sensitivity: Option<RecentRequestMaxSensitivity>,
    #[serde(rename = "namespace", default, skip_serializing_if = "none_or_empty")]
    pub namespace: Option<String>,
    #[serde(rename = "project", default, skip_serializing_if = "none_or_empty")]
    pub project: Option<String>,
    #[serde(rename = "since", default, skip_serializing_if = "none_or_empty")]
    pub since: Option<String>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RecentRequestContentMode {
    #[default]
    #[serde(rename = "full")]
    Full,
    #[serde(rename = "snippet")]
    Snippet,
    #[serde(rename = "ids")]
    Ids,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RecentRequestMaxSensitivity {
    #[default]
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "sensitive")]
    Sensitive,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RememberResult {
    #[serde(rename = "deduplicated", default, skip_serializing_if = "Option::is_none")]
    pub deduplicated: Option<bool>,
    #[serde(rename = "embedded", default, skip_serializing_if = "Option::is_none")]
    pub embedded: Option<bool>,
    #[serde(rename = "id", default)]
    pub id: Option<String>,
    #[serde(rename = "rejected", default, skip_serializing_if = "none_or_empty")]
    pub rejected: Option<String>,
    #[serde(rename = "superseded", default, skip_serializing_if = "Option::is_none")]
    pub superseded: Option<Vec<String>>,
    #[serde(rename = "updated", default, skip_serializing_if = "Option::is_none")]
    pub updated: Option<bool>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RevokeResult {
    #[serde(rename = "revoked", default)]
    pub revoked: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SearchRequest {
    #[serde(rename = "agentName", default, skip_serializing_if = "none_or_empty")]
    pub agent_name: Option<String>,
    #[serde(rename = "asOf", default, skip_serializing_if = "none_or_empty")]
    pub as_of: Option<String>,
    #[serde(rename = "contentMode", default, skip_serializing_if = "Option::is_none")]
    pub content_mode: Option<SearchRequestContentMode>,
    #[serde(rename = "decompose", default, skip_serializing_if = "Option::is_none")]
    pub decompose: Option<bool>,
    #[serde(rename = "expandSourceChunks", default, skip_serializing_if = "Option::is_none")]
    pub expand_source_chunks: Option<bool>,
    #[serde(rename = "includeNamespaces", default, skip_serializing_if = "Option::is_none")]
    pub include_namespaces: Option<Vec<String>>,
    #[serde(rename = "includeProjects", default, skip_serializing_if = "Option::is_none")]
    pub include_projects: Option<Vec<String>>,
    #[serde(rename = "k", default, skip_serializing_if = "Option::is_none")]
    pub k: Option<i32>,
    #[serde(rename = "maxSensitivity", default, skip_serializing_if = "Option::is_none")]
    pub max_sensitivity: Option<SearchRequestMaxSensitivity>,
    #[serde(rename = "maxTokens", default, skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<i32>,
    #[serde(rename = "minVectorScore", default, skip_serializing_if = "Option::is_none")]
    pub min_vector_score: Option<f64>,
    #[serde(rename = "namespace", default, skip_serializing_if = "none_or_empty")]
    pub namespace: Option<String>,
    #[serde(rename = "project", default, skip_serializing_if = "none_or_empty")]
    pub project: Option<String>,
    #[serde(rename = "query", default)]
    pub query: String,
    #[serde(rename = "rerank", default, skip_serializing_if = "Option::is_none")]
    pub rerank: Option<bool>,
    #[serde(rename = "weights", default, skip_serializing_if = "Option::is_none")]
    pub weights: Option<SearchRequestWeights>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SearchRequestContentMode {
    #[default]
    #[serde(rename = "full")]
    Full,
    #[serde(rename = "snippet")]
    Snippet,
    #[serde(rename = "ids")]
    Ids,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SearchRequestMaxSensitivity {
    #[default]
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "sensitive")]
    Sensitive,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SearchRequestWeights {
    #[serde(rename = "entity", default, skip_serializing_if = "Option::is_none")]
    pub entity: Option<f64>,
    #[serde(rename = "graph", default, skip_serializing_if = "Option::is_none")]
    pub graph: Option<f64>,
    #[serde(rename = "keyword", default, skip_serializing_if = "Option::is_none")]
    pub keyword: Option<f64>,
    #[serde(rename = "recency", default, skip_serializing_if = "Option::is_none")]
    pub recency: Option<f64>,
    #[serde(rename = "vector", default, skip_serializing_if = "Option::is_none")]
    pub vector: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SearchResult {
    #[serde(rename = "degraded", default, skip_serializing_if = "Option::is_none")]
    pub degraded: Option<bool>,
    #[serde(rename = "results", default)]
    pub results: Vec<MemoryEntry>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SessionRecapRequest {
    #[serde(rename = "agentName", default, skip_serializing_if = "none_or_empty")]
    pub agent_name: Option<String>,
    #[serde(rename = "capturedFrom", default, skip_serializing_if = "none_or_empty")]
    pub captured_from: Option<String>,
    #[serde(rename = "confidence", default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    #[serde(rename = "decisions", default, skip_serializing_if = "Option::is_none")]
    pub decisions: Option<Vec<String>>,
    #[serde(rename = "force", default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Map<String, serde_json::Value>>,
    #[serde(rename = "namespace", default, skip_serializing_if = "none_or_empty")]
    pub namespace: Option<String>,
    #[serde(rename = "other", default, skip_serializing_if = "Option::is_none")]
    pub other: Option<Vec<String>>,
    #[serde(rename = "preferences", default, skip_serializing_if = "Option::is_none")]
    pub preferences: Option<Vec<String>>,
    #[serde(rename = "project", default, skip_serializing_if = "none_or_empty")]
    pub project: Option<String>,
    #[serde(rename = "projectConventions", default, skip_serializing_if = "Option::is_none")]
    pub project_conventions: Option<Vec<String>>,
    #[serde(rename = "rootCauses", default, skip_serializing_if = "Option::is_none")]
    pub root_causes: Option<Vec<String>>,
    #[serde(rename = "safetyConstraints", default, skip_serializing_if = "Option::is_none")]
    pub safety_constraints: Option<Vec<String>>,
    #[serde(rename = "sensitivity", default, skip_serializing_if = "Option::is_none")]
    pub sensitivity: Option<SessionRecapRequestSensitivity>,
    #[serde(rename = "setupFacts", default, skip_serializing_if = "Option::is_none")]
    pub setup_facts: Option<Vec<String>>,
    #[serde(rename = "source", default, skip_serializing_if = "none_or_empty")]
    pub source: Option<String>,
    #[serde(rename = "sourceType", default, skip_serializing_if = "none_or_empty")]
    pub source_type: Option<String>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SessionRecapRequestSensitivity {
    #[default]
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "sensitive")]
    Sensitive,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SessionRecapResult {
    #[serde(rename = "results", default)]
    pub results: Vec<CaptureResult>,
    #[serde(rename = "saved", default)]
    pub saved: f64,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Stats {
    #[serde(rename = "byNamespace", default)]
    pub by_namespace: BTreeMap<String, StatsByNamespaceValue>,
    #[serde(rename = "lastDecayAt", default, skip_serializing_if = "none_or_empty")]
    pub last_decay_at: Option<String>,
    #[serde(rename = "totalCold", default)]
    pub total_cold: f64,
    #[serde(rename = "totalWarm", default)]
    pub total_warm: f64,
    #[serde(rename = "uptimeMs", default, skip_serializing_if = "Option::is_none")]
    pub uptime_ms: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct StatsByNamespaceValue {
    #[serde(rename = "cold", default, skip_serializing_if = "Option::is_none")]
    pub cold: Option<f64>,
    #[serde(rename = "warm", default, skip_serializing_if = "Option::is_none")]
    pub warm: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TokenDeleted {
    #[serde(rename = "deleted", default)]
    pub deleted: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TokenList {
    #[serde(rename = "tokens", default)]
    pub tokens: Vec<serde_json::Map<String, serde_json::Value>>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UpdateRequest {
    #[serde(rename = "capturedFrom", default, skip_serializing_if = "none_or_empty")]
    pub captured_from: Option<String>,
    #[serde(rename = "confidence", default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    #[serde(rename = "content", default, skip_serializing_if = "none_or_empty")]
    pub content: Option<String>,
    #[serde(rename = "metadata", default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Map<String, serde_json::Value>>,
    #[serde(rename = "namespace", default, skip_serializing_if = "none_or_empty")]
    pub namespace: Option<String>,
    #[serde(rename = "project", default, skip_serializing_if = "none_or_empty")]
    pub project: Option<String>,
    #[serde(rename = "sensitivity", default, skip_serializing_if = "Option::is_none")]
    pub sensitivity: Option<UpdateRequestSensitivity>,
    #[serde(rename = "sourceType", default, skip_serializing_if = "none_or_empty")]
    pub source_type: Option<String>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum UpdateRequestSensitivity {
    #[default]
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "sensitive")]
    Sensitive,
    /// A value this version of the SDK does not know.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UpdateResult {
    #[serde(rename = "embeddingChanged", default)]
    pub embedding_changed: bool,
    #[serde(rename = "id", default)]
    pub id: String,
    #[serde(rename = "updated", default)]
    pub updated: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Usage {
    #[serde(rename = "entries", default, skip_serializing_if = "Option::is_none")]
    pub entries: Option<f64>,
    #[serde(rename = "quota", default, skip_serializing_if = "Option::is_none")]
    pub quota: Option<UsageQuota>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UsageQuota {
    #[serde(rename = "maxEntries", default, skip_serializing_if = "Option::is_none")]
    pub max_entries: Option<f64>,
    #[serde(rename = "writesPerMinute", default, skip_serializing_if = "Option::is_none")]
    pub writes_per_minute: Option<f64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UserDeletion {
    #[serde(rename = "coldCleanup", default)]
    pub cold_cleanup: Vec<String>,
    #[serde(rename = "coldCleanupOk", default)]
    pub cold_cleanup_ok: bool,
    #[serde(rename = "deleted", default)]
    pub deleted: bool,
    #[serde(rename = "entriesRemoved", default)]
    pub entries_removed: i32,
    #[serde(rename = "projectsDeleted", default)]
    pub projects_deleted: Vec<String>,
    #[serde(rename = "tokensRemoved", default)]
    pub tokens_removed: i32,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UserDeletionPreview {
    #[serde(rename = "dryRun", default)]
    pub dry_run: bool,
    #[serde(rename = "wouldDelete", default)]
    pub would_delete: UserDeletionPreviewWouldDelete,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UserDeletionPreviewWouldDelete {
    #[serde(rename = "email", default, skip_serializing_if = "none_or_empty")]
    pub email: Option<String>,
    #[serde(rename = "entries", default)]
    pub entries: i32,
    #[serde(rename = "ownedProjects", default)]
    pub owned_projects: Vec<String>,
    #[serde(rename = "tokens", default)]
    pub tokens: i32,
    #[serde(rename = "userId", default)]
    pub user_id: String,
}
