// Code generated by clients/gen. DO NOT EDIT.
// swiftlint:disable all
//
// Scenario dispatch: calls the routes.json method a scenario names, with the
// scenario's wire-form args, and returns the result as JSON. Every method is
// called directly, so a method missing from the SDK fails compilation.

import Foundation
@testable import Novamem

struct Clients: Sendable {
    let client: Client
    let management: Management
    let admin: Admin
}

private func args(_ d: Data) -> [String: JSONValue] {
    (try? JSONDecoder().decode([String: JSONValue].self, from: d)) ?? [:]
}

private func req<T: Decodable>(_ t: T.Type, _ d: Data) throws -> T {
    try JSONDecoder().decode(T.self, from: d)
}

private func enc<T: Encodable>(_ v: T) throws -> Data {
    try JSONEncoder().encode(v)
}

private func str(_ a: [String: JSONValue], _ k: String) -> String? {
    if case .string(let s) = a[k] { return s }
    return nil
}

private func int(_ a: [String: JSONValue], _ k: String) -> Int? {
    if case .number(let n) = a[k] { return Int(n) }
    return nil
}

private func bool(_ a: [String: JSONValue], _ k: String) -> Bool? {
    if case .bool(let b) = a[k] { return b }
    return nil
}

private func list(_ a: [String: JSONValue], _ k: String) -> [JSONValue] {
    if case .array(let v) = a[k] { return v }
    return []
}


let dispatchTable: [String: @Sendable (Clients, Data) async throws -> Data] = [
    "Admin.DeleteUser": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.admin.deleteUser(id: str(a, "id") ?? ""))
    },
    "Admin.ListUsers": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.admin.listUsers())
    },
    "Admin.PreviewDeleteUser": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.admin.previewDeleteUser(id: str(a, "id") ?? ""))
    },
    "Admin.ProvisionUser": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.admin.provisionUser(req(ProvisionUserRequest.self, d)))
    },
    "Admin.RevokeUserToken": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.admin.revokeUserToken(token: str(a, "token") ?? ""))
    },
    "Admin.SetUserQuota": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.admin.setUserQuota(id: str(a, "id") ?? "", maxEntries: int(a, "maxEntries"), writesPerMinute: int(a, "writesPerMinute")))
    },
    "Client.Capture": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.capture(req(CaptureRequest.self, d)))
    },
    "Client.Context": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.context(req(ContextRequest.self, d)))
    },
    "Client.ContextPrefix": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.contextPrefix(project: str(a, "project")))
    },
    "Client.Forget": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.forget(req(ForgetRequest.self, d)))
    },
    "Client.Health": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.health())
    },
    "Client.Neighbors": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.neighbors(req(NeighborsRequest.self, d)))
    },
    "Client.Recent": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.recent(req(RecentRequest.self, d)))
    },
    "Client.Remember": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.remember(req(CaptureRequest.self, d)))
    },
    "Client.Search": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.search(req(SearchRequest.self, d)))
    },
    "Client.SessionRecap": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.sessionRecap(req(SessionRecapRequest.self, d)))
    },
    "Client.Stats": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.stats())
    },
    "Client.Today": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.today(req(RecentRequest.self, d)))
    },
    "Client.Update": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.client.update(id: str(a, "id") ?? "", req(UpdateRequest.self, d)))
    },
    "Management.ActiveProject": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.activeProject())
    },
    "Management.AddProjectMember": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.addProjectMember(id: str(a, "id") ?? "", email: str(a, "email") ?? "", role: str(a, "role")))
    },
    "Management.Adoption": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.adoption(client: str(a, "client")))
    },
    "Management.Changes": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.changes(since: str(a, "since"), afterSeq: int(a, "afterSeq").map(Int64.init), limit: int(a, "limit")))
    },
    "Management.ClearActiveProject": { c, d in
        let a = args(d)
        _ = a
        try await c.management.clearActiveProject()
        return Data("null".utf8)
    },
    "Management.CreateProject": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.createProject(name: str(a, "name") ?? ""))
    },
    "Management.Decay": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.decay(effectiveDays: int(a, "effectiveDays")))
    },
    "Management.DeleteProject": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.deleteProject(id: str(a, "id") ?? ""))
    },
    "Management.Evaluate": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.evaluate(suite: str(a, "suite")))
    },
    "Management.Export": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.export(afterId: str(a, "afterId"), limit: int(a, "limit")))
    },
    "Management.Hygiene": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.hygiene(k: int(a, "k")))
    },
    "Management.Import": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.`import`(entries: list(a, "entries")))
    },
    "Management.ListProjectMembers": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.listProjectMembers(id: str(a, "id") ?? ""))
    },
    "Management.ListProjects": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.listProjects())
    },
    "Management.ListTokens": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.listTokens())
    },
    "Management.MintToken": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.mintToken(req(MintTokenRequest.self, d)))
    },
    "Management.Observe": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.observe(project: str(a, "project"), limit: int(a, "limit")))
    },
    "Management.RemoveProjectMember": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.removeProjectMember(id: str(a, "id") ?? "", userId: str(a, "userId") ?? ""))
    },
    "Management.RemoveProjectMemberByUsername": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.removeProjectMemberByUsername(id: str(a, "id") ?? "", username: str(a, "username") ?? ""))
    },
    "Management.RevokeToken": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.revokeToken(hash: str(a, "hash") ?? ""))
    },
    "Management.SetActiveProject": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.setActiveProject(project: str(a, "project") ?? ""))
    },
    "Management.Usage": { c, d in
        let a = args(d)
        _ = a
        return try enc(await c.management.usage())
    },
]
