// Code generated by clients/gen. DO NOT EDIT.
//
// Scenario dispatch: calls the routes.json method a scenario names, with the
// scenario's wire-form args. Every method is called directly, so a method
// missing from the SDK fails compilation. With async set, the …Async
// variant runs and is cancelled after cancelAfterMs.

package com.azrtydxb.novamem;

import com.azrtydxb.novamem.types.Types;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

final class Dispatch {
  private Dispatch() {}

  /** The three clients a scenario can call. */
  record Clients(Client client, Management management, Admin admin) {}

  /** One scenario call. */
  interface Fn {
    Object call(Clients c, JsonNode args, boolean async, long cancelAfterMs) throws Exception;
  }

  private static String str(JsonNode a, String k) {
    return a != null && a.path(k).isTextual() ? a.get(k).asText() : null;
  }

  private static Integer i32(JsonNode a, String k) {
    return a != null && a.path(k).isNumber() ? a.get(k).asInt() : null;
  }

  private static Long i64(JsonNode a, String k) {
    return a != null && a.path(k).isNumber() ? a.get(k).asLong() : null;
  }

  private static List<?> list(JsonNode a, String k) {
    return a != null && a.path(k).isArray()
        ? Json.MAPPER.convertValue(a.get(k), List.class)
        : List.of();
  }

  private static <T> T req(JsonNode a, Class<T> cls) {
    return Json.MAPPER.convertValue(a == null ? Json.MAPPER.createObjectNode() : a, cls);
  }

  private static Object nil(Runnable r) {
    r.run();
    return null;
  }

  private static Object run(CompletableFuture<?> f, long cancelAfterMs) {
    if (cancelAfterMs > 0) {
      CompletableFuture.delayedExecutor(cancelAfterMs, TimeUnit.MILLISECONDS)
          .execute(() -> f.cancel(true));
    }
    return f.join();
  }

  static final Map<String, Fn> TABLE =
      Map.ofEntries(
          Map.entry(
              "Admin.DeleteUser",
              (c, a, async, ms) ->
                  async
                      ? run(c.admin().deleteUserAsync(str(a, "id")), ms)
                      : c.admin().deleteUser(str(a, "id"))),
          Map.entry(
              "Admin.ListUsers",
              (c, a, async, ms) ->
                  async ? run(c.admin().listUsersAsync(), ms) : c.admin().listUsers()),
          Map.entry(
              "Admin.PreviewDeleteUser",
              (c, a, async, ms) ->
                  async
                      ? run(c.admin().previewDeleteUserAsync(str(a, "id")), ms)
                      : c.admin().previewDeleteUser(str(a, "id"))),
          Map.entry(
              "Admin.ProvisionUser",
              (c, a, async, ms) ->
                  async
                      ? run(
                          c.admin().provisionUserAsync(req(a, Types.ProvisionUserRequest.class)),
                          ms)
                      : c.admin().provisionUser(req(a, Types.ProvisionUserRequest.class))),
          Map.entry(
              "Admin.RevokeUserToken",
              (c, a, async, ms) ->
                  async
                      ? run(c.admin().revokeUserTokenAsync(str(a, "token")), ms)
                      : c.admin().revokeUserToken(str(a, "token"))),
          Map.entry(
              "Admin.SetUserQuota",
              (c, a, async, ms) ->
                  async
                      ? run(
                          c.admin()
                              .setUserQuotaAsync(
                                  str(a, "id"), i32(a, "maxEntries"), i32(a, "writesPerMinute")),
                          ms)
                      : c.admin()
                          .setUserQuota(
                              str(a, "id"), i32(a, "maxEntries"), i32(a, "writesPerMinute"))),
          Map.entry(
              "Client.Capture",
              (c, a, async, ms) ->
                  async
                      ? run(c.client().captureAsync(req(a, Types.CaptureRequest.class)), ms)
                      : c.client().capture(req(a, Types.CaptureRequest.class))),
          Map.entry(
              "Client.Context",
              (c, a, async, ms) ->
                  async
                      ? run(c.client().contextAsync(req(a, Types.ContextRequest.class)), ms)
                      : c.client().context(req(a, Types.ContextRequest.class))),
          Map.entry(
              "Client.ContextPrefix",
              (c, a, async, ms) ->
                  async
                      ? run(c.client().contextPrefixAsync(str(a, "project")), ms)
                      : c.client().contextPrefix(str(a, "project"))),
          Map.entry(
              "Client.Forget",
              (c, a, async, ms) ->
                  async
                      ? run(c.client().forgetAsync(req(a, Types.ForgetRequest.class)), ms)
                      : c.client().forget(req(a, Types.ForgetRequest.class))),
          Map.entry(
              "Client.Health",
              (c, a, async, ms) -> async ? run(c.client().healthAsync(), ms) : c.client().health()),
          Map.entry(
              "Client.Neighbors",
              (c, a, async, ms) ->
                  async
                      ? run(c.client().neighborsAsync(req(a, Types.NeighborsRequest.class)), ms)
                      : c.client().neighbors(req(a, Types.NeighborsRequest.class))),
          Map.entry(
              "Client.Recent",
              (c, a, async, ms) ->
                  async
                      ? run(c.client().recentAsync(req(a, Types.RecentRequest.class)), ms)
                      : c.client().recent(req(a, Types.RecentRequest.class))),
          Map.entry(
              "Client.Remember",
              (c, a, async, ms) ->
                  async
                      ? run(c.client().rememberAsync(req(a, Types.CaptureRequest.class)), ms)
                      : c.client().remember(req(a, Types.CaptureRequest.class))),
          Map.entry(
              "Client.Search",
              (c, a, async, ms) ->
                  async
                      ? run(c.client().searchAsync(req(a, Types.SearchRequest.class)), ms)
                      : c.client().search(req(a, Types.SearchRequest.class))),
          Map.entry(
              "Client.SessionRecap",
              (c, a, async, ms) ->
                  async
                      ? run(
                          c.client().sessionRecapAsync(req(a, Types.SessionRecapRequest.class)), ms)
                      : c.client().sessionRecap(req(a, Types.SessionRecapRequest.class))),
          Map.entry(
              "Client.Stats",
              (c, a, async, ms) -> async ? run(c.client().statsAsync(), ms) : c.client().stats()),
          Map.entry(
              "Client.Today",
              (c, a, async, ms) ->
                  async
                      ? run(c.client().todayAsync(req(a, Types.RecentRequest.class)), ms)
                      : c.client().today(req(a, Types.RecentRequest.class))),
          Map.entry(
              "Client.Update",
              (c, a, async, ms) ->
                  async
                      ? run(
                          c.client().updateAsync(str(a, "id"), req(a, Types.UpdateRequest.class)),
                          ms)
                      : c.client().update(str(a, "id"), req(a, Types.UpdateRequest.class))),
          Map.entry(
              "Management.ActiveProject",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().activeProjectAsync(), ms)
                      : c.management().activeProject()),
          Map.entry(
              "Management.AddProjectMember",
              (c, a, async, ms) ->
                  async
                      ? run(
                          c.management()
                              .addProjectMemberAsync(str(a, "id"), str(a, "email"), str(a, "role")),
                          ms)
                      : c.management()
                          .addProjectMember(str(a, "id"), str(a, "email"), str(a, "role"))),
          Map.entry(
              "Management.Adoption",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().adoptionAsync(str(a, "client")), ms)
                      : c.management().adoption(str(a, "client"))),
          Map.entry(
              "Management.Changes",
              (c, a, async, ms) ->
                  async
                      ? run(
                          c.management()
                              .changesAsync(str(a, "since"), i64(a, "afterSeq"), i32(a, "limit")),
                          ms)
                      : c.management()
                          .changes(str(a, "since"), i64(a, "afterSeq"), i32(a, "limit"))),
          Map.entry(
              "Management.ClearActiveProject",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().clearActiveProjectAsync(), ms)
                      : nil(() -> c.management().clearActiveProject())),
          Map.entry(
              "Management.CreateProject",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().createProjectAsync(str(a, "name")), ms)
                      : c.management().createProject(str(a, "name"))),
          Map.entry(
              "Management.Decay",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().decayAsync(i32(a, "effectiveDays")), ms)
                      : c.management().decay(i32(a, "effectiveDays"))),
          Map.entry(
              "Management.DeleteProject",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().deleteProjectAsync(str(a, "id")), ms)
                      : c.management().deleteProject(str(a, "id"))),
          Map.entry(
              "Management.Evaluate",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().evaluateAsync(str(a, "suite")), ms)
                      : c.management().evaluate(str(a, "suite"))),
          Map.entry(
              "Management.Export",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().exportAsync(str(a, "afterId"), i32(a, "limit")), ms)
                      : c.management().export(str(a, "afterId"), i32(a, "limit"))),
          Map.entry(
              "Management.Hygiene",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().hygieneAsync(i32(a, "k")), ms)
                      : c.management().hygiene(i32(a, "k"))),
          Map.entry(
              "Management.Import",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().importEntriesAsync(list(a, "entries")), ms)
                      : c.management().importEntries(list(a, "entries"))),
          Map.entry(
              "Management.ListProjectMembers",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().listProjectMembersAsync(str(a, "id")), ms)
                      : c.management().listProjectMembers(str(a, "id"))),
          Map.entry(
              "Management.ListProjects",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().listProjectsAsync(), ms)
                      : c.management().listProjects()),
          Map.entry(
              "Management.ListTokens",
              (c, a, async, ms) ->
                  async ? run(c.management().listTokensAsync(), ms) : c.management().listTokens()),
          Map.entry(
              "Management.MintToken",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().mintTokenAsync(req(a, Types.MintTokenRequest.class)), ms)
                      : c.management().mintToken(req(a, Types.MintTokenRequest.class))),
          Map.entry(
              "Management.Observe",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().observeAsync(str(a, "project"), i32(a, "limit")), ms)
                      : c.management().observe(str(a, "project"), i32(a, "limit"))),
          Map.entry(
              "Management.RemoveProjectMember",
              (c, a, async, ms) ->
                  async
                      ? run(
                          c.management().removeProjectMemberAsync(str(a, "id"), str(a, "userId")),
                          ms)
                      : c.management().removeProjectMember(str(a, "id"), str(a, "userId"))),
          Map.entry(
              "Management.RemoveProjectMemberByUsername",
              (c, a, async, ms) ->
                  async
                      ? run(
                          c.management()
                              .removeProjectMemberByUsernameAsync(str(a, "id"), str(a, "username")),
                          ms)
                      : c.management()
                          .removeProjectMemberByUsername(str(a, "id"), str(a, "username"))),
          Map.entry(
              "Management.RevokeToken",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().revokeTokenAsync(str(a, "hash")), ms)
                      : c.management().revokeToken(str(a, "hash"))),
          Map.entry(
              "Management.SetActiveProject",
              (c, a, async, ms) ->
                  async
                      ? run(c.management().setActiveProjectAsync(str(a, "project")), ms)
                      : c.management().setActiveProject(str(a, "project"))),
          Map.entry(
              "Management.Usage",
              (c, a, async, ms) ->
                  async ? run(c.management().usageAsync(), ms) : c.management().usage()));
}
