apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuvryn-sync-deployer
  namespace: novamem
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kuvryn-sync-deployer
  namespace: novamem
rules:
  - apiGroups: [""]
    resources: [configmaps, services, persistentvolumeclaims]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [pods, events]
    verbs: [get, list, watch]
  - apiGroups: [apps]
    resources: [deployments, statefulsets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [cert-manager.io]
    resources: [certificates]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [replicasets]
    verbs: [get, list, watch]
  - apiGroups: [discovery.k8s.io]
    resources: [endpointslices]
    verbs: [get, list, watch]
  - apiGroups: [policy]
    resources: [poddisruptionbudgets]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuvryn-sync-deployer
  namespace: novamem
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kuvryn-sync-deployer
subjects:
  - kind: ServiceAccount
    name: kuvryn-sync-deployer
    namespace: novamem
