// Code generated by clients/gen. DO NOT EDIT.
//
// The 41 operations as C functions, each a blocking call into the Rust SDK
// on the library's runtime. Declared in clients/c/include/novamem.h.

#![allow(non_camel_case_types, clippy::all, unused_unsafe, unused_mut)]
// Formatting a generated file would fight the generator; rustfmt alone
// sets the `rustfmt` cfg, so the compiler never sees this attribute.
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::os::raw::c_char;

use crate::conv::*;
use crate::ffi_types::*;
use crate::{block_on, guard, handle, novamem_admin, novamem_client, novamem_error, novamem_management, novamem_status};


#[no_mangle]
pub unsafe extern "C" fn novamem_admin_delete_user(
    h: *const novamem_admin,
    id: *const c_char,
    out: *mut *mut novamem_user_deletion,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "delete-user")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "delete-user", message: "out must not be NULL".into() });
        }
        let p_id = c_str(id).unwrap_or_default();
        let r = block_on(h.0.delete_user(&p_id))?;
        write_out(out, boxed(novamem_user_deletion::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_admin_list_users(
    h: *const novamem_admin,
    out: *mut *mut novamem_admin_user_list,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "list-users")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "list-users", message: "out must not be NULL".into() });
        }
        let r = block_on(h.0.list_users())?;
        write_out(out, boxed(novamem_admin_user_list::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_admin_preview_delete_user(
    h: *const novamem_admin,
    id: *const c_char,
    out: *mut *mut novamem_user_deletion_preview,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "preview-delete-user")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "preview-delete-user", message: "out must not be NULL".into() });
        }
        let p_id = c_str(id).unwrap_or_default();
        let r = block_on(h.0.preview_delete_user(&p_id))?;
        write_out(out, boxed(novamem_user_deletion_preview::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_admin_provision_user(
    h: *const novamem_admin,
    request: *const novamem_provision_user_request,
    out: *mut *mut novamem_provisioned_user,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "provision-user")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "provision-user", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.provision_user(p_request))?;
        write_out(out, boxed(novamem_provisioned_user::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_admin_revoke_user_token(
    h: *const novamem_admin,
    token: *const c_char,
    out: *mut *mut novamem_revoke_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "revoke-user-token")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "revoke-user-token", message: "out must not be NULL".into() });
        }
        let p_token = c_str(token).unwrap_or_default();
        let r = block_on(h.0.revoke_user_token(&p_token))?;
        write_out(out, boxed(novamem_revoke_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_admin_set_user_quota(
    h: *const novamem_admin,
    id: *const c_char,
    max_entries: *const i32,
    writes_per_minute: *const i32,
    out: *mut *mut novamem_quota_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "set-user-quota")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "set-user-quota", message: "out must not be NULL".into() });
        }
        let p_id = c_str(id).unwrap_or_default();
        let p_max_entries = opt_num(max_entries);
        let p_writes_per_minute = opt_num(writes_per_minute);
        let r = block_on(h.0.set_user_quota(&p_id, p_max_entries, p_writes_per_minute))?;
        write_out(out, boxed(novamem_quota_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_capture(
    h: *const novamem_client,
    request: *const novamem_capture_request,
    out: *mut *mut novamem_capture_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "capture")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "capture", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.capture(p_request))?;
        write_out(out, boxed(novamem_capture_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_context(
    h: *const novamem_client,
    request: *const novamem_context_request,
    out: *mut *mut novamem_search_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "context")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "context", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.context(p_request))?;
        write_out(out, boxed(novamem_search_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_context_prefix(
    h: *const novamem_client,
    project: *const c_char,
    out: *mut *mut novamem_context_prefix,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "context-prefix")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "context-prefix", message: "out must not be NULL".into() });
        }
        let p_project = c_str(project);
        let r = block_on(h.0.context_prefix(p_project.as_deref()))?;
        write_out(out, boxed(novamem_context_prefix::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_forget(
    h: *const novamem_client,
    request: *const novamem_forget_request,
    out: *mut *mut novamem_forget_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "forget")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "forget", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.forget(p_request))?;
        write_out(out, boxed(novamem_forget_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_health(
    h: *const novamem_client,
    out: *mut bool,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "health")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "health", message: "out must not be NULL".into() });
        }
        let r = block_on(h.0.health())?;
        write_out(out, r);
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_neighbors(
    h: *const novamem_client,
    request: *const novamem_neighbors_request,
    out: *mut *mut novamem_search_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "neighbors")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "neighbors", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.neighbors(p_request))?;
        write_out(out, boxed(novamem_search_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_recent(
    h: *const novamem_client,
    request: *const novamem_recent_request,
    out: *mut *mut novamem_entry_list,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "recent")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "recent", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.recent(p_request))?;
        write_out(out, boxed(novamem_entry_list::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_remember(
    h: *const novamem_client,
    request: *const novamem_capture_request,
    out: *mut *mut novamem_remember_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "remember")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "remember", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.remember(p_request))?;
        write_out(out, boxed(novamem_remember_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_search(
    h: *const novamem_client,
    request: *const novamem_search_request,
    out: *mut *mut novamem_search_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "search")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "search", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.search(p_request))?;
        write_out(out, boxed(novamem_search_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_session_recap(
    h: *const novamem_client,
    request: *const novamem_session_recap_request,
    out: *mut *mut novamem_session_recap_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "session-recap")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "session-recap", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.session_recap(p_request))?;
        write_out(out, boxed(novamem_session_recap_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_stats(
    h: *const novamem_client,
    out: *mut *mut novamem_stats,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "stats")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "stats", message: "out must not be NULL".into() });
        }
        let r = block_on(h.0.stats())?;
        write_out(out, boxed(novamem_stats::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_today(
    h: *const novamem_client,
    request: *const novamem_recent_request,
    out: *mut *mut novamem_entry_list,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "recent")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "recent", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.today(p_request))?;
        write_out(out, boxed(novamem_entry_list::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_client_update(
    h: *const novamem_client,
    id: *const c_char,
    request: *const novamem_update_request,
    out: *mut *mut novamem_update_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "update")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "update", message: "out must not be NULL".into() });
        }
        let p_id = c_str(id).unwrap_or_default();
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.update(&p_id, p_request))?;
        write_out(out, boxed(novamem_update_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_active_project(
    h: *const novamem_management,
    out: *mut *mut novamem_active_project,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "active-project")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "active-project", message: "out must not be NULL".into() });
        }
        let r = block_on(h.0.active_project())?;
        write_out(out, boxed(novamem_active_project::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_add_project_member(
    h: *const novamem_management,
    id: *const c_char,
    email: *const c_char,
    role: *const c_char,
    out: *mut *mut novamem_member_added,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "add-member")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "add-member", message: "out must not be NULL".into() });
        }
        let p_id = c_str(id).unwrap_or_default();
        let p_email = c_str(email).unwrap_or_default();
        let p_role = c_str(role);
        let r = block_on(h.0.add_project_member(&p_id, &p_email, p_role.as_deref()))?;
        write_out(out, boxed(novamem_member_added::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_adoption(
    h: *const novamem_management,
    client: *const c_char,
    out: *mut *mut novamem_adoption_report,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "adoption")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "adoption", message: "out must not be NULL".into() });
        }
        let p_client = c_str(client);
        let r = block_on(h.0.adoption(p_client.as_deref()))?;
        write_out(out, boxed(novamem_adoption_report::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_changes(
    h: *const novamem_management,
    since: *const c_char,
    after_seq: *const i64,
    limit: *const i32,
    out: *mut *mut novamem_change_feed,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "changes")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "changes", message: "out must not be NULL".into() });
        }
        let p_since = c_str(since);
        let p_after_seq = opt_num(after_seq);
        let p_limit = opt_num(limit);
        let r = block_on(h.0.changes(p_since.as_deref(), p_after_seq, p_limit))?;
        write_out(out, boxed(novamem_change_feed::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_clear_active_project(
    h: *const novamem_management,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "clear-active-project")?;
        let r = block_on(h.0.clear_active_project())?;
        let () = r;
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_create_project(
    h: *const novamem_management,
    name: *const c_char,
    out: *mut *mut novamem_project,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "create-project")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "create-project", message: "out must not be NULL".into() });
        }
        let p_name = c_str(name).unwrap_or_default();
        let r = block_on(h.0.create_project(&p_name))?;
        write_out(out, boxed(novamem_project::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_decay(
    h: *const novamem_management,
    effective_days: *const i32,
    out: *mut *mut novamem_decay_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "decay")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "decay", message: "out must not be NULL".into() });
        }
        let p_effective_days = opt_num(effective_days);
        let r = block_on(h.0.decay(p_effective_days))?;
        write_out(out, boxed(novamem_decay_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_delete_project(
    h: *const novamem_management,
    id: *const c_char,
    out: *mut *mut novamem_project_deleted,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "delete-project")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "delete-project", message: "out must not be NULL".into() });
        }
        let p_id = c_str(id).unwrap_or_default();
        let r = block_on(h.0.delete_project(&p_id))?;
        write_out(out, boxed(novamem_project_deleted::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_evaluate(
    h: *const novamem_management,
    suite: *const c_char,
    out: *mut *mut novamem_evaluate_report,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "evaluate")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "evaluate", message: "out must not be NULL".into() });
        }
        let p_suite = c_str(suite);
        let r = block_on(h.0.evaluate(p_suite.as_deref()))?;
        write_out(out, boxed(novamem_evaluate_report::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_export(
    h: *const novamem_management,
    after_id: *const c_char,
    limit: *const i32,
    out: *mut *mut novamem_export_page,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "export")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "export", message: "out must not be NULL".into() });
        }
        let p_after_id = c_str(after_id);
        let p_limit = opt_num(limit);
        let r = block_on(h.0.export(p_after_id.as_deref(), p_limit))?;
        write_out(out, boxed(novamem_export_page::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_hygiene(
    h: *const novamem_management,
    k: *const i32,
    out: *mut *mut novamem_hygiene_report,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "hygiene")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "hygiene", message: "out must not be NULL".into() });
        }
        let p_k = opt_num(k);
        let r = block_on(h.0.hygiene(p_k))?;
        write_out(out, boxed(novamem_hygiene_report::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_import(
    h: *const novamem_management,
    entries_json: *const c_char,
    out: *mut *mut novamem_import_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "import")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "import", message: "out must not be NULL".into() });
        }
        let p_entries: Vec<serde_json::Value> = c_json(entries_json).unwrap_or_default();
        let r = block_on(h.0.import(p_entries))?;
        write_out(out, boxed(novamem_import_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_list_project_members(
    h: *const novamem_management,
    id: *const c_char,
    out: *mut *mut novamem_member_list,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "list-members")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "list-members", message: "out must not be NULL".into() });
        }
        let p_id = c_str(id).unwrap_or_default();
        let r = block_on(h.0.list_project_members(&p_id))?;
        write_out(out, boxed(novamem_member_list::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_list_projects(
    h: *const novamem_management,
    out: *mut *mut novamem_project_list,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "list-projects")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "list-projects", message: "out must not be NULL".into() });
        }
        let r = block_on(h.0.list_projects())?;
        write_out(out, boxed(novamem_project_list::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_list_tokens(
    h: *const novamem_management,
    out: *mut *mut novamem_token_list,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "list-tokens")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "list-tokens", message: "out must not be NULL".into() });
        }
        let r = block_on(h.0.list_tokens())?;
        write_out(out, boxed(novamem_token_list::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_mint_token(
    h: *const novamem_management,
    request: *const novamem_mint_token_request,
    out: *mut *mut novamem_minted_token,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "mint-token")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "mint-token", message: "out must not be NULL".into() });
        }
        let p_request = request.as_ref().map(|r| r.to_rust()).unwrap_or_default();
        let r = block_on(h.0.mint_token(p_request))?;
        write_out(out, boxed(novamem_minted_token::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_observe(
    h: *const novamem_management,
    project: *const c_char,
    limit: *const i32,
    out: *mut *mut novamem_observe_result,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "observe")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "observe", message: "out must not be NULL".into() });
        }
        let p_project = c_str(project);
        let p_limit = opt_num(limit);
        let r = block_on(h.0.observe(p_project.as_deref(), p_limit))?;
        write_out(out, boxed(novamem_observe_result::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_remove_project_member(
    h: *const novamem_management,
    id: *const c_char,
    user_id: *const c_char,
    out: *mut *mut novamem_member_removed,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "remove-member")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "remove-member", message: "out must not be NULL".into() });
        }
        let p_id = c_str(id).unwrap_or_default();
        let p_user_id = c_str(user_id).unwrap_or_default();
        let r = block_on(h.0.remove_project_member(&p_id, &p_user_id))?;
        write_out(out, boxed(novamem_member_removed::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_remove_project_member_by_username(
    h: *const novamem_management,
    id: *const c_char,
    username: *const c_char,
    out: *mut *mut novamem_member_removed,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "remove-member")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "remove-member", message: "out must not be NULL".into() });
        }
        let p_id = c_str(id).unwrap_or_default();
        let p_username = c_str(username).unwrap_or_default();
        let r = block_on(h.0.remove_project_member_by_username(&p_id, &p_username))?;
        write_out(out, boxed(novamem_member_removed::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_revoke_token(
    h: *const novamem_management,
    hash: *const c_char,
    out: *mut *mut novamem_token_deleted,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "revoke-token")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "revoke-token", message: "out must not be NULL".into() });
        }
        let p_hash = c_str(hash).unwrap_or_default();
        let r = block_on(h.0.revoke_token(&p_hash))?;
        write_out(out, boxed(novamem_token_deleted::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_set_active_project(
    h: *const novamem_management,
    project: *const c_char,
    out: *mut *mut novamem_active_project,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "set-active-project")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "set-active-project", message: "out must not be NULL".into() });
        }
        let p_project = c_str(project).unwrap_or_default();
        let r = block_on(h.0.set_active_project(&p_project))?;
        write_out(out, boxed(novamem_active_project::to_c(&r)));
        Ok(())
    })
}

#[no_mangle]
pub unsafe extern "C" fn novamem_management_usage(
    h: *const novamem_management,
    out: *mut *mut novamem_usage,
    err: *mut novamem_error,
) -> novamem_status {
    guard(err, || {
        let h = handle(h, "usage")?;
        // Checked before the call: a result with nowhere to go would leak.
        if out.is_null() {
            return Err(crate::FfiError::Local { op: "usage", message: "out must not be NULL".into() });
        }
        let r = block_on(h.0.usage())?;
        write_out(out, boxed(novamem_usage::to_c(&r)));
        Ok(())
    })
}

/// Test-only: calls a routes.json method by name with wire-form JSON args,
/// through the typed functions above (so the C structs and their
/// conversions are what the scenarios exercise), and returns the result as
/// JSON text.
#[cfg(feature = "test-dispatch")]
#[no_mangle]
pub unsafe extern "C" fn novamem_test_call_by_name(
    base_url: *const c_char,
    token: *const c_char,
    timeout_ms: u32,
    method: *const c_char,
    args_json: *const c_char,
    result_json: *mut *mut c_char,
    err: *mut novamem_error,
) -> novamem_status {
    use crate::test_args::*;
    let a: serde_json::Value = c_json(args_json).unwrap_or(serde_json::Value::Null);
    let method = c_str(method).unwrap_or_default();
    match method.as_str() {
        "Admin.DeleteUser" => {
            let h = crate::novamem_admin_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_id = arg_cstring(&a, "id");
            let mut out: *mut novamem_user_deletion = std::ptr::null_mut();
            let st = novamem_admin_delete_user(h, cstr_ptr(&a_id), &mut out, err);
            crate::novamem_admin_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_user_deletion_free(out);
            }
            st
        }
        "Admin.ListUsers" => {
            let h = crate::novamem_admin_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut out: *mut novamem_admin_user_list = std::ptr::null_mut();
            let st = novamem_admin_list_users(h, &mut out, err);
            crate::novamem_admin_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_admin_user_list_free(out);
            }
            st
        }
        "Admin.PreviewDeleteUser" => {
            let h = crate::novamem_admin_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_id = arg_cstring(&a, "id");
            let mut out: *mut novamem_user_deletion_preview = std::ptr::null_mut();
            let st = novamem_admin_preview_delete_user(h, cstr_ptr(&a_id), &mut out, err);
            crate::novamem_admin_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_user_deletion_preview_free(out);
            }
            st
        }
        "Admin.ProvisionUser" => {
            let h = crate::novamem_admin_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_provision_user_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_provisioned_user = std::ptr::null_mut();
            let st = novamem_admin_provision_user(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_admin_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_provisioned_user_free(out);
            }
            st
        }
        "Admin.RevokeUserToken" => {
            let h = crate::novamem_admin_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_token = arg_cstring(&a, "token");
            let mut out: *mut novamem_revoke_result = std::ptr::null_mut();
            let st = novamem_admin_revoke_user_token(h, cstr_ptr(&a_token), &mut out, err);
            crate::novamem_admin_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_revoke_result_free(out);
            }
            st
        }
        "Admin.SetUserQuota" => {
            let h = crate::novamem_admin_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_id = arg_cstring(&a, "id");
            let a_max_entries: Option<i32> = arg_value(&a, "maxEntries");
            let a_writes_per_minute: Option<i32> = arg_value(&a, "writesPerMinute");
            let mut out: *mut novamem_quota_result = std::ptr::null_mut();
            let st = novamem_admin_set_user_quota(h, cstr_ptr(&a_id), opt_ptr(&a_max_entries), opt_ptr(&a_writes_per_minute), &mut out, err);
            crate::novamem_admin_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_quota_result_free(out);
            }
            st
        }
        "Client.Capture" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_capture_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_capture_result = std::ptr::null_mut();
            let st = novamem_client_capture(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_capture_result_free(out);
            }
            st
        }
        "Client.Context" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_context_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_search_result = std::ptr::null_mut();
            let st = novamem_client_context(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_search_result_free(out);
            }
            st
        }
        "Client.ContextPrefix" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_project = arg_cstring(&a, "project");
            let mut out: *mut novamem_context_prefix = std::ptr::null_mut();
            let st = novamem_client_context_prefix(h, cstr_ptr(&a_project), &mut out, err);
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_context_prefix_free(out);
            }
            st
        }
        "Client.Forget" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_forget_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_forget_result = std::ptr::null_mut();
            let st = novamem_client_forget(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_forget_result_free(out);
            }
            st
        }
        "Client.Health" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut out = false;
            let st = novamem_client_health(h, &mut out, err);
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&out)));
            }
            st
        }
        "Client.Neighbors" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_neighbors_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_search_result = std::ptr::null_mut();
            let st = novamem_client_neighbors(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_search_result_free(out);
            }
            st
        }
        "Client.Recent" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_recent_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_entry_list = std::ptr::null_mut();
            let st = novamem_client_recent(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_entry_list_free(out);
            }
            st
        }
        "Client.Remember" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_capture_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_remember_result = std::ptr::null_mut();
            let st = novamem_client_remember(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_remember_result_free(out);
            }
            st
        }
        "Client.Search" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_search_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_search_result = std::ptr::null_mut();
            let st = novamem_client_search(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_search_result_free(out);
            }
            st
        }
        "Client.SessionRecap" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_session_recap_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_session_recap_result = std::ptr::null_mut();
            let st = novamem_client_session_recap(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_session_recap_result_free(out);
            }
            st
        }
        "Client.Stats" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut out: *mut novamem_stats = std::ptr::null_mut();
            let st = novamem_client_stats(h, &mut out, err);
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_stats_free(out);
            }
            st
        }
        "Client.Today" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_recent_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_entry_list = std::ptr::null_mut();
            let st = novamem_client_today(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_entry_list_free(out);
            }
            st
        }
        "Client.Update" => {
            let h = crate::novamem_client_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_id = arg_cstring(&a, "id");
            let mut req = novamem_update_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_update_result = std::ptr::null_mut();
            let st = novamem_client_update(h, cstr_ptr(&a_id), &req, &mut out, err);
            req.free_fields();
            crate::novamem_client_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_update_result_free(out);
            }
            st
        }
        "Management.ActiveProject" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut out: *mut novamem_active_project = std::ptr::null_mut();
            let st = novamem_management_active_project(h, &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_active_project_free(out);
            }
            st
        }
        "Management.AddProjectMember" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_id = arg_cstring(&a, "id");
            let a_email = arg_cstring(&a, "email");
            let a_role = arg_cstring(&a, "role");
            let mut out: *mut novamem_member_added = std::ptr::null_mut();
            let st = novamem_management_add_project_member(h, cstr_ptr(&a_id), cstr_ptr(&a_email), cstr_ptr(&a_role), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_member_added_free(out);
            }
            st
        }
        "Management.Adoption" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_client = arg_cstring(&a, "client");
            let mut out: *mut novamem_adoption_report = std::ptr::null_mut();
            let st = novamem_management_adoption(h, cstr_ptr(&a_client), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_adoption_report_free(out);
            }
            st
        }
        "Management.Changes" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_since = arg_cstring(&a, "since");
            let a_after_seq: Option<i64> = arg_value(&a, "afterSeq");
            let a_limit: Option<i32> = arg_value(&a, "limit");
            let mut out: *mut novamem_change_feed = std::ptr::null_mut();
            let st = novamem_management_changes(h, cstr_ptr(&a_since), opt_ptr(&a_after_seq), opt_ptr(&a_limit), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_change_feed_free(out);
            }
            st
        }
        "Management.ClearActiveProject" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let st = novamem_management_clear_active_project(h, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&serde_json::Value::Null)));
            }
            st
        }
        "Management.CreateProject" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_name = arg_cstring(&a, "name");
            let mut out: *mut novamem_project = std::ptr::null_mut();
            let st = novamem_management_create_project(h, cstr_ptr(&a_name), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_project_free(out);
            }
            st
        }
        "Management.Decay" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_effective_days: Option<i32> = arg_value(&a, "effectiveDays");
            let mut out: *mut novamem_decay_result = std::ptr::null_mut();
            let st = novamem_management_decay(h, opt_ptr(&a_effective_days), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_decay_result_free(out);
            }
            st
        }
        "Management.DeleteProject" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_id = arg_cstring(&a, "id");
            let mut out: *mut novamem_project_deleted = std::ptr::null_mut();
            let st = novamem_management_delete_project(h, cstr_ptr(&a_id), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_project_deleted_free(out);
            }
            st
        }
        "Management.Evaluate" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_suite = arg_cstring(&a, "suite");
            let mut out: *mut novamem_evaluate_report = std::ptr::null_mut();
            let st = novamem_management_evaluate(h, cstr_ptr(&a_suite), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_evaluate_report_free(out);
            }
            st
        }
        "Management.Export" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_after_id = arg_cstring(&a, "afterId");
            let a_limit: Option<i32> = arg_value(&a, "limit");
            let mut out: *mut novamem_export_page = std::ptr::null_mut();
            let st = novamem_management_export(h, cstr_ptr(&a_after_id), opt_ptr(&a_limit), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_export_page_free(out);
            }
            st
        }
        "Management.Hygiene" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_k: Option<i32> = arg_value(&a, "k");
            let mut out: *mut novamem_hygiene_report = std::ptr::null_mut();
            let st = novamem_management_hygiene(h, opt_ptr(&a_k), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_hygiene_report_free(out);
            }
            st
        }
        "Management.Import" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_entries = arg_json(&a, "entries");
            let mut out: *mut novamem_import_result = std::ptr::null_mut();
            let st = novamem_management_import(h, cstr_ptr(&a_entries), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_import_result_free(out);
            }
            st
        }
        "Management.ListProjectMembers" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_id = arg_cstring(&a, "id");
            let mut out: *mut novamem_member_list = std::ptr::null_mut();
            let st = novamem_management_list_project_members(h, cstr_ptr(&a_id), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_member_list_free(out);
            }
            st
        }
        "Management.ListProjects" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut out: *mut novamem_project_list = std::ptr::null_mut();
            let st = novamem_management_list_projects(h, &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_project_list_free(out);
            }
            st
        }
        "Management.ListTokens" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut out: *mut novamem_token_list = std::ptr::null_mut();
            let st = novamem_management_list_tokens(h, &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_token_list_free(out);
            }
            st
        }
        "Management.MintToken" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut req = novamem_mint_token_request::to_c(&serde_json::from_value(a.clone()).unwrap_or_default());
            let mut out: *mut novamem_minted_token = std::ptr::null_mut();
            let st = novamem_management_mint_token(h, &req, &mut out, err);
            req.free_fields();
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_minted_token_free(out);
            }
            st
        }
        "Management.Observe" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_project = arg_cstring(&a, "project");
            let a_limit: Option<i32> = arg_value(&a, "limit");
            let mut out: *mut novamem_observe_result = std::ptr::null_mut();
            let st = novamem_management_observe(h, cstr_ptr(&a_project), opt_ptr(&a_limit), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_observe_result_free(out);
            }
            st
        }
        "Management.RemoveProjectMember" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_id = arg_cstring(&a, "id");
            let a_user_id = arg_cstring(&a, "userId");
            let mut out: *mut novamem_member_removed = std::ptr::null_mut();
            let st = novamem_management_remove_project_member(h, cstr_ptr(&a_id), cstr_ptr(&a_user_id), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_member_removed_free(out);
            }
            st
        }
        "Management.RemoveProjectMemberByUsername" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_id = arg_cstring(&a, "id");
            let a_username = arg_cstring(&a, "username");
            let mut out: *mut novamem_member_removed = std::ptr::null_mut();
            let st = novamem_management_remove_project_member_by_username(h, cstr_ptr(&a_id), cstr_ptr(&a_username), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_member_removed_free(out);
            }
            st
        }
        "Management.RevokeToken" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_hash = arg_cstring(&a, "hash");
            let mut out: *mut novamem_token_deleted = std::ptr::null_mut();
            let st = novamem_management_revoke_token(h, cstr_ptr(&a_hash), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_token_deleted_free(out);
            }
            st
        }
        "Management.SetActiveProject" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let a_project = arg_cstring(&a, "project");
            let mut out: *mut novamem_active_project = std::ptr::null_mut();
            let st = novamem_management_set_active_project(h, cstr_ptr(&a_project), &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_active_project_free(out);
            }
            st
        }
        "Management.Usage" => {
            let h = crate::novamem_management_new(base_url, token, timeout_ms, err);
            if h.is_null() {
                return novamem_status::NOVAMEM_ERR;
            }
            let mut out: *mut novamem_usage = std::ptr::null_mut();
            let st = novamem_management_usage(h, &mut out, err);
            crate::novamem_management_free(h);
            if st == novamem_status::NOVAMEM_OK {
                write_out(result_json, json_to_c(Some(&(*out).to_rust())));
                novamem_usage_free(out);
            }
            st
        }
        other => {
            crate::fill_local(err, "test-call", &format!("unknown method {other}"));
            novamem_status::NOVAMEM_ERR
        }
    }
}
