// Code generated by clients/gen. DO NOT EDIT.
//
// Wire types for the novamem API, generated from docs/api/openapi.json.
// Field names are the wire names. Request timestamps accept a Date or an
// ISO string (a Date is sent as UTC with a Z by JSON.stringify).

/** Wire names of timestamp fields: the client sends these as UTC with a Z. */
export const DATETIME_FIELDS: readonly string[] = ["asOf", "expiresAt", "since"];


export interface ActiveProject {
  active: ActiveProjectActive | null;
}

export interface ActiveProjectActive {
  id?: string;
  name?: string;
}

export interface AdminUser {
  createdAt: string;
  email: string;
  entryCount: number;
  id: string;
  name: string | null;
  role: string;
  tokenCount: number;
}

export interface AdminUserList {
  users: Array<AdminUser>;
}

export interface AdoptionReport {
  diagnostics: Array<Record<string, unknown>>;
  features?: Record<string, unknown>;
  mcp: Record<string, unknown>;
  refresh?: Record<string, unknown>;
  requestedClient: string;
  requiredTools?: Array<string>;
  server: Record<string, unknown>;
}

export interface CaptureRequest {
  agentName?: string | null;
  capturedFrom?: string;
  confidence?: number;
  content: string;
  expiresAt?: string | Date;
  force?: boolean;
  metadata?: Record<string, unknown>;
  namespace?: string;
  project?: string | null;
  sensitivity?: CaptureRequestSensitivity;
  source?: string;
  sourceType?: string;
}

export type CaptureRequestSensitivity = | "public" | "internal" | "private" | "sensitive";

export interface CaptureResult {
  deduplicated?: boolean;
  embedded?: boolean;
  id: string | null;
  rejected?: string;
  superseded?: Array<string>;
  updated?: boolean;
}

export interface ChangeFeed {
  changes: Array<ChangeFeedChangesItem>;
  nextSeq?: number | null;
}

export interface ChangeFeedChangesItem {
  at?: string;
  change?: ChangeFeedChangesItemChange;
  detail?: Record<string, unknown> | null;
  entryId?: string;
  projectId?: string | null;
  seq?: number;
}

export type ChangeFeedChangesItemChange = | "created" | "updated" | "superseded" | "deleted" | "expired";

export interface ContextPrefix {
  prefix: string;
}

export interface ContextRequest {
  asOf?: string | Date | null;
  decompose?: boolean;
  expandSourceChunks?: boolean;
  includeNamespaces?: Array<string>;
  includeProjects?: Array<string>;
  k?: number;
  maxSensitivity?: ContextRequestMaxSensitivity;
  maxTokens?: number;
  message: string;
  namespace?: string;
  project?: string | null;
  weights?: ContextRequestWeights;
}

export type ContextRequestMaxSensitivity = | "public" | "internal" | "private" | "sensitive";

export interface ContextRequestWeights {
  entity?: number;
  graph?: number;
  keyword?: number;
  recency?: number;
  vector?: number;
}

export interface DecayResult {
  demoted: number;
  expired: number;
  promoted: number;
}

export interface EntryList {
  results: Array<MemoryEntry>;
}

export interface EvaluateReport {
  cases: Array<EvaluateReportCasesItem>;
  passed: boolean;
  suite: string;
  summary: EvaluateReportSummary;
}

export interface EvaluateReportCasesItem {
  name?: string;
  passed?: boolean;
}

export interface EvaluateReportSummary {
  failed?: number;
  passed?: number;
  total?: number;
}

export interface ExportPage {
  entries: Array<ExportedEntry>;
  nextAfterId: string | null;
}

export interface ExportedEntry {
  agentName: string | null;
  capturedFrom: string | null;
  confidence: number;
  content: string;
  createdAt: string;
  id: string;
  metadata: Record<string, unknown>;
  namespace: string;
  projectId: string | null;
  source: string;
  sourceType: string | null;
  updatedAt: string;
}

export interface ForgetRequest {
  id: string;
  project?: string | null;
}

export interface ForgetResult {
  coldDeleteOk?: boolean;
  deleted: boolean;
}

export interface Health {
  ok: boolean;
}

export interface HygieneReport {
  contradictionCandidates?: Array<unknown>;
  duplicateClusters?: Array<unknown>;
  lowValue?: Array<unknown>;
  orphanCandidates?: Array<unknown>;
  stale?: Array<unknown>;
  summary: HygieneReportSummary;
}

export interface HygieneReportSummary {
  contradictionCandidates?: number;
  duplicateClusters?: number;
  lowValue?: number;
  orphanCandidates?: number;
  scanned?: number;
  stale?: number;
}

export interface ImportResult {
  deduplicated: number;
  failed: Array<ImportResultFailedItem>;
  imported: number;
}

export interface ImportResultFailedItem {
  error: string;
  index: number;
}

export interface MemberAdded {
  added: boolean;
  userId: string;
  username: string;
}

export interface MemberList {
  members: Array<MemberListMembersItem>;
}

export interface MemberListMembersItem {
  joinedAt?: string;
  role?: string;
  userId?: string;
  username?: string;
}

export interface MemberRemoved {
  removed: boolean;
}

export interface MemoryEntry {
  content: string;
  id: string;
  metadata?: Record<string, unknown>;
  namespace?: string;
  project?: string | null;
  score?: number;
  signals?: MemoryEntrySignals;
  source?: string;
  tier?: MemoryEntryTier;
}

export interface MemoryEntrySignals {
  entity?: number;
  graph?: number;
  keyword?: number;
  recency?: number;
  vector?: number;
}

export type MemoryEntryTier = | "warm" | "cold";

export interface MintTokenRequest {
  expiresInDays?: number;
  label?: string;
  project?: string;
  scope?: MintTokenRequestScope;
}

export type MintTokenRequestScope = | "full" | "read_only";

export interface MintedToken {
  createdAt?: string;
  expiresAt?: string | null;
  projectId?: string | null;
  scope?: string;
  token: string;
  userId?: string;
  warning?: string;
}

export interface NeighborsRequest {
  depth?: number;
  id: string;
  includeNamespaces?: Array<string>;
  includeProjects?: Array<string>;
  k?: number;
  maxSensitivity?: NeighborsRequestMaxSensitivity;
  project?: string | null;
}

export type NeighborsRequestMaxSensitivity = | "public" | "internal" | "private" | "sensitive";

export interface ObserveResult {
  logChars?: number;
  observed?: number;
  reflected?: boolean;
}

export interface Project {
  createdAt?: string;
  id: string;
  name: string;
  ownerUserId?: string;
}

export interface ProjectDeleted {
  coldCollectionsDropped?: Array<string> | null;
  deleted: boolean;
  entriesRemoved?: number;
  graphCleared?: boolean;
}

export interface ProjectList {
  projects: Array<ProjectListItem>;
}

export interface ProjectListItem {
  createdAt?: string;
  id: string;
  name: string;
  ownerUserId?: string;
  role: string;
}

export interface ProvisionUserRequest {
  email: string;
  name?: string;
  password: string;
  tokenExpiresInDays?: number;
  tokenLabel?: string;
  tokenScope?: ProvisionUserRequestTokenScope;
}

export type ProvisionUserRequestTokenScope = | "full" | "read_only";

export interface ProvisionedUser {
  email: string;
  token?: string;
  userId: string;
}

export interface QuotaResult {
  quota: QuotaResultQuota;
  userId: string;
}

export interface QuotaResultQuota {
  maxEntries: number | null;
  writesPerMinute: number | null;
}

export interface RecentRequest {
  contentMode?: RecentRequestContentMode;
  includeNamespaces?: Array<string>;
  includeProjects?: Array<string>;
  k?: number;
  maxSensitivity?: RecentRequestMaxSensitivity;
  namespace?: string;
  project?: string | null;
  since?: string | Date;
}

export type RecentRequestContentMode = | "full" | "snippet" | "ids";

export type RecentRequestMaxSensitivity = | "public" | "internal" | "private" | "sensitive";

export interface RememberResult {
  deduplicated?: boolean;
  embedded?: boolean;
  id: string | null;
  rejected?: string;
  superseded?: Array<string>;
  updated?: boolean;
}

export interface RevokeResult {
  revoked: boolean;
}

export interface SearchRequest {
  agentName?: string | null;
  asOf?: string | Date | null;
  contentMode?: SearchRequestContentMode;
  decompose?: boolean;
  expandSourceChunks?: boolean;
  includeNamespaces?: Array<string>;
  includeProjects?: Array<string>;
  k?: number;
  maxSensitivity?: SearchRequestMaxSensitivity;
  maxTokens?: number;
  minVectorScore?: number;
  namespace?: string;
  project?: string | null;
  query: string;
  rerank?: boolean;
  weights?: SearchRequestWeights;
}

export type SearchRequestContentMode = | "full" | "snippet" | "ids";

export type SearchRequestMaxSensitivity = | "public" | "internal" | "private" | "sensitive";

export interface SearchRequestWeights {
  entity?: number;
  graph?: number;
  keyword?: number;
  recency?: number;
  vector?: number;
}

export interface SearchResult {
  degraded?: boolean;
  results: Array<MemoryEntry>;
}

export interface SessionRecapRequest {
  agentName?: string | null;
  capturedFrom?: string;
  confidence?: number;
  decisions?: Array<string>;
  force?: boolean;
  metadata?: Record<string, unknown>;
  namespace?: string;
  other?: Array<string>;
  preferences?: Array<string>;
  project?: string | null;
  projectConventions?: Array<string>;
  rootCauses?: Array<string>;
  safetyConstraints?: Array<string>;
  sensitivity?: SessionRecapRequestSensitivity;
  setupFacts?: Array<string>;
  source?: string;
  sourceType?: string;
}

export type SessionRecapRequestSensitivity = | "public" | "internal" | "private" | "sensitive";

export interface SessionRecapResult {
  results: Array<CaptureResult>;
  saved: number;
}

export interface Stats {
  byNamespace: Record<string, StatsByNamespaceValue>;
  lastDecayAt?: string | null;
  totalCold: number;
  totalWarm: number;
  uptimeMs?: number;
}

export interface StatsByNamespaceValue {
  cold?: number;
  warm?: number;
}

export interface TokenDeleted {
  deleted: boolean;
}

export interface TokenList {
  tokens: Array<Record<string, unknown>>;
}

export interface UpdateRequest {
  capturedFrom?: string;
  confidence?: number;
  content?: string;
  metadata?: Record<string, unknown>;
  namespace?: string;
  project?: string | null;
  sensitivity?: UpdateRequestSensitivity;
  sourceType?: string;
}

export type UpdateRequestSensitivity = | "public" | "internal" | "private" | "sensitive";

export interface UpdateResult {
  embeddingChanged: boolean;
  id: string;
  updated: boolean;
}

export interface Usage {
  entries?: number;
  quota?: UsageQuota;
}

export interface UsageQuota {
  maxEntries?: number | null;
  writesPerMinute?: number | null;
}

export interface UserDeletion {
  coldCleanup: Array<string>;
  coldCleanupOk: boolean;
  deleted: boolean;
  entriesRemoved: number;
  projectsDeleted: Array<string>;
  tokensRemoved: number;
}

export interface UserDeletionPreview {
  dryRun: boolean;
  wouldDelete: UserDeletionPreviewWouldDelete;
}

export interface UserDeletionPreviewWouldDelete {
  email?: string;
  entries: number;
  ownedProjects: Array<string>;
  tokens: number;
  userId: string;
}
