<?php

// Code generated by clients/gen. DO NOT EDIT.
// @codingStandardsIgnoreFile
//
// Scenario dispatch: calls the routes.json method a scenario names, with the
// scenario's wire-form args. Required params are positional, optional ones
// named, a request object comes last.

declare(strict_types=1);

final class Dispatch
{
    /** @return array<string, callable(array<string, object>, array<string, mixed>): mixed> */
    public static function table(): array
    {
        return [
            'Admin.DeleteUser' => fn (array $c, array $a) => $c['Admin']->deleteUser($a['id'] ?? '', ),
            'Admin.ListUsers' => fn (array $c, array $a) => $c['Admin']->listUsers(),
            'Admin.PreviewDeleteUser' => fn (array $c, array $a) => $c['Admin']->previewDeleteUser($a['id'] ?? '', ),
            'Admin.ProvisionUser' => fn (array $c, array $a) => $c['Admin']->provisionUser(\Novamem\Types\ProvisionUserRequest::fromArray($a), ),
            'Admin.RevokeUserToken' => fn (array $c, array $a) => $c['Admin']->revokeUserToken($a['token'] ?? '', ),
            'Admin.SetUserQuota' => fn (array $c, array $a) => $c['Admin']->setUserQuota($a['id'] ?? '', maxEntries: $a['maxEntries'] ?? null, writesPerMinute: $a['writesPerMinute'] ?? null, ),
            'Client.Capture' => fn (array $c, array $a) => $c['Client']->capture(\Novamem\Types\CaptureRequest::fromArray($a), ),
            'Client.Context' => fn (array $c, array $a) => $c['Client']->context(\Novamem\Types\ContextRequest::fromArray($a), ),
            'Client.ContextPrefix' => fn (array $c, array $a) => $c['Client']->contextPrefix(project: $a['project'] ?? null, ),
            'Client.Forget' => fn (array $c, array $a) => $c['Client']->forget(\Novamem\Types\ForgetRequest::fromArray($a), ),
            'Client.Health' => fn (array $c, array $a) => $c['Client']->health(),
            'Client.Neighbors' => fn (array $c, array $a) => $c['Client']->neighbors(\Novamem\Types\NeighborsRequest::fromArray($a), ),
            'Client.Recent' => fn (array $c, array $a) => $c['Client']->recent(\Novamem\Types\RecentRequest::fromArray($a), ),
            'Client.Remember' => fn (array $c, array $a) => $c['Client']->remember(\Novamem\Types\CaptureRequest::fromArray($a), ),
            'Client.Search' => fn (array $c, array $a) => $c['Client']->search(\Novamem\Types\SearchRequest::fromArray($a), ),
            'Client.SessionRecap' => fn (array $c, array $a) => $c['Client']->sessionRecap(\Novamem\Types\SessionRecapRequest::fromArray($a), ),
            'Client.Stats' => fn (array $c, array $a) => $c['Client']->stats(),
            'Client.Today' => fn (array $c, array $a) => $c['Client']->today(\Novamem\Types\RecentRequest::fromArray($a), ),
            'Client.Update' => fn (array $c, array $a) => $c['Client']->update($a['id'] ?? '', \Novamem\Types\UpdateRequest::fromArray($a), ),
            'Management.ActiveProject' => fn (array $c, array $a) => $c['Management']->activeProject(),
            'Management.AddProjectMember' => fn (array $c, array $a) => $c['Management']->addProjectMember($a['id'] ?? '', $a['email'] ?? '', role: $a['role'] ?? null, ),
            'Management.Adoption' => fn (array $c, array $a) => $c['Management']->adoption(client: $a['client'] ?? null, ),
            'Management.Changes' => fn (array $c, array $a) => $c['Management']->changes(since: $a['since'] ?? null, afterSeq: $a['afterSeq'] ?? null, limit: $a['limit'] ?? null, ),
            'Management.ClearActiveProject' => fn (array $c, array $a) => $c['Management']->clearActiveProject(),
            'Management.CreateProject' => fn (array $c, array $a) => $c['Management']->createProject($a['name'] ?? '', ),
            'Management.Decay' => fn (array $c, array $a) => $c['Management']->decay(effectiveDays: $a['effectiveDays'] ?? null, ),
            'Management.DeleteProject' => fn (array $c, array $a) => $c['Management']->deleteProject($a['id'] ?? '', ),
            'Management.Evaluate' => fn (array $c, array $a) => $c['Management']->evaluate(suite: $a['suite'] ?? null, ),
            'Management.Export' => fn (array $c, array $a) => $c['Management']->export(afterId: $a['afterId'] ?? null, limit: $a['limit'] ?? null, ),
            'Management.Hygiene' => fn (array $c, array $a) => $c['Management']->hygiene(k: $a['k'] ?? null, ),
            'Management.Import' => fn (array $c, array $a) => $c['Management']->import($a['entries'] ?? [], ),
            'Management.ListProjectMembers' => fn (array $c, array $a) => $c['Management']->listProjectMembers($a['id'] ?? '', ),
            'Management.ListProjects' => fn (array $c, array $a) => $c['Management']->listProjects(),
            'Management.ListTokens' => fn (array $c, array $a) => $c['Management']->listTokens(),
            'Management.MintToken' => fn (array $c, array $a) => $c['Management']->mintToken(\Novamem\Types\MintTokenRequest::fromArray($a), ),
            'Management.Observe' => fn (array $c, array $a) => $c['Management']->observe(project: $a['project'] ?? null, limit: $a['limit'] ?? null, ),
            'Management.RemoveProjectMember' => fn (array $c, array $a) => $c['Management']->removeProjectMember($a['id'] ?? '', $a['userId'] ?? '', ),
            'Management.RemoveProjectMemberByUsername' => fn (array $c, array $a) => $c['Management']->removeProjectMemberByUsername($a['id'] ?? '', $a['username'] ?? '', ),
            'Management.RevokeToken' => fn (array $c, array $a) => $c['Management']->revokeToken($a['hash'] ?? '', ),
            'Management.SetActiveProject' => fn (array $c, array $a) => $c['Management']->setActiveProject($a['project'] ?? '', ),
            'Management.Usage' => fn (array $c, array $a) => $c['Management']->usage(),
        ];
    }
}
