# Code generated by clients/gen. DO NOT EDIT.
"""Wire types for the novamem API, generated from docs/api/openapi.json.

Every object type is a frozen dataclass with ``to_wire()`` (a JSON-ready
dict: unset and empty optional fields are left out, required ones are always
present, datetimes are sent as UTC with a ``Z``) and ``from_wire(d)`` (unknown keys are ignored, so
a newer server still decodes). Enum values the SDK does not know are kept as
plain strings rather than rejected.
"""

from __future__ import annotations

from dataclasses import dataclass, fields
from datetime import datetime, timezone
from enum import Enum
from typing import Any, ClassVar


def _dt_to_wire(v: datetime) -> str:
    if v.tzinfo is None:
        v = v.replace(tzinfo=timezone.utc)
    return v.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def _dt_from_wire(v: Any) -> Any:
    if isinstance(v, str):
        try:
            return datetime.fromisoformat(v.replace("Z", "+00:00"))
        except ValueError:
            return v
    return v


def _to_wire(value: Any, spec: tuple[str, Any]) -> Any:
    kind, arg = spec
    if value is None:
        return None
    if kind == "p":
        return _dt_to_wire(value) if arg == "datetime" and isinstance(value, datetime) else value
    if kind == "n":
        if isinstance(value, Enum):
            return value.value
        return value.to_wire() if hasattr(value, "to_wire") else value
    if kind == "a":
        return [_to_wire(v, arg) for v in value]
    return {k: _to_wire(v, arg) for k, v in value.items()}


def _from_wire(value: Any, spec: tuple[str, Any]) -> Any:
    kind, arg = spec
    if value is None:
        return None
    if kind == "p":
        return _dt_from_wire(value) if arg == "datetime" else value
    if kind == "n":
        cls = globals()[arg]
        if issubclass(cls, Enum):
            try:
                return cls(value)
            except ValueError:
                return value
        return cls.from_wire(value) if isinstance(value, dict) else value
    if kind == "a":
        return [_from_wire(v, arg) for v in value] if isinstance(value, list) else value
    return {k: _from_wire(v, arg) for k, v in value.items()} if isinstance(value, dict) else value


class _Wire:
    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = ()

    def to_wire(self) -> dict[str, Any]:
        out: dict[str, Any] = {}
        for name, wire, spec, required in self._FIELDS:
            v = getattr(self, name)
            # A required field is always sent, as null when it is None: the
            # key's presence is part of the contract. Optional ones are left
            # out when unset or empty.
            if not required and (v is None or v == ""):
                continue
            out[wire] = _to_wire(v, spec)
        return out

    @classmethod
    def from_wire(cls, d: dict[str, Any]) -> Any:
        return cls(**{name: _from_wire(d.get(wire), spec) for name, wire, spec, _ in cls._FIELDS})



class CaptureRequestSensitivity(str, Enum):
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"


class ChangeFeedChangesItemChange(str, Enum):
    CREATED = "created"
    UPDATED = "updated"
    SUPERSEDED = "superseded"
    DELETED = "deleted"
    EXPIRED = "expired"


class ContextRequestMaxSensitivity(str, Enum):
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"


class MemoryEntryTier(str, Enum):
    WARM = "warm"
    COLD = "cold"


class MintTokenRequestScope(str, Enum):
    FULL = "full"
    READ_ONLY = "read_only"


class NeighborsRequestMaxSensitivity(str, Enum):
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"


class ProvisionUserRequestTokenScope(str, Enum):
    FULL = "full"
    READ_ONLY = "read_only"


class RecentRequestContentMode(str, Enum):
    FULL = "full"
    SNIPPET = "snippet"
    IDS = "ids"


class RecentRequestMaxSensitivity(str, Enum):
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"


class SearchRequestContentMode(str, Enum):
    FULL = "full"
    SNIPPET = "snippet"
    IDS = "ids"


class SearchRequestMaxSensitivity(str, Enum):
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"


class SessionRecapRequestSensitivity(str, Enum):
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"


class UpdateRequestSensitivity(str, Enum):
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"


@dataclass(frozen=True)
class ActiveProject(_Wire):
    active: ActiveProjectActive | None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("active", "active", ("n", "ActiveProjectActive"), True),
    )


@dataclass(frozen=True)
class ActiveProjectActive(_Wire):
    id: str | None = None
    name: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("id", "id", ("p", "string"), False),
        ("name", "name", ("p", "string"), False),
    )


@dataclass(frozen=True)
class AdminUser(_Wire):
    created_at: str
    email: str
    entry_count: int
    id: str
    name: str | None
    role: str
    token_count: int

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("created_at", "createdAt", ("p", "string"), True),
        ("email", "email", ("p", "string"), True),
        ("entry_count", "entryCount", ("p", "int32"), True),
        ("id", "id", ("p", "string"), True),
        ("name", "name", ("p", "string"), True),
        ("role", "role", ("p", "string"), True),
        ("token_count", "tokenCount", ("p", "int32"), True),
    )


@dataclass(frozen=True)
class AdminUserList(_Wire):
    users: list[AdminUser]

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("users", "users", ("a", ("n", "AdminUser")), True),
    )


@dataclass(frozen=True)
class AdoptionReport(_Wire):
    diagnostics: list[dict[str, Any]]
    mcp: dict[str, Any]
    requested_client: str
    server: dict[str, Any]
    features: dict[str, Any] | None = None
    refresh: dict[str, Any] | None = None
    required_tools: list[str] | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("diagnostics", "diagnostics", ("a", ("m", ("p", "any"))), True),
        ("features", "features", ("m", ("p", "any")), False),
        ("mcp", "mcp", ("m", ("p", "any")), True),
        ("refresh", "refresh", ("m", ("p", "any")), False),
        ("requested_client", "requestedClient", ("p", "string"), True),
        ("required_tools", "requiredTools", ("a", ("p", "string")), False),
        ("server", "server", ("m", ("p", "any")), True),
    )


@dataclass(frozen=True)
class CaptureRequest(_Wire):
    content: str
    agent_name: str | None = None
    captured_from: str | None = None
    confidence: float | None = None
    expires_at: datetime | None = None
    force: bool | None = None
    metadata: dict[str, Any] | None = None
    namespace: str | None = None
    project: str | None = None
    sensitivity: CaptureRequestSensitivity | None = None
    source: str | None = None
    source_type: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("agent_name", "agentName", ("p", "string"), False),
        ("captured_from", "capturedFrom", ("p", "string"), False),
        ("confidence", "confidence", ("p", "float"), False),
        ("content", "content", ("p", "string"), True),
        ("expires_at", "expiresAt", ("p", "datetime"), False),
        ("force", "force", ("p", "bool"), False),
        ("metadata", "metadata", ("m", ("p", "any")), False),
        ("namespace", "namespace", ("p", "string"), False),
        ("project", "project", ("p", "string"), False),
        ("sensitivity", "sensitivity", ("n", "CaptureRequestSensitivity"), False),
        ("source", "source", ("p", "string"), False),
        ("source_type", "sourceType", ("p", "string"), False),
    )


@dataclass(frozen=True)
class CaptureResult(_Wire):
    id: str | None
    deduplicated: bool | None = None
    embedded: bool | None = None
    rejected: str | None = None
    superseded: list[str] | None = None
    updated: bool | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("deduplicated", "deduplicated", ("p", "bool"), False),
        ("embedded", "embedded", ("p", "bool"), False),
        ("id", "id", ("p", "string"), True),
        ("rejected", "rejected", ("p", "string"), False),
        ("superseded", "superseded", ("a", ("p", "string")), False),
        ("updated", "updated", ("p", "bool"), False),
    )


@dataclass(frozen=True)
class ChangeFeed(_Wire):
    changes: list[ChangeFeedChangesItem]
    next_seq: int | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("changes", "changes", ("a", ("n", "ChangeFeedChangesItem")), True),
        ("next_seq", "nextSeq", ("p", "int64"), False),
    )


@dataclass(frozen=True)
class ChangeFeedChangesItem(_Wire):
    at: str | None = None
    change: ChangeFeedChangesItemChange | None = None
    detail: dict[str, Any] | None = None
    entry_id: str | None = None
    project_id: str | None = None
    seq: int | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("at", "at", ("p", "string"), False),
        ("change", "change", ("n", "ChangeFeedChangesItemChange"), False),
        ("detail", "detail", ("m", ("p", "any")), False),
        ("entry_id", "entryId", ("p", "string"), False),
        ("project_id", "projectId", ("p", "string"), False),
        ("seq", "seq", ("p", "int64"), False),
    )


@dataclass(frozen=True)
class ContextPrefix(_Wire):
    prefix: str

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("prefix", "prefix", ("p", "string"), True),
    )


@dataclass(frozen=True)
class ContextRequest(_Wire):
    message: str
    as_of: datetime | None = None
    decompose: bool | None = None
    expand_source_chunks: bool | None = None
    include_namespaces: list[str] | None = None
    include_projects: list[str] | None = None
    k: int | None = None
    max_sensitivity: ContextRequestMaxSensitivity | None = None
    max_tokens: int | None = None
    namespace: str | None = None
    project: str | None = None
    weights: ContextRequestWeights | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("as_of", "asOf", ("p", "datetime"), False),
        ("decompose", "decompose", ("p", "bool"), False),
        ("expand_source_chunks", "expandSourceChunks", ("p", "bool"), False),
        ("include_namespaces", "includeNamespaces", ("a", ("p", "string")), False),
        ("include_projects", "includeProjects", ("a", ("p", "string")), False),
        ("k", "k", ("p", "int32"), False),
        ("max_sensitivity", "maxSensitivity", ("n", "ContextRequestMaxSensitivity"), False),
        ("max_tokens", "maxTokens", ("p", "int32"), False),
        ("message", "message", ("p", "string"), True),
        ("namespace", "namespace", ("p", "string"), False),
        ("project", "project", ("p", "string"), False),
        ("weights", "weights", ("n", "ContextRequestWeights"), False),
    )


@dataclass(frozen=True)
class ContextRequestWeights(_Wire):
    entity: float | None = None
    graph: float | None = None
    keyword: float | None = None
    recency: float | None = None
    vector: float | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("entity", "entity", ("p", "float"), False),
        ("graph", "graph", ("p", "float"), False),
        ("keyword", "keyword", ("p", "float"), False),
        ("recency", "recency", ("p", "float"), False),
        ("vector", "vector", ("p", "float"), False),
    )


@dataclass(frozen=True)
class DecayResult(_Wire):
    demoted: float
    expired: float
    promoted: float

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("demoted", "demoted", ("p", "float"), True),
        ("expired", "expired", ("p", "float"), True),
        ("promoted", "promoted", ("p", "float"), True),
    )


@dataclass(frozen=True)
class EntryList(_Wire):
    results: list[MemoryEntry]

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("results", "results", ("a", ("n", "MemoryEntry")), True),
    )


@dataclass(frozen=True)
class EvaluateReport(_Wire):
    cases: list[EvaluateReportCasesItem]
    passed: bool
    suite: str
    summary: EvaluateReportSummary

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("cases", "cases", ("a", ("n", "EvaluateReportCasesItem")), True),
        ("passed", "passed", ("p", "bool"), True),
        ("suite", "suite", ("p", "string"), True),
        ("summary", "summary", ("n", "EvaluateReportSummary"), True),
    )


@dataclass(frozen=True)
class EvaluateReportCasesItem(_Wire):
    name: str | None = None
    passed: bool | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("name", "name", ("p", "string"), False),
        ("passed", "passed", ("p", "bool"), False),
    )


@dataclass(frozen=True)
class EvaluateReportSummary(_Wire):
    failed: float | None = None
    passed: float | None = None
    total: float | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("failed", "failed", ("p", "float"), False),
        ("passed", "passed", ("p", "float"), False),
        ("total", "total", ("p", "float"), False),
    )


@dataclass(frozen=True)
class ExportPage(_Wire):
    entries: list[ExportedEntry]
    next_after_id: str | None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("entries", "entries", ("a", ("n", "ExportedEntry")), True),
        ("next_after_id", "nextAfterId", ("p", "string"), True),
    )


@dataclass(frozen=True)
class ExportedEntry(_Wire):
    agent_name: str | None
    captured_from: str | None
    confidence: float
    content: str
    created_at: str
    id: str
    metadata: dict[str, Any]
    namespace: str
    project_id: str | None
    source: str
    source_type: str | None
    updated_at: str

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("agent_name", "agentName", ("p", "string"), True),
        ("captured_from", "capturedFrom", ("p", "string"), True),
        ("confidence", "confidence", ("p", "float"), True),
        ("content", "content", ("p", "string"), True),
        ("created_at", "createdAt", ("p", "string"), True),
        ("id", "id", ("p", "string"), True),
        ("metadata", "metadata", ("m", ("p", "any")), True),
        ("namespace", "namespace", ("p", "string"), True),
        ("project_id", "projectId", ("p", "string"), True),
        ("source", "source", ("p", "string"), True),
        ("source_type", "sourceType", ("p", "string"), True),
        ("updated_at", "updatedAt", ("p", "string"), True),
    )


@dataclass(frozen=True)
class ForgetRequest(_Wire):
    id: str
    project: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("id", "id", ("p", "string"), True),
        ("project", "project", ("p", "string"), False),
    )


@dataclass(frozen=True)
class ForgetResult(_Wire):
    deleted: bool
    cold_delete_ok: bool | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("cold_delete_ok", "coldDeleteOk", ("p", "bool"), False),
        ("deleted", "deleted", ("p", "bool"), True),
    )


@dataclass(frozen=True)
class Health(_Wire):
    ok: bool

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("ok", "ok", ("p", "bool"), True),
    )


@dataclass(frozen=True)
class HygieneReport(_Wire):
    summary: HygieneReportSummary
    contradiction_candidates: list[Any] | None = None
    duplicate_clusters: list[Any] | None = None
    low_value: list[Any] | None = None
    orphan_candidates: list[Any] | None = None
    stale: list[Any] | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("contradiction_candidates", "contradictionCandidates", ("a", ("p", "any")), False),
        ("duplicate_clusters", "duplicateClusters", ("a", ("p", "any")), False),
        ("low_value", "lowValue", ("a", ("p", "any")), False),
        ("orphan_candidates", "orphanCandidates", ("a", ("p", "any")), False),
        ("stale", "stale", ("a", ("p", "any")), False),
        ("summary", "summary", ("n", "HygieneReportSummary"), True),
    )


@dataclass(frozen=True)
class HygieneReportSummary(_Wire):
    contradiction_candidates: float | None = None
    duplicate_clusters: float | None = None
    low_value: float | None = None
    orphan_candidates: float | None = None
    scanned: float | None = None
    stale: float | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("contradiction_candidates", "contradictionCandidates", ("p", "float"), False),
        ("duplicate_clusters", "duplicateClusters", ("p", "float"), False),
        ("low_value", "lowValue", ("p", "float"), False),
        ("orphan_candidates", "orphanCandidates", ("p", "float"), False),
        ("scanned", "scanned", ("p", "float"), False),
        ("stale", "stale", ("p", "float"), False),
    )


@dataclass(frozen=True)
class ImportResult(_Wire):
    deduplicated: int
    failed: list[ImportResultFailedItem]
    imported: int

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("deduplicated", "deduplicated", ("p", "int32"), True),
        ("failed", "failed", ("a", ("n", "ImportResultFailedItem")), True),
        ("imported", "imported", ("p", "int32"), True),
    )


@dataclass(frozen=True)
class ImportResultFailedItem(_Wire):
    error: str
    index: int

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("error", "error", ("p", "string"), True),
        ("index", "index", ("p", "int32"), True),
    )


@dataclass(frozen=True)
class MemberAdded(_Wire):
    added: bool
    user_id: str
    username: str

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("added", "added", ("p", "bool"), True),
        ("user_id", "userId", ("p", "string"), True),
        ("username", "username", ("p", "string"), True),
    )


@dataclass(frozen=True)
class MemberList(_Wire):
    members: list[MemberListMembersItem]

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("members", "members", ("a", ("n", "MemberListMembersItem")), True),
    )


@dataclass(frozen=True)
class MemberListMembersItem(_Wire):
    joined_at: str | None = None
    role: str | None = None
    user_id: str | None = None
    username: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("joined_at", "joinedAt", ("p", "string"), False),
        ("role", "role", ("p", "string"), False),
        ("user_id", "userId", ("p", "string"), False),
        ("username", "username", ("p", "string"), False),
    )


@dataclass(frozen=True)
class MemberRemoved(_Wire):
    removed: bool

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("removed", "removed", ("p", "bool"), True),
    )


@dataclass(frozen=True)
class MemoryEntry(_Wire):
    content: str
    id: str
    metadata: dict[str, Any] | None = None
    namespace: str | None = None
    project: str | None = None
    score: float | None = None
    signals: MemoryEntrySignals | None = None
    source: str | None = None
    tier: MemoryEntryTier | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("content", "content", ("p", "string"), True),
        ("id", "id", ("p", "string"), True),
        ("metadata", "metadata", ("m", ("p", "any")), False),
        ("namespace", "namespace", ("p", "string"), False),
        ("project", "project", ("p", "string"), False),
        ("score", "score", ("p", "float"), False),
        ("signals", "signals", ("n", "MemoryEntrySignals"), False),
        ("source", "source", ("p", "string"), False),
        ("tier", "tier", ("n", "MemoryEntryTier"), False),
    )


@dataclass(frozen=True)
class MemoryEntrySignals(_Wire):
    entity: float | None = None
    graph: float | None = None
    keyword: float | None = None
    recency: float | None = None
    vector: float | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("entity", "entity", ("p", "float"), False),
        ("graph", "graph", ("p", "float"), False),
        ("keyword", "keyword", ("p", "float"), False),
        ("recency", "recency", ("p", "float"), False),
        ("vector", "vector", ("p", "float"), False),
    )


@dataclass(frozen=True)
class MintTokenRequest(_Wire):
    expires_in_days: int | None = None
    label: str | None = None
    project: str | None = None
    scope: MintTokenRequestScope | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("expires_in_days", "expiresInDays", ("p", "int32"), False),
        ("label", "label", ("p", "string"), False),
        ("project", "project", ("p", "string"), False),
        ("scope", "scope", ("n", "MintTokenRequestScope"), False),
    )


@dataclass(frozen=True)
class MintedToken(_Wire):
    token: str
    created_at: str | None = None
    expires_at: str | None = None
    project_id: str | None = None
    scope: str | None = None
    user_id: str | None = None
    warning: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("created_at", "createdAt", ("p", "string"), False),
        ("expires_at", "expiresAt", ("p", "string"), False),
        ("project_id", "projectId", ("p", "string"), False),
        ("scope", "scope", ("p", "string"), False),
        ("token", "token", ("p", "string"), True),
        ("user_id", "userId", ("p", "string"), False),
        ("warning", "warning", ("p", "string"), False),
    )


@dataclass(frozen=True)
class NeighborsRequest(_Wire):
    id: str
    depth: int | None = None
    include_namespaces: list[str] | None = None
    include_projects: list[str] | None = None
    k: int | None = None
    max_sensitivity: NeighborsRequestMaxSensitivity | None = None
    project: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("depth", "depth", ("p", "int32"), False),
        ("id", "id", ("p", "string"), True),
        ("include_namespaces", "includeNamespaces", ("a", ("p", "string")), False),
        ("include_projects", "includeProjects", ("a", ("p", "string")), False),
        ("k", "k", ("p", "int32"), False),
        ("max_sensitivity", "maxSensitivity", ("n", "NeighborsRequestMaxSensitivity"), False),
        ("project", "project", ("p", "string"), False),
    )


@dataclass(frozen=True)
class ObserveResult(_Wire):
    log_chars: float | None = None
    observed: float | None = None
    reflected: bool | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("log_chars", "logChars", ("p", "float"), False),
        ("observed", "observed", ("p", "float"), False),
        ("reflected", "reflected", ("p", "bool"), False),
    )


@dataclass(frozen=True)
class Project(_Wire):
    id: str
    name: str
    created_at: str | None = None
    owner_user_id: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("created_at", "createdAt", ("p", "string"), False),
        ("id", "id", ("p", "string"), True),
        ("name", "name", ("p", "string"), True),
        ("owner_user_id", "ownerUserId", ("p", "string"), False),
    )


@dataclass(frozen=True)
class ProjectDeleted(_Wire):
    deleted: bool
    cold_collections_dropped: list[str] | None = None
    entries_removed: float | None = None
    graph_cleared: bool | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("cold_collections_dropped", "coldCollectionsDropped", ("a", ("p", "string")), False),
        ("deleted", "deleted", ("p", "bool"), True),
        ("entries_removed", "entriesRemoved", ("p", "float"), False),
        ("graph_cleared", "graphCleared", ("p", "bool"), False),
    )


@dataclass(frozen=True)
class ProjectList(_Wire):
    projects: list[ProjectListItem]

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("projects", "projects", ("a", ("n", "ProjectListItem")), True),
    )


@dataclass(frozen=True)
class ProjectListItem(_Wire):
    id: str
    name: str
    role: str
    created_at: str | None = None
    owner_user_id: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("created_at", "createdAt", ("p", "string"), False),
        ("id", "id", ("p", "string"), True),
        ("name", "name", ("p", "string"), True),
        ("owner_user_id", "ownerUserId", ("p", "string"), False),
        ("role", "role", ("p", "string"), True),
    )


@dataclass(frozen=True)
class ProvisionUserRequest(_Wire):
    email: str
    password: str
    name: str | None = None
    token_expires_in_days: int | None = None
    token_label: str | None = None
    token_scope: ProvisionUserRequestTokenScope | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("email", "email", ("p", "string"), True),
        ("name", "name", ("p", "string"), False),
        ("password", "password", ("p", "string"), True),
        ("token_expires_in_days", "tokenExpiresInDays", ("p", "int32"), False),
        ("token_label", "tokenLabel", ("p", "string"), False),
        ("token_scope", "tokenScope", ("n", "ProvisionUserRequestTokenScope"), False),
    )


@dataclass(frozen=True)
class ProvisionedUser(_Wire):
    email: str
    user_id: str
    token: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("email", "email", ("p", "string"), True),
        ("token", "token", ("p", "string"), False),
        ("user_id", "userId", ("p", "string"), True),
    )


@dataclass(frozen=True)
class QuotaResult(_Wire):
    quota: QuotaResultQuota
    user_id: str

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("quota", "quota", ("n", "QuotaResultQuota"), True),
        ("user_id", "userId", ("p", "string"), True),
    )


@dataclass(frozen=True)
class QuotaResultQuota(_Wire):
    max_entries: int | None
    writes_per_minute: int | None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("max_entries", "maxEntries", ("p", "int32"), True),
        ("writes_per_minute", "writesPerMinute", ("p", "int32"), True),
    )


@dataclass(frozen=True)
class RecentRequest(_Wire):
    content_mode: RecentRequestContentMode | None = None
    include_namespaces: list[str] | None = None
    include_projects: list[str] | None = None
    k: int | None = None
    max_sensitivity: RecentRequestMaxSensitivity | None = None
    namespace: str | None = None
    project: str | None = None
    since: datetime | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("content_mode", "contentMode", ("n", "RecentRequestContentMode"), False),
        ("include_namespaces", "includeNamespaces", ("a", ("p", "string")), False),
        ("include_projects", "includeProjects", ("a", ("p", "string")), False),
        ("k", "k", ("p", "int32"), False),
        ("max_sensitivity", "maxSensitivity", ("n", "RecentRequestMaxSensitivity"), False),
        ("namespace", "namespace", ("p", "string"), False),
        ("project", "project", ("p", "string"), False),
        ("since", "since", ("p", "datetime"), False),
    )


@dataclass(frozen=True)
class RememberResult(_Wire):
    id: str | None
    deduplicated: bool | None = None
    embedded: bool | None = None
    rejected: str | None = None
    superseded: list[str] | None = None
    updated: bool | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("deduplicated", "deduplicated", ("p", "bool"), False),
        ("embedded", "embedded", ("p", "bool"), False),
        ("id", "id", ("p", "string"), True),
        ("rejected", "rejected", ("p", "string"), False),
        ("superseded", "superseded", ("a", ("p", "string")), False),
        ("updated", "updated", ("p", "bool"), False),
    )


@dataclass(frozen=True)
class RevokeResult(_Wire):
    revoked: bool

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("revoked", "revoked", ("p", "bool"), True),
    )


@dataclass(frozen=True)
class SearchRequest(_Wire):
    query: str
    agent_name: str | None = None
    as_of: datetime | None = None
    content_mode: SearchRequestContentMode | None = None
    decompose: bool | None = None
    expand_source_chunks: bool | None = None
    include_namespaces: list[str] | None = None
    include_projects: list[str] | None = None
    k: int | None = None
    max_sensitivity: SearchRequestMaxSensitivity | None = None
    max_tokens: int | None = None
    min_vector_score: float | None = None
    namespace: str | None = None
    project: str | None = None
    rerank: bool | None = None
    weights: SearchRequestWeights | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("agent_name", "agentName", ("p", "string"), False),
        ("as_of", "asOf", ("p", "datetime"), False),
        ("content_mode", "contentMode", ("n", "SearchRequestContentMode"), False),
        ("decompose", "decompose", ("p", "bool"), False),
        ("expand_source_chunks", "expandSourceChunks", ("p", "bool"), False),
        ("include_namespaces", "includeNamespaces", ("a", ("p", "string")), False),
        ("include_projects", "includeProjects", ("a", ("p", "string")), False),
        ("k", "k", ("p", "int32"), False),
        ("max_sensitivity", "maxSensitivity", ("n", "SearchRequestMaxSensitivity"), False),
        ("max_tokens", "maxTokens", ("p", "int32"), False),
        ("min_vector_score", "minVectorScore", ("p", "float"), False),
        ("namespace", "namespace", ("p", "string"), False),
        ("project", "project", ("p", "string"), False),
        ("query", "query", ("p", "string"), True),
        ("rerank", "rerank", ("p", "bool"), False),
        ("weights", "weights", ("n", "SearchRequestWeights"), False),
    )


@dataclass(frozen=True)
class SearchRequestWeights(_Wire):
    entity: float | None = None
    graph: float | None = None
    keyword: float | None = None
    recency: float | None = None
    vector: float | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("entity", "entity", ("p", "float"), False),
        ("graph", "graph", ("p", "float"), False),
        ("keyword", "keyword", ("p", "float"), False),
        ("recency", "recency", ("p", "float"), False),
        ("vector", "vector", ("p", "float"), False),
    )


@dataclass(frozen=True)
class SearchResult(_Wire):
    results: list[MemoryEntry]
    degraded: bool | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("degraded", "degraded", ("p", "bool"), False),
        ("results", "results", ("a", ("n", "MemoryEntry")), True),
    )


@dataclass(frozen=True)
class SessionRecapRequest(_Wire):
    agent_name: str | None = None
    captured_from: str | None = None
    confidence: float | None = None
    decisions: list[str] | None = None
    force: bool | None = None
    metadata: dict[str, Any] | None = None
    namespace: str | None = None
    other: list[str] | None = None
    preferences: list[str] | None = None
    project: str | None = None
    project_conventions: list[str] | None = None
    root_causes: list[str] | None = None
    safety_constraints: list[str] | None = None
    sensitivity: SessionRecapRequestSensitivity | None = None
    setup_facts: list[str] | None = None
    source: str | None = None
    source_type: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("agent_name", "agentName", ("p", "string"), False),
        ("captured_from", "capturedFrom", ("p", "string"), False),
        ("confidence", "confidence", ("p", "float"), False),
        ("decisions", "decisions", ("a", ("p", "string")), False),
        ("force", "force", ("p", "bool"), False),
        ("metadata", "metadata", ("m", ("p", "any")), False),
        ("namespace", "namespace", ("p", "string"), False),
        ("other", "other", ("a", ("p", "string")), False),
        ("preferences", "preferences", ("a", ("p", "string")), False),
        ("project", "project", ("p", "string"), False),
        ("project_conventions", "projectConventions", ("a", ("p", "string")), False),
        ("root_causes", "rootCauses", ("a", ("p", "string")), False),
        ("safety_constraints", "safetyConstraints", ("a", ("p", "string")), False),
        ("sensitivity", "sensitivity", ("n", "SessionRecapRequestSensitivity"), False),
        ("setup_facts", "setupFacts", ("a", ("p", "string")), False),
        ("source", "source", ("p", "string"), False),
        ("source_type", "sourceType", ("p", "string"), False),
    )


@dataclass(frozen=True)
class SessionRecapResult(_Wire):
    results: list[CaptureResult]
    saved: float

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("results", "results", ("a", ("n", "CaptureResult")), True),
        ("saved", "saved", ("p", "float"), True),
    )


@dataclass(frozen=True)
class Stats(_Wire):
    by_namespace: dict[str, StatsByNamespaceValue]
    total_cold: float
    total_warm: float
    last_decay_at: str | None = None
    uptime_ms: float | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("by_namespace", "byNamespace", ("m", ("n", "StatsByNamespaceValue")), True),
        ("last_decay_at", "lastDecayAt", ("p", "string"), False),
        ("total_cold", "totalCold", ("p", "float"), True),
        ("total_warm", "totalWarm", ("p", "float"), True),
        ("uptime_ms", "uptimeMs", ("p", "float"), False),
    )


@dataclass(frozen=True)
class StatsByNamespaceValue(_Wire):
    cold: float | None = None
    warm: float | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("cold", "cold", ("p", "float"), False),
        ("warm", "warm", ("p", "float"), False),
    )


@dataclass(frozen=True)
class TokenDeleted(_Wire):
    deleted: bool

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("deleted", "deleted", ("p", "bool"), True),
    )


@dataclass(frozen=True)
class TokenList(_Wire):
    tokens: list[dict[str, Any]]

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("tokens", "tokens", ("a", ("m", ("p", "any"))), True),
    )


@dataclass(frozen=True)
class UpdateRequest(_Wire):
    captured_from: str | None = None
    confidence: float | None = None
    content: str | None = None
    metadata: dict[str, Any] | None = None
    namespace: str | None = None
    project: str | None = None
    sensitivity: UpdateRequestSensitivity | None = None
    source_type: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("captured_from", "capturedFrom", ("p", "string"), False),
        ("confidence", "confidence", ("p", "float"), False),
        ("content", "content", ("p", "string"), False),
        ("metadata", "metadata", ("m", ("p", "any")), False),
        ("namespace", "namespace", ("p", "string"), False),
        ("project", "project", ("p", "string"), False),
        ("sensitivity", "sensitivity", ("n", "UpdateRequestSensitivity"), False),
        ("source_type", "sourceType", ("p", "string"), False),
    )


@dataclass(frozen=True)
class UpdateResult(_Wire):
    embedding_changed: bool
    id: str
    updated: bool

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("embedding_changed", "embeddingChanged", ("p", "bool"), True),
        ("id", "id", ("p", "string"), True),
        ("updated", "updated", ("p", "bool"), True),
    )


@dataclass(frozen=True)
class Usage(_Wire):
    entries: float | None = None
    quota: UsageQuota | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("entries", "entries", ("p", "float"), False),
        ("quota", "quota", ("n", "UsageQuota"), False),
    )


@dataclass(frozen=True)
class UsageQuota(_Wire):
    max_entries: float | None = None
    writes_per_minute: float | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("max_entries", "maxEntries", ("p", "float"), False),
        ("writes_per_minute", "writesPerMinute", ("p", "float"), False),
    )


@dataclass(frozen=True)
class UserDeletion(_Wire):
    cold_cleanup: list[str]
    cold_cleanup_ok: bool
    deleted: bool
    entries_removed: int
    projects_deleted: list[str]
    tokens_removed: int

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("cold_cleanup", "coldCleanup", ("a", ("p", "string")), True),
        ("cold_cleanup_ok", "coldCleanupOk", ("p", "bool"), True),
        ("deleted", "deleted", ("p", "bool"), True),
        ("entries_removed", "entriesRemoved", ("p", "int32"), True),
        ("projects_deleted", "projectsDeleted", ("a", ("p", "string")), True),
        ("tokens_removed", "tokensRemoved", ("p", "int32"), True),
    )


@dataclass(frozen=True)
class UserDeletionPreview(_Wire):
    dry_run: bool
    would_delete: UserDeletionPreviewWouldDelete

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("dry_run", "dryRun", ("p", "bool"), True),
        ("would_delete", "wouldDelete", ("n", "UserDeletionPreviewWouldDelete"), True),
    )


@dataclass(frozen=True)
class UserDeletionPreviewWouldDelete(_Wire):
    entries: int
    owned_projects: list[str]
    tokens: int
    user_id: str
    email: str | None = None

    _FIELDS: ClassVar[tuple[tuple[str, str, tuple[str, Any], bool], ...]] = (
        ("email", "email", ("p", "string"), False),
        ("entries", "entries", ("p", "int32"), True),
        ("owned_projects", "ownedProjects", ("a", ("p", "string")), True),
        ("tokens", "tokens", ("p", "int32"), True),
        ("user_id", "userId", ("p", "string"), True),
    )


__all__ = [
    "ActiveProject",
    "ActiveProjectActive",
    "AdminUser",
    "AdminUserList",
    "AdoptionReport",
    "CaptureRequest",
    "CaptureRequestSensitivity",
    "CaptureResult",
    "ChangeFeed",
    "ChangeFeedChangesItem",
    "ChangeFeedChangesItemChange",
    "ContextPrefix",
    "ContextRequest",
    "ContextRequestMaxSensitivity",
    "ContextRequestWeights",
    "DecayResult",
    "EntryList",
    "EvaluateReport",
    "EvaluateReportCasesItem",
    "EvaluateReportSummary",
    "ExportPage",
    "ExportedEntry",
    "ForgetRequest",
    "ForgetResult",
    "Health",
    "HygieneReport",
    "HygieneReportSummary",
    "ImportResult",
    "ImportResultFailedItem",
    "MemberAdded",
    "MemberList",
    "MemberListMembersItem",
    "MemberRemoved",
    "MemoryEntry",
    "MemoryEntrySignals",
    "MemoryEntryTier",
    "MintTokenRequest",
    "MintTokenRequestScope",
    "MintedToken",
    "NeighborsRequest",
    "NeighborsRequestMaxSensitivity",
    "ObserveResult",
    "Project",
    "ProjectDeleted",
    "ProjectList",
    "ProjectListItem",
    "ProvisionUserRequest",
    "ProvisionUserRequestTokenScope",
    "ProvisionedUser",
    "QuotaResult",
    "QuotaResultQuota",
    "RecentRequest",
    "RecentRequestContentMode",
    "RecentRequestMaxSensitivity",
    "RememberResult",
    "RevokeResult",
    "SearchRequest",
    "SearchRequestContentMode",
    "SearchRequestMaxSensitivity",
    "SearchRequestWeights",
    "SearchResult",
    "SessionRecapRequest",
    "SessionRecapRequestSensitivity",
    "SessionRecapResult",
    "Stats",
    "StatsByNamespaceValue",
    "TokenDeleted",
    "TokenList",
    "UpdateRequest",
    "UpdateRequestSensitivity",
    "UpdateResult",
    "Usage",
    "UsageQuota",
    "UserDeletion",
    "UserDeletionPreview",
    "UserDeletionPreviewWouldDelete",
]
