// Code generated by cmd/gen-contract from api/openapi.yaml. DO NOT EDIT.

package httpapi

var baAllowlist = map[string]bool{
	"/api/auth/admin/ban-user": true,
	"/api/auth/admin/create-user": true,
	"/api/auth/admin/impersonate-user": true,
	"/api/auth/admin/list-user-sessions": true,
	"/api/auth/admin/list-users": true,
	"/api/auth/admin/remove-user": true,
	"/api/auth/admin/revoke-user-session": true,
	"/api/auth/admin/revoke-user-sessions": true,
	"/api/auth/admin/set-role": true,
	"/api/auth/admin/set-user-password": true,
	"/api/auth/admin/stop-impersonating": true,
	"/api/auth/admin/unban-user": true,
	"/api/auth/admin/update-user": true,
	"/api/auth/change-password": true,
	"/api/auth/forget-password": true,
	"/api/auth/get-session": true,
	"/api/auth/jwks": true,
	"/api/auth/list-sessions": true,
	"/api/auth/reset-password": true,
	"/api/auth/revoke-session": true,
	"/api/auth/send-verification-email": true,
	"/api/auth/sign-in/email": true,
	"/api/auth/sign-out": true,
	"/api/auth/token": true,
	"/api/auth/verify-email": true,
}
