// Code generated from the TS server's last published contract, then
// owned here. The Go server is now the generator: `go run
// ./cmd/gen-openapi` renders docs/api/openapi.json from this table, and
// openapi_test.go fails if this table and the routes the mux actually
// serves disagree in either direction.
//
// Request/response schema fragments are raw JSON so a hand edit stays a
// one-line change and the rendered document keeps byte-for-byte
// stability.

package httpapi

// Document-level metadata (everything but `paths`).
const (
	openapiVersion = "3.0.3"
	openapiInfo    = "{\"title\":\"novamem\",\"version\":\"1.1.7\",\"description\":\"Tiered memory service with hybrid search (keyword + vector + graph), per-user isolation, and project-scoped sub-brains.\\n\\n**Auth**: every authenticated route accepts either an `nm_…` user bearer (created from the dashboard's API Tokens page) or a Better Auth session cookie/bearer (set by `POST /api/auth/sign-in/email`). Both flow through the same auth hook and resolve to the same user. Better Auth's own routes are mounted at `/api/auth/*` — see the Better Auth documentation for their shapes.\",\"license\":{\"name\":\"Apache-2.0\",\"url\":\"https://www.apache.org/licenses/LICENSE-2.0\"}}"

	openapiComponents = `{"securitySchemes":{"UserBearer":{"type":"http","scheme":"bearer","bearerFormat":"nm_…","description":"Per-device API token belonging to one user. Carries every right the owning user has — data plane, project CRUD, membership, metrics. Created from the dashboard's API Tokens page; the plaintext is shown once."},"SessionCookie":{"type":"apiKey","in":"cookie","name":"nm.session_token","description":"Better Auth session cookie set by /api/auth/sign-in/email. HttpOnly + SameSite=Lax. Browsers attach it automatically."}},"schemas":{}}`

	openapiServers = `[{"url":"/","description":"this server"}]`

	openapiTags = "[{\"name\":\"memory\",\"description\":\"Read/write the memory data plane\"},{\"name\":\"lifecycle\",\"description\":\"Decay, dream cycle, orphan reaper, stats\"},{\"name\":\"auth\",\"description\":\"Rotate `nm_…` bearers (Better Auth's own surface lives at /api/auth/*)\"},{\"name\":\"self-service\",\"description\":\"Per-caller settings (active project)\"},{\"name\":\"projects\",\"description\":\"Project CRUD + membership\"},{\"name\":\"tokens\",\"description\":\"Per-device `nm_…` bearer management\"},{\"name\":\"metrics\",\"description\":\"Per-user metrics + 24h history\"},{\"name\":\"admin\",\"description\":\"Admin-only endpoints (role=admin)\"},{\"name\":\"mcp\",\"description\":\"Model Context Protocol transports (Streamable HTTP + legacy SSE)\"},{\"name\":\"liveness\",\"description\":\"Health checks\"}]"
)

var apiRoutes = []apiRoute{
	{
		Method:   "POST",
		Path:     "/v1/auth/rotate-token",
		Summary:  "Self-rotate the caller's `nm_…` bearer (user mode only)",
		Tags:     []string{"auth"},
		Security: []string{"UserBearer"},
	},
	{
		Method:   "POST",
		Path:     "/v1/adoption",
		Summary:  "Client adoption and refresh diagnostics for MCP/tooling integrations",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"client":{"type":"string","maxLength":64},"observedTools":{"maxItems":128,"type":"array","items":{"type":"string","minLength":1,"maxLength":128}},"observedInstructionsHash":{"type":"string","pattern":"^[a-fA-F0-9]{64}$"}},"additionalProperties":false}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/hygiene",
		Summary:  "Read-only memory hygiene report",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"k":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":100}},"additionalProperties":false}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/evaluate",
		Summary:  "Run built-in memory quality evaluation scenarios",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"suite":{"type":"string","minLength":1,"maxLength":64}},"additionalProperties":false}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/search",
		Summary:  "Hybrid search (keyword + vector + graph) over the caller's memories",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"query":{"type":"string","minLength":1,"maxLength":8192},"k":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":200},"namespace":{"type":"string","maxLength":128},"agentName":{"nullable":true,"type":"string","maxLength":128},"project":{"nullable":true,"type":"string","minLength":1,"maxLength":128},"includeProjects":{"maxItems":16,"type":"array","items":{"type":"string","minLength":1,"maxLength":128}},"includeNamespaces":{"maxItems":16,"type":"array","items":{"type":"string","minLength":1,"maxLength":128,"pattern":"^[a-z0-9][a-z0-9._:-]*$"}},"weights":{"type":"object","properties":{"keyword":{"type":"number"},"vector":{"type":"number"},"graph":{"type":"number"},"recency":{"type":"number"},"entity":{"type":"number"}}},"contentMode":{"type":"string","enum":["full","snippet","ids"]},"maxSensitivity":{"type":"string","enum":["public","internal","private","sensitive"]},"asOf":{"nullable":true,"type":"string","format":"date-time","pattern":"^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"},"decompose":{"type":"boolean"},"expandSourceChunks":{"type":"boolean"},"rerank":{"type":"boolean"},"minVectorScore":{"type":"number","minimum":0,"maximum":1},"maxTokens":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":1000000}},"required":["query"]}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/context",
		Summary:  "Get first-pass memory context for a user message",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"message":{"type":"string","minLength":1,"maxLength":8192},"k":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":50},"namespace":{"type":"string","maxLength":128},"project":{"nullable":true,"type":"string","minLength":1,"maxLength":128},"includeProjects":{"maxItems":16,"type":"array","items":{"type":"string","minLength":1,"maxLength":128}},"includeNamespaces":{"maxItems":16,"type":"array","items":{"type":"string","minLength":1,"maxLength":128,"pattern":"^[a-z0-9][a-z0-9._:-]*$"}},"weights":{"type":"object","properties":{"keyword":{"type":"number"},"vector":{"type":"number"},"graph":{"type":"number"},"recency":{"type":"number"},"entity":{"type":"number"}}},"maxSensitivity":{"type":"string","enum":["public","internal","private","sensitive"]},"asOf":{"nullable":true,"type":"string","format":"date-time","pattern":"^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"},"decompose":{"type":"boolean"},"expandSourceChunks":{"type":"boolean"},"maxTokens":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":1000000}},"required":["message"]}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/capture",
		Summary:  "Capture a durable memory fact with provenance defaults",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"content":{"type":"string","minLength":1,"maxLength":262144},"namespace":{"type":"string","maxLength":128},"source":{"type":"string","maxLength":128},"agentName":{"nullable":true,"type":"string","maxLength":128},"project":{"nullable":true,"type":"string","minLength":1,"maxLength":128},"metadata":{"type":"object","additionalProperties":{}},"sensitivity":{"type":"string","enum":["public","internal","private","sensitive"]},"sourceType":{"type":"string","maxLength":64},"capturedFrom":{"type":"string","maxLength":256},"confidence":{"type":"number","minimum":0,"maximum":1},"force":{"type":"boolean"},"expiresAt":{"type":"string","format":"date-time","pattern":"^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$"}},"required":["content"]}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/session-recap",
		Summary:  "Ingest a concise session recap as typed durable memories",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"decisions":{"type":"array","items":{"type":"string","minLength":12,"maxLength":4000}},"setupFacts":{"type":"array","items":{"type":"string","minLength":12,"maxLength":4000}},"rootCauses":{"type":"array","items":{"type":"string","minLength":12,"maxLength":4000}},"preferences":{"type":"array","items":{"type":"string","minLength":12,"maxLength":4000}},"projectConventions":{"type":"array","items":{"type":"string","minLength":12,"maxLength":4000}},"safetyConstraints":{"type":"array","items":{"type":"string","minLength":12,"maxLength":4000}},"other":{"type":"array","items":{"type":"string","minLength":12,"maxLength":4000}},"namespace":{"type":"string","minLength":1,"maxLength":128},"source":{"type":"string","minLength":1,"maxLength":256},"sourceType":{"type":"string","minLength":1,"maxLength":64},"capturedFrom":{"type":"string","minLength":1,"maxLength":256},"agentName":{"nullable":true,"type":"string","maxLength":128},"confidence":{"type":"number","minimum":0,"maximum":1},"force":{"type":"boolean"},"project":{"nullable":true,"type":"string","minLength":1,"maxLength":128},"metadata":{"type":"object","additionalProperties":{}},"sensitivity":{"type":"string","enum":["public","internal","private","sensitive"]}},"additionalProperties":false}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/remember",
		Summary:  "Store a new memory entry",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"content":{"type":"string","minLength":1,"maxLength":262144},"namespace":{"type":"string","maxLength":128},"source":{"type":"string","maxLength":128},"agentName":{"nullable":true,"type":"string","maxLength":128},"project":{"nullable":true,"type":"string","minLength":1,"maxLength":128},"metadata":{"type":"object","additionalProperties":{}},"sensitivity":{"type":"string","enum":["public","internal","private","sensitive"]},"sourceType":{"type":"string","maxLength":64},"capturedFrom":{"type":"string","maxLength":256},"confidence":{"type":"number","minimum":0,"maximum":1},"force":{"type":"boolean"},"expiresAt":{"type":"string","format":"date-time","pattern":"^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$"}},"required":["content"]}`,
	},
	{
		Method:   "GET",
		Path:     "/v1/context-prefix",
		Summary:  "Cacheable observation log prefix for prompt-caching agents",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Params:   `[{"schema":{"nullable":true,"type":"string","maxLength":128},"in":"query","name":"project","required":false}]`,
	},
	{
		Method:   "POST",
		Path:     "/v1/observe",
		Summary:  "Trigger an observer+reflector pass over recent memories (operator)",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"project":{"nullable":true,"type":"string","maxLength":128},"limit":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":200}}}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/decay",
		Summary:  "Trigger a decay sweep (operator)",
		Tags:     []string{"lifecycle"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"effectiveDays":{"type":"number","minimum":0,"exclusiveMinimum":true}}}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/dream-cycle",
		Summary:  "Trigger the dedup-merge + edge-promotion pass (operator)",
		Tags:     []string{"lifecycle"},
		Security: []string{"UserBearer", "SessionCookie"},
	},
	{
		Method:   "PUT",
		Path:     "/v1/memories/{id}",
		Summary:  "Update a memory entry's content / metadata / namespace",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"content":{"type":"string","minLength":1,"maxLength":262144},"namespace":{"type":"string","maxLength":128},"metadata":{"type":"object","additionalProperties":{}},"sensitivity":{"type":"string","enum":["public","internal","private","sensitive"]},"sourceType":{"type":"string","maxLength":64},"capturedFrom":{"type":"string","maxLength":256},"confidence":{"type":"number","minimum":0,"maximum":1},"project":{"nullable":true,"type":"string","minLength":1,"maxLength":128}}}`,
		Params:   `[{"schema":{"type":"string","minLength":1,"maxLength":128},"in":"path","name":"id","required":true}]`,
	},
	{
		Method:   "POST",
		Path:     "/v1/reap-orphans",
		Summary:  "Trigger the cold-orphan reaper (operator)",
		Tags:     []string{"lifecycle"},
		Security: []string{"UserBearer", "SessionCookie"},
	},
	{
		Method:   "POST",
		Path:     "/v1/recent",
		Summary:  "List recent memories for the caller's scope",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"namespace":{"type":"string","maxLength":128},"k":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":200},"since":{"type":"string","format":"date-time","pattern":"^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$"},"project":{"nullable":true,"type":"string","minLength":1,"maxLength":128},"includeProjects":{"maxItems":16,"type":"array","items":{"type":"string","minLength":1,"maxLength":128}},"includeNamespaces":{"maxItems":16,"type":"array","items":{"type":"string","minLength":1,"maxLength":128,"pattern":"^[a-z0-9][a-z0-9._:-]*$"}},"maxSensitivity":{"type":"string","enum":["public","internal","private","sensitive"]},"contentMode":{"type":"string","enum":["full","snippet","ids"]}}}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/neighbors",
		Summary:  "Graph-walk neighbours of a seed memory",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"id":{"type":"string","minLength":1,"maxLength":128},"depth":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":3},"k":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":50},"project":{"nullable":true,"type":"string","minLength":1,"maxLength":128},"includeProjects":{"maxItems":16,"type":"array","items":{"type":"string","minLength":1,"maxLength":128}},"includeNamespaces":{"maxItems":16,"type":"array","items":{"type":"string","minLength":1,"maxLength":128,"pattern":"^[a-z0-9][a-z0-9._:-]*$"}},"maxSensitivity":{"type":"string","enum":["public","internal","private","sensitive"]}},"required":["id"]}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/forget",
		Summary:  "Delete a memory entry by id",
		Tags:     []string{"memory"},
		Security: []string{"UserBearer", "SessionCookie"},
		Body:     `{"type":"object","properties":{"id":{"type":"string","minLength":1,"maxLength":128},"project":{"nullable":true,"type":"string","minLength":1,"maxLength":128}},"required":["id"]}`,
	},
	{
		Method:   "GET",
		Path:     "/v1/stats",
		Summary:  "Per-user counts across warm/cold/graph",
		Tags:     []string{"lifecycle"},
		Security: []string{"UserBearer", "SessionCookie"},
	},
	{
		Method:   "GET",
		Path:     "/v1/me/metrics",
		Summary:  "Per-caller throughput + lifetime counters (admins get the global view)",
		Tags:     []string{"metrics"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:   "GET",
		Path:     "/v1/me/metrics/history",
		Summary:  "Rolling 1-48h sample history of queries + remembers",
		Tags:     []string{"metrics"},
		Security: []string{"SessionCookie", "UserBearer"},
		Params:   `[{"schema":{"type":"integer","minimum":1,"maximum":48},"in":"query","name":"hours","required":false}]`,
	},
	{
		Method:   "GET",
		Path:     "/v1/me/tokens",
		Summary:  "List the caller's API tokens",
		Tags:     []string{"tokens"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:   "POST",
		Path:     "/v1/me/tokens",
		Summary:  "Mint a new `nm_…` API token for the caller",
		Tags:     []string{"tokens"},
		Security: []string{"SessionCookie", "UserBearer"},
		Body:     `{"type":"object","properties":{"label":{"type":"string","maxLength":128},"scope":{"type":"string","enum":["full","read_only"]},"project":{"type":"string","minLength":1,"maxLength":128},"expiresInDays":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":3650}}}`,
	},
	{
		Method:   "DELETE",
		Path:     "/v1/me/tokens/{hash}",
		Summary:  "Hard-delete a token by its sha256 hash",
		Tags:     []string{"tokens"},
		Security: []string{"SessionCookie", "UserBearer"},
		Params:   `[{"schema":{"type":"string","pattern":"^[a-f0-9]{64}$"},"in":"path","name":"hash","required":true}]`,
	},
	{
		Method:   "GET",
		Path:     "/v1/me/projects",
		Summary:  "List projects the caller owns or is a member of",
		Tags:     []string{"projects"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:   "POST",
		Path:     "/v1/me/projects",
		Summary:  "Create a project (sub-brain)",
		Tags:     []string{"projects"},
		Security: []string{"SessionCookie", "UserBearer"},
		Body:     `{"type":"object","properties":{"name":{"type":"string","minLength":1,"maxLength":128}},"required":["name"]}`,
	},
	{
		Method:   "DELETE",
		Path:     "/v1/me/projects/{id}",
		Summary:  "Delete a project (owner only)",
		Tags:     []string{"projects"},
		Security: []string{"SessionCookie", "UserBearer"},
		Params:   `[{"schema":{"type":"string","minLength":1,"maxLength":128},"in":"path","name":"id","required":true}]`,
	},
	{
		Method:   "GET",
		Path:     "/v1/me/projects/{id}/members",
		Summary:  "List members of a project (member-only)",
		Tags:     []string{"projects"},
		Security: []string{"SessionCookie", "UserBearer"},
		Params:   `[{"schema":{"type":"string","minLength":1,"maxLength":128},"in":"path","name":"id","required":true}]`,
	},
	{
		Method:   "POST",
		Path:     "/v1/me/projects/{id}/members",
		Summary:  "Invite a user (by exact email) to a project (owner only)",
		Tags:     []string{"projects"},
		Security: []string{"SessionCookie", "UserBearer"},
		Body:     `{"type":"object","properties":{"username":{"type":"string","minLength":1,"maxLength":64},"role":{"type":"string","enum":["owner","member"]}},"required":["username"]}`,
		Params:   `[{"schema":{"type":"string","minLength":1,"maxLength":128},"in":"path","name":"id","required":true}]`,
	},
	{
		Method:   "DELETE",
		Path:     "/v1/me/projects/{id}/members/{userId}",
		Summary:  "Remove a member from a project (owner can remove anyone; members can leave)",
		Tags:     []string{"projects"},
		Security: []string{"SessionCookie", "UserBearer"},
		Params:   `[{"schema":{"type":"string","minLength":1,"maxLength":128},"in":"path","name":"id","required":true},{"schema":{"type":"string","minLength":1,"maxLength":128},"in":"path","name":"userId","required":true}]`,
	},
	{
		Method:   "GET",
		Path:     "/v1/me/active-project",
		Summary:  "Get the caller's active project (or null)",
		Tags:     []string{"self-service"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:   "PUT",
		Path:     "/v1/me/active-project",
		Summary:  "Set the caller's active project",
		Tags:     []string{"self-service"},
		Security: []string{"SessionCookie", "UserBearer"},
		Body:     `{"type":"object","properties":{"project":{"type":"string","minLength":1,"maxLength":128}},"required":["project"]}`,
	},
	{
		Method:   "DELETE",
		Path:     "/v1/me/active-project",
		Summary:  "Clear the caller's active project",
		Tags:     []string{"self-service"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:   "GET",
		Path:     "/v1/me/export",
		Summary:  "Keyset-paged export of every entry the caller owns",
		Tags:     []string{"self-service"},
		Security: []string{"SessionCookie", "UserBearer"},
		Params:   `[{"schema":{"type":"string","maxLength":64},"in":"query","name":"afterId","required":false},{"schema":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":1000},"in":"query","name":"limit","required":false}]`,
	},
	{
		Method:   "POST",
		Path:     "/v1/me/import",
		Summary:  "Import entries (from an export or a migration) as new memories",
		Tags:     []string{"self-service"},
		Security: []string{"SessionCookie", "UserBearer"},
		Body:     `{"type":"object","properties":{"entries":{"minItems":1,"maxItems":200,"type":"array","items":{"type":"object","properties":{"content":{"type":"string","minLength":1,"maxLength":262144},"namespace":{"type":"string","maxLength":128},"source":{"type":"string","maxLength":128},"agentName":{"nullable":true,"type":"string","maxLength":128},"project":{"nullable":true,"type":"string","minLength":1,"maxLength":128},"metadata":{"type":"object","additionalProperties":{}},"sourceType":{"type":"string","maxLength":64},"capturedFrom":{"type":"string","maxLength":256},"confidence":{"type":"number","minimum":0,"maximum":1}},"required":["content"]}}},"required":["entries"]}`,
	},
	{
		Method:   "GET",
		Path:     "/v1/me/usage",
		Summary:  "The caller's stored-entry count and effective quotas",
		Tags:     []string{"self-service"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:   "GET",
		Path:     "/v1/me/changes",
		Summary:  "Per-user memory changelog (created/updated/superseded/deleted/expired)",
		Tags:     []string{"self-service"},
		Security: []string{"SessionCookie", "UserBearer"},
		Params:   `[{"schema":{"type":"string","format":"date-time","pattern":"^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$"},"in":"query","name":"since","required":false},{"schema":{"type":"integer","minimum":0,"maximum":9007199254740991},"in":"query","name":"afterSeq","required":false},{"schema":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":500},"in":"query","name":"limit","required":false}]`,
	},
	{
		Method:   "GET",
		Path:     "/v1/me/today",
		Summary:  "Lightweight cross-table activity feed for the user dashboard",
		Tags:     []string{"self-service"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:   "GET",
		Path:     "/v1/me/onboarding",
		Summary:  "Derived onboarding state for the welcome wizard",
		Tags:     []string{"self-service"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:   "POST",
		Path:     "/v1/admin/tokens/revoke",
		Summary:  "Revoke a user bearer by plaintext token",
		Tags:     []string{"admin"},
		Security: []string{"SessionCookie", "UserBearer"},
		Body:     `{"type":"object","properties":{"token":{"type":"string","minLength":1,"maxLength":256}},"required":["token"]}`,
	},
	{
		Method:   "POST",
		Path:     "/v1/admin/users",
		Summary:  "Provision a user (and optionally a bearer token) non-interactively",
		Tags:     []string{"admin"},
		Security: []string{"SessionCookie", "UserBearer"},
		Body:     `{"type":"object","properties":{"email":{"type":"string","maxLength":254,"format":"email","pattern":"^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$"},"password":{"type":"string","minLength":8,"maxLength":256},"name":{"type":"string","minLength":1,"maxLength":128},"tokenLabel":{"type":"string","maxLength":128},"tokenScope":{"type":"string","enum":["full","read_only"]},"tokenExpiresInDays":{"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":3650}},"required":["email","password"]}`,
	},
	{
		Method:   "GET",
		Path:     "/v1/admin/users",
		Summary:  "List every user with entry + token counts",
		Tags:     []string{"admin"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:   "DELETE",
		Path:     "/v1/admin/users/{id}",
		Summary:  "Delete a user and everything they own (irreversible)",
		Tags:     []string{"admin"},
		Security: []string{"SessionCookie", "UserBearer"},
		Params:   `[{"schema":{"type":"boolean"},"in":"query","name":"dryRun","required":false},{"schema":{"type":"string","minLength":1,"maxLength":128},"in":"path","name":"id","required":true}]`,
	},
	{
		Method:   "PUT",
		Path:     "/v1/admin/users/{id}/quota",
		Summary:  "Set per-user quota overrides (null clears back to server default)",
		Tags:     []string{"admin"},
		Security: []string{"SessionCookie", "UserBearer"},
		Body:     `{"type":"object","properties":{"maxEntries":{"nullable":true,"type":"integer","minimum":0,"maximum":9007199254740991},"writesPerMinute":{"nullable":true,"type":"integer","minimum":0,"maximum":9007199254740991}}}`,
		Params:   `[{"schema":{"type":"string","minLength":1,"maxLength":128},"in":"path","name":"id","required":true}]`,
	},
	{
		Method:   "GET",
		Path:     "/v1/admin/audit-log",
		Summary:  "Tail the audit log",
		Tags:     []string{"admin"},
		Security: []string{"SessionCookie", "UserBearer"},
		Params:   `[{"schema":{"default":200,"type":"integer","minimum":0,"exclusiveMinimum":true,"maximum":500},"in":"query","name":"limit","required":false}]`,
	},
	{
		Method:   "GET",
		Path:     "/v1/admin/metrics",
		Summary:  "Global metrics snapshot (JSON)",
		Tags:     []string{"admin"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:   "GET",
		Path:     "/v1/admin/metrics/prom",
		Summary:  "Same metrics in Prometheus exposition format",
		Tags:     []string{"admin"},
		Security: []string{"SessionCookie", "UserBearer"},
	},
	{
		Method:      "GET",
		Path:        "/mcp/sse",
		Summary:     "Legacy MCP SSE transport (2024-11-05) — open the event stream",
		Tags:        []string{"mcp"},
		Description: "Opens the long-lived SSE event stream for the legacy two-endpoint MCP transport. Clients then POST JSON-RPC requests to `/mcp/messages?sessionId=<id>`. New integrations should prefer `/mcp` (Streamable HTTP).",
	},
	{
		Method:      "POST",
		Path:        "/mcp/messages",
		Summary:     "Legacy MCP SSE transport — submit a JSON-RPC request",
		Tags:        []string{"mcp"},
		Description: "Submit a JSON-RPC request on a session opened via `/mcp/sse`. The JSON-RPC response is delivered on the SSE channel, not in this response body.",
	},
	{
		Method:      "POST",
		Path:        "/mcp",
		Summary:     "MCP Streamable HTTP transport (2025-03-26+)",
		Tags:        []string{"mcp"},
		Description: "Single-endpoint MCP transport. POST a JSON-RPC request; the response is either a JSON document or a `text/event-stream` upgrade. The session id is returned in the `Mcp-Session-Id` response header on `initialize` and must be echoed on subsequent calls. GET opens a server→client SSE channel; DELETE closes the session. Origin and MCP-Protocol-Version are validated on every request.",
	},
	{
		Method:      "GET",
		Path:        "/mcp",
		Summary:     "MCP Streamable HTTP transport (2025-03-26+)",
		Tags:        []string{"mcp"},
		Description: "Single-endpoint MCP transport. POST a JSON-RPC request; the response is either a JSON document or a `text/event-stream` upgrade. The session id is returned in the `Mcp-Session-Id` response header on `initialize` and must be echoed on subsequent calls. GET opens a server→client SSE channel; DELETE closes the session. Origin and MCP-Protocol-Version are validated on every request.",
	},
	{
		Method:      "DELETE",
		Path:        "/mcp",
		Summary:     "MCP Streamable HTTP transport (2025-03-26+)",
		Tags:        []string{"mcp"},
		Description: "Single-endpoint MCP transport. POST a JSON-RPC request; the response is either a JSON document or a `text/event-stream` upgrade. The session id is returned in the `Mcp-Session-Id` response header on `initialize` and must be echoed on subsequent calls. GET opens a server→client SSE channel; DELETE closes the session. Origin and MCP-Protocol-Version are validated on every request.",
	},
	{
		Method:    "GET",
		Path:      "/live",
		Summary:   "Liveness probe — process only, no dependency checks",
		Tags:      []string{"liveness"},
		Responses: `{"200":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"],"additionalProperties":false}}}}}`,
	},
	{
		Method:    "GET",
		Path:      "/ready",
		Summary:   "Readiness probe — dependency checks, boolean only",
		Tags:      []string{"readiness"},
		Responses: `{"200":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"],"additionalProperties":false}}}},"503":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"],"additionalProperties":false}}}}}`,
	},
	{
		Method:    "GET",
		Path:      "/health",
		Summary:   "Readiness probe — dependency checks, boolean only",
		Tags:      []string{"readiness"},
		Responses: `{"200":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"],"additionalProperties":false}}}},"503":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"}},"required":["ok"],"additionalProperties":false}}}}}`,
	},
	{
		Method:    "GET",
		Path:      "/v1/admin/health/deep",
		Summary:   "Admin-only dependency snapshot (warm/cold/graph status)",
		Tags:      []string{"admin"},
		Security:  []string{"SessionCookie"},
		Responses: `{"200":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"},"deps":{"type":"object","properties":{"warm":{"type":"string","enum":["ok","unreachable"]},"cold":{"type":"string","enum":["ok","unreachable"]},"graph":{"type":"string","enum":["ok","unreachable","disabled"]},"embedder":{"type":"string","enum":["ok","failing"]}},"required":["warm","cold","graph","embedder"],"additionalProperties":false},"pendingEmbeddings":{"nullable":true,"type":"number"}},"required":["ok","deps","pendingEmbeddings"],"additionalProperties":false}}}},"401":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"error":{"type":"string"}},"required":["error"],"additionalProperties":false}}}},"503":{"description":"Default Response","content":{"application/json":{"schema":{"type":"object","properties":{"ok":{"type":"boolean"},"deps":{"type":"object","properties":{"warm":{"type":"string","enum":["ok","unreachable"]},"cold":{"type":"string","enum":["ok","unreachable"]},"graph":{"type":"string","enum":["ok","unreachable","disabled"]},"embedder":{"type":"string","enum":["ok","failing"]}},"required":["warm","cold","graph","embedder"],"additionalProperties":false},"pendingEmbeddings":{"nullable":true,"type":"number"}},"required":["ok","deps","pendingEmbeddings"],"additionalProperties":false}}}}}`,
	},
}
