// Code generated by cmd/gen-contract from api/openapi.yaml. DO NOT EDIT.

package httpapi

// GeneratedRoute is one operation the contract declares. openapi_test.go
// checks this list against what the mux actually serves, in both
// directions: a route served but not in the spec is undocumented, and a
// route in the spec but not served is a promise nothing keeps.
type GeneratedRoute struct {
	Method      string
	Path        string
	OperationID string
	// Tool is the MCP tool this operation backs, or "" when it is
	// HTTP-only.
	Tool string
}

var generatedRoutes = []GeneratedRoute{
	{Method: "GET", Path: "/.well-known/oauth-protected-resource", OperationID: "getWellKnownOauthProtectedResource", Tool: ""},
	{Method: "GET", Path: "/health", OperationID: "getHealth", Tool: ""},
	{Method: "GET", Path: "/live", OperationID: "getLive", Tool: ""},
	{Method: "DELETE", Path: "/mcp", OperationID: "deleteMcp", Tool: ""},
	{Method: "GET", Path: "/mcp", OperationID: "getMcp", Tool: ""},
	{Method: "POST", Path: "/mcp", OperationID: "postMcp", Tool: ""},
	{Method: "GET", Path: "/ready", OperationID: "getReady", Tool: ""},
	{Method: "GET", Path: "/v1/admin/audit-log", OperationID: "getV1AdminAuditLog", Tool: ""},
	{Method: "GET", Path: "/v1/admin/health/deep", OperationID: "getV1AdminHealthDeep", Tool: ""},
	{Method: "GET", Path: "/v1/admin/metrics", OperationID: "getV1AdminMetrics", Tool: ""},
	{Method: "GET", Path: "/v1/admin/metrics/prom", OperationID: "getV1AdminMetricsProm", Tool: ""},
	{Method: "POST", Path: "/v1/admin/tokens/revoke", OperationID: "postV1AdminTokensRevoke", Tool: ""},
	{Method: "GET", Path: "/v1/admin/users", OperationID: "getV1AdminUsers", Tool: ""},
	{Method: "POST", Path: "/v1/admin/users", OperationID: "postV1AdminUsers", Tool: ""},
	{Method: "DELETE", Path: "/v1/admin/users/{id}", OperationID: "deleteV1AdminUsersById", Tool: ""},
	{Method: "PUT", Path: "/v1/admin/users/{id}/quota", OperationID: "putV1AdminUsersByIdQuota", Tool: ""},
	{Method: "POST", Path: "/v1/adoption", OperationID: "postV1Adoption", Tool: "memory_adoption"},
	{Method: "POST", Path: "/v1/auth/rotate-token", OperationID: "postV1AuthRotateToken", Tool: ""},
	{Method: "POST", Path: "/v1/capture", OperationID: "postV1Capture", Tool: "memory_capture"},
	{Method: "POST", Path: "/v1/context", OperationID: "postV1Context", Tool: "memory_context"},
	{Method: "GET", Path: "/v1/context-prefix", OperationID: "getV1ContextPrefix", Tool: ""},
	{Method: "POST", Path: "/v1/decay", OperationID: "postV1Decay", Tool: ""},
	{Method: "POST", Path: "/v1/dream-cycle", OperationID: "postV1DreamCycle", Tool: ""},
	{Method: "POST", Path: "/v1/evaluate", OperationID: "postV1Evaluate", Tool: "memory_evaluate"},
	{Method: "POST", Path: "/v1/forget", OperationID: "postV1Forget", Tool: "memory_forget"},
	{Method: "POST", Path: "/v1/hygiene", OperationID: "postV1Hygiene", Tool: "memory_hygiene"},
	{Method: "DELETE", Path: "/v1/me/active-project", OperationID: "deleteV1MeActiveProject", Tool: "project_deactivate"},
	{Method: "GET", Path: "/v1/me/active-project", OperationID: "getV1MeActiveProject", Tool: ""},
	{Method: "PUT", Path: "/v1/me/active-project", OperationID: "putV1MeActiveProject", Tool: "project_activate"},
	{Method: "GET", Path: "/v1/me/changes", OperationID: "getV1MeChanges", Tool: ""},
	{Method: "GET", Path: "/v1/me/export", OperationID: "getV1MeExport", Tool: ""},
	{Method: "POST", Path: "/v1/me/import", OperationID: "postV1MeImport", Tool: ""},
	{Method: "GET", Path: "/v1/me/metrics", OperationID: "getV1MeMetrics", Tool: ""},
	{Method: "GET", Path: "/v1/me/metrics/history", OperationID: "getV1MeMetricsHistory", Tool: ""},
	{Method: "GET", Path: "/v1/me/onboarding", OperationID: "getV1MeOnboarding", Tool: ""},
	{Method: "GET", Path: "/v1/me/projects", OperationID: "getV1MeProjects", Tool: "project_list"},
	{Method: "POST", Path: "/v1/me/projects", OperationID: "postV1MeProjects", Tool: "project_create"},
	{Method: "DELETE", Path: "/v1/me/projects/{id}", OperationID: "deleteV1MeProjectsById", Tool: "project_delete"},
	{Method: "GET", Path: "/v1/me/projects/{id}/members", OperationID: "getV1MeProjectsByIdMembers", Tool: ""},
	{Method: "POST", Path: "/v1/me/projects/{id}/members", OperationID: "postV1MeProjectsByIdMembers", Tool: "project_share"},
	{Method: "DELETE", Path: "/v1/me/projects/{id}/members/{userId}", OperationID: "deleteV1MeProjectsByIdMembersByUserId", Tool: "project_unshare"},
	{Method: "GET", Path: "/v1/me/today", OperationID: "getV1MeToday", Tool: "memory_today"},
	{Method: "GET", Path: "/v1/me/tokens", OperationID: "getV1MeTokens", Tool: ""},
	{Method: "POST", Path: "/v1/me/tokens", OperationID: "postV1MeTokens", Tool: ""},
	{Method: "DELETE", Path: "/v1/me/tokens/{hash}", OperationID: "deleteV1MeTokensByHash", Tool: ""},
	{Method: "GET", Path: "/v1/me/usage", OperationID: "getV1MeUsage", Tool: ""},
	{Method: "PUT", Path: "/v1/memories/{id}", OperationID: "putV1MemoriesById", Tool: "memory_update"},
	{Method: "POST", Path: "/v1/neighbors", OperationID: "postV1Neighbors", Tool: "memory_neighbors"},
	{Method: "POST", Path: "/v1/observe", OperationID: "postV1Observe", Tool: ""},
	{Method: "POST", Path: "/v1/reap-orphans", OperationID: "postV1ReapOrphans", Tool: ""},
	{Method: "POST", Path: "/v1/recent", OperationID: "postV1Recent", Tool: "memory_recent"},
	{Method: "POST", Path: "/v1/remember", OperationID: "postV1Remember", Tool: "memory_remember"},
	{Method: "POST", Path: "/v1/search", OperationID: "postV1Search", Tool: "memory_search"},
	{Method: "POST", Path: "/v1/session-recap", OperationID: "postV1SessionRecap", Tool: "memory_session_recap"},
	{Method: "GET", Path: "/v1/stats", OperationID: "getV1Stats", Tool: "memory_stats"},
}
