// Code generated by clients/gen. DO NOT EDIT.
//
// Scenario dispatch: calls the routes.json method a scenario names, with the
// scenario's wire-form args, and returns the result as JSON. Every method
// is called directly, so a method missing from the SDK fails compilation.

#![allow(clippy::all, dead_code, unused_variables)]
// Formatting a generated file would fight the generator; rustfmt alone
// sets the `rustfmt` cfg, so the compiler never sees this attribute.
#![cfg_attr(rustfmt, rustfmt_skip)]

use novamem::types;
use serde::de::DeserializeOwned;
use serde_json::Value;

use super::Clients;

fn arg<T: DeserializeOwned + Default>(a: &Value, k: &str) -> T {
    a.get(k).cloned().and_then(|v| serde_json::from_value(v).ok()).unwrap_or_default()
}

fn req<T: DeserializeOwned + Default>(a: &Value) -> T {
    serde_json::from_value(a.clone()).unwrap_or_default()
}

fn json<T: serde::Serialize>(v: T) -> Value {
    serde_json::to_value(v).unwrap_or(Value::Null)
}


/// The routes.json method names this table serves.
pub const METHODS: &[&str] = &[
    "Admin.DeleteUser",
    "Admin.ListUsers",
    "Admin.PreviewDeleteUser",
    "Admin.ProvisionUser",
    "Admin.RevokeUserToken",
    "Admin.SetUserQuota",
    "Client.Capture",
    "Client.Context",
    "Client.ContextPrefix",
    "Client.Forget",
    "Client.Health",
    "Client.Neighbors",
    "Client.Recent",
    "Client.Remember",
    "Client.Search",
    "Client.SessionRecap",
    "Client.Stats",
    "Client.Today",
    "Client.Update",
    "Management.ActiveProject",
    "Management.AddProjectMember",
    "Management.Adoption",
    "Management.Changes",
    "Management.ClearActiveProject",
    "Management.CreateProject",
    "Management.Decay",
    "Management.DeleteProject",
    "Management.Evaluate",
    "Management.Export",
    "Management.Hygiene",
    "Management.Import",
    "Management.ListProjectMembers",
    "Management.ListProjects",
    "Management.ListTokens",
    "Management.MintToken",
    "Management.Observe",
    "Management.RemoveProjectMember",
    "Management.RemoveProjectMemberByUsername",
    "Management.RevokeToken",
    "Management.SetActiveProject",
    "Management.Usage",
];

pub async fn dispatch(c: &Clients, method: &str, a: &Value) -> Result<Value, novamem::Error> {
    Ok(match method {
        "Admin.DeleteUser" => json(c.admin.delete_user(&arg::<String>(a, "id"), ).await?),
        "Admin.ListUsers" => json(c.admin.list_users().await?),
        "Admin.PreviewDeleteUser" => json(c.admin.preview_delete_user(&arg::<String>(a, "id"), ).await?),
        "Admin.ProvisionUser" => json(c.admin.provision_user(req::<types::ProvisionUserRequest>(a)).await?),
        "Admin.RevokeUserToken" => json(c.admin.revoke_user_token(&arg::<String>(a, "token"), ).await?),
        "Admin.SetUserQuota" => json(c.admin.set_user_quota(&arg::<String>(a, "id"), arg::<Option<i32>>(a, "maxEntries"), arg::<Option<i32>>(a, "writesPerMinute"), ).await?),
        "Client.Capture" => json(c.client.capture(req::<types::CaptureRequest>(a)).await?),
        "Client.Context" => json(c.client.context(req::<types::ContextRequest>(a)).await?),
        "Client.ContextPrefix" => json(c.client.context_prefix(arg::<Option<String>>(a, "project").as_deref(), ).await?),
        "Client.Forget" => json(c.client.forget(req::<types::ForgetRequest>(a)).await?),
        "Client.Health" => json(c.client.health().await?),
        "Client.Neighbors" => json(c.client.neighbors(req::<types::NeighborsRequest>(a)).await?),
        "Client.Recent" => json(c.client.recent(req::<types::RecentRequest>(a)).await?),
        "Client.Remember" => json(c.client.remember(req::<types::CaptureRequest>(a)).await?),
        "Client.Search" => json(c.client.search(req::<types::SearchRequest>(a)).await?),
        "Client.SessionRecap" => json(c.client.session_recap(req::<types::SessionRecapRequest>(a)).await?),
        "Client.Stats" => json(c.client.stats().await?),
        "Client.Today" => json(c.client.today(req::<types::RecentRequest>(a)).await?),
        "Client.Update" => json(c.client.update(&arg::<String>(a, "id"), req::<types::UpdateRequest>(a)).await?),
        "Management.ActiveProject" => json(c.management.active_project().await?),
        "Management.AddProjectMember" => json(c.management.add_project_member(&arg::<String>(a, "id"), &arg::<String>(a, "email"), arg::<Option<String>>(a, "role").as_deref(), ).await?),
        "Management.Adoption" => json(c.management.adoption(arg::<Option<String>>(a, "client").as_deref(), ).await?),
        "Management.Changes" => json(c.management.changes(arg::<Option<String>>(a, "since").as_deref(), arg::<Option<i64>>(a, "afterSeq"), arg::<Option<i32>>(a, "limit"), ).await?),
        "Management.ClearActiveProject" => json(c.management.clear_active_project().await?),
        "Management.CreateProject" => json(c.management.create_project(&arg::<String>(a, "name"), ).await?),
        "Management.Decay" => json(c.management.decay(arg::<Option<i32>>(a, "effectiveDays"), ).await?),
        "Management.DeleteProject" => json(c.management.delete_project(&arg::<String>(a, "id"), ).await?),
        "Management.Evaluate" => json(c.management.evaluate(arg::<Option<String>>(a, "suite").as_deref(), ).await?),
        "Management.Export" => json(c.management.export(arg::<Option<String>>(a, "afterId").as_deref(), arg::<Option<i32>>(a, "limit"), ).await?),
        "Management.Hygiene" => json(c.management.hygiene(arg::<Option<i32>>(a, "k"), ).await?),
        "Management.Import" => json(c.management.import(arg::<Vec<Value>>(a, "entries"), ).await?),
        "Management.ListProjectMembers" => json(c.management.list_project_members(&arg::<String>(a, "id"), ).await?),
        "Management.ListProjects" => json(c.management.list_projects().await?),
        "Management.ListTokens" => json(c.management.list_tokens().await?),
        "Management.MintToken" => json(c.management.mint_token(req::<types::MintTokenRequest>(a)).await?),
        "Management.Observe" => json(c.management.observe(arg::<Option<String>>(a, "project").as_deref(), arg::<Option<i32>>(a, "limit"), ).await?),
        "Management.RemoveProjectMember" => json(c.management.remove_project_member(&arg::<String>(a, "id"), &arg::<String>(a, "userId"), ).await?),
        "Management.RemoveProjectMemberByUsername" => json(c.management.remove_project_member_by_username(&arg::<String>(a, "id"), &arg::<String>(a, "username"), ).await?),
        "Management.RevokeToken" => json(c.management.revoke_token(&arg::<String>(a, "hash"), ).await?),
        "Management.SetActiveProject" => json(c.management.set_active_project(&arg::<String>(a, "project"), ).await?),
        "Management.Usage" => json(c.management.usage().await?),
        other => panic!("scenario names unknown method {other}"),
    })
}
