# frozen_string_literal: true

# Code generated by clients/gen. DO NOT EDIT.
# rubocop:disable all
#
# Scenario dispatch: calls the routes.json method a scenario names, with the
# scenario's wire-form args. Required params are positional, optional ones
# are keywords, a request object comes last.

DISPATCH = {
  "Admin.DeleteUser" => lambda { |c, a|
    c[:Admin].delete_user(a["id"], )
  },
  "Admin.ListUsers" => lambda { |c, a|
    c[:Admin].list_users()
  },
  "Admin.PreviewDeleteUser" => lambda { |c, a|
    c[:Admin].preview_delete_user(a["id"], )
  },
  "Admin.ProvisionUser" => lambda { |c, a|
    c[:Admin].provision_user(Novamem::ProvisionUserRequest.from_h(a), )
  },
  "Admin.RevokeUserToken" => lambda { |c, a|
    c[:Admin].revoke_user_token(a["token"], )
  },
  "Admin.SetUserQuota" => lambda { |c, a|
    c[:Admin].set_user_quota(a["id"], max_entries: a["maxEntries"], writes_per_minute: a["writesPerMinute"], )
  },
  "Client.Capture" => lambda { |c, a|
    c[:Client].capture(Novamem::CaptureRequest.from_h(a), )
  },
  "Client.Context" => lambda { |c, a|
    c[:Client].context(Novamem::ContextRequest.from_h(a), )
  },
  "Client.ContextPrefix" => lambda { |c, a|
    c[:Client].context_prefix(project: a["project"], )
  },
  "Client.Forget" => lambda { |c, a|
    c[:Client].forget(Novamem::ForgetRequest.from_h(a), )
  },
  "Client.Health" => lambda { |c, a|
    c[:Client].health()
  },
  "Client.Neighbors" => lambda { |c, a|
    c[:Client].neighbors(Novamem::NeighborsRequest.from_h(a), )
  },
  "Client.Recent" => lambda { |c, a|
    c[:Client].recent(Novamem::RecentRequest.from_h(a), )
  },
  "Client.Remember" => lambda { |c, a|
    c[:Client].remember(Novamem::CaptureRequest.from_h(a), )
  },
  "Client.Search" => lambda { |c, a|
    c[:Client].search(Novamem::SearchRequest.from_h(a), )
  },
  "Client.SessionRecap" => lambda { |c, a|
    c[:Client].session_recap(Novamem::SessionRecapRequest.from_h(a), )
  },
  "Client.Stats" => lambda { |c, a|
    c[:Client].stats()
  },
  "Client.Today" => lambda { |c, a|
    c[:Client].today(Novamem::RecentRequest.from_h(a), )
  },
  "Client.Update" => lambda { |c, a|
    c[:Client].update(a["id"], Novamem::UpdateRequest.from_h(a), )
  },
  "Management.ActiveProject" => lambda { |c, a|
    c[:Management].active_project()
  },
  "Management.AddProjectMember" => lambda { |c, a|
    c[:Management].add_project_member(a["id"], a["email"], role: a["role"], )
  },
  "Management.Adoption" => lambda { |c, a|
    c[:Management].adoption(client: a["client"], )
  },
  "Management.Changes" => lambda { |c, a|
    c[:Management].changes(since: a["since"], after_seq: a["afterSeq"], limit: a["limit"], )
  },
  "Management.ClearActiveProject" => lambda { |c, a|
    c[:Management].clear_active_project()
  },
  "Management.CreateProject" => lambda { |c, a|
    c[:Management].create_project(a["name"], )
  },
  "Management.Decay" => lambda { |c, a|
    c[:Management].decay(effective_days: a["effectiveDays"], )
  },
  "Management.DeleteProject" => lambda { |c, a|
    c[:Management].delete_project(a["id"], )
  },
  "Management.Evaluate" => lambda { |c, a|
    c[:Management].evaluate(suite: a["suite"], )
  },
  "Management.Export" => lambda { |c, a|
    c[:Management].export(after_id: a["afterId"], limit: a["limit"], )
  },
  "Management.Hygiene" => lambda { |c, a|
    c[:Management].hygiene(k: a["k"], )
  },
  "Management.Import" => lambda { |c, a|
    c[:Management].import(a["entries"], )
  },
  "Management.ListProjectMembers" => lambda { |c, a|
    c[:Management].list_project_members(a["id"], )
  },
  "Management.ListProjects" => lambda { |c, a|
    c[:Management].list_projects()
  },
  "Management.ListTokens" => lambda { |c, a|
    c[:Management].list_tokens()
  },
  "Management.MintToken" => lambda { |c, a|
    c[:Management].mint_token(Novamem::MintTokenRequest.from_h(a), )
  },
  "Management.Observe" => lambda { |c, a|
    c[:Management].observe(project: a["project"], limit: a["limit"], )
  },
  "Management.RemoveProjectMember" => lambda { |c, a|
    c[:Management].remove_project_member(a["id"], a["userId"], )
  },
  "Management.RemoveProjectMemberByUsername" => lambda { |c, a|
    c[:Management].remove_project_member_by_username(a["id"], a["username"], )
  },
  "Management.RevokeToken" => lambda { |c, a|
    c[:Management].revoke_token(a["hash"], )
  },
  "Management.SetActiveProject" => lambda { |c, a|
    c[:Management].set_active_project(a["project"], )
  },
  "Management.Usage" => lambda { |c, a|
    c[:Management].usage()
  },
}.freeze
