# frozen_string_literal: true

# Code generated by clients/gen. DO NOT EDIT.
# rubocop:disable all
#
# Wire types for the novamem API, generated from docs/api/openapi.json.
# Every object type is a Struct (keyword_init) with #to_h_wire (a JSON-ready
# Hash: unset and empty optional fields are left out, required ones are
# always present, timestamps are sent as UTC with a Z) and .from_h (unknown
# keys are ignored, so a newer server still decodes).

require "time"

module Novamem
  # Conversions shared by every generated type.
  module Wire
    module_function

    def to_wire(value, spec)
      kind, arg = spec
      return nil if value.nil?

      case kind
      when :p then arg == "datetime" ? timestamp(value) : value
      when :n then value.respond_to?(:to_h_wire) ? value.to_h_wire : value
      when :a then value.map { |v| to_wire(v, arg) }
      else value.to_h.transform_values { |v| to_wire(v, arg) }
      end
    end

    def from_wire(value, spec)
      kind, arg = spec
      return nil if value.nil?

      case kind
      when :n
        cls = Novamem.const_get(arg)
        cls.respond_to?(:from_h) && value.is_a?(Hash) ? cls.from_h(value) : value
      when :a then value.is_a?(Array) ? value.map { |v| from_wire(v, arg) } : value
      when :m then value.is_a?(Hash) ? value.transform_values { |v| from_wire(v, arg) } : value
      else value
      end
    end

    # A timestamp given as a Time or a string is sent as UTC with a Z; a
    # string that does not parse is sent unchanged, and the server answers it.
    def timestamp(value)
      t = value.is_a?(String) ? Time.iso8601(value) : value
      t.respond_to?(:utc) ? t.getutc.iso8601(3) : value
    rescue ArgumentError
      value
    end
  end


  ActiveProject = Struct.new(:active, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ActiveProject
    FIELDS = [
      [:active, "active", [:n, "ActiveProjectActive"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ActiveProjectActive = Struct.new(:id, :name, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ActiveProjectActive
    FIELDS = [
      [:id, "id", [:p, "string"], false],
      [:name, "name", [:p, "string"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  AdminUser = Struct.new(:created_at, :email, :entry_count, :id, :name, :role, :token_count, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class AdminUser
    FIELDS = [
      [:created_at, "createdAt", [:p, "string"], true],
      [:email, "email", [:p, "string"], true],
      [:entry_count, "entryCount", [:p, "int32"], true],
      [:id, "id", [:p, "string"], true],
      [:name, "name", [:p, "string"], true],
      [:role, "role", [:p, "string"], true],
      [:token_count, "tokenCount", [:p, "int32"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  AdminUserList = Struct.new(:users, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class AdminUserList
    FIELDS = [
      [:users, "users", [:a, [:n, "AdminUser"]], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  AdoptionReport = Struct.new(:diagnostics, :features, :mcp, :refresh, :requested_client, :required_tools, :server, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class AdoptionReport
    FIELDS = [
      [:diagnostics, "diagnostics", [:a, [:m, [:p, "any"]]], true],
      [:features, "features", [:m, [:p, "any"]], false],
      [:mcp, "mcp", [:m, [:p, "any"]], true],
      [:refresh, "refresh", [:m, [:p, "any"]], false],
      [:requested_client, "requestedClient", [:p, "string"], true],
      [:required_tools, "requiredTools", [:a, [:p, "string"]], false],
      [:server, "server", [:m, [:p, "any"]], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  CaptureRequest = Struct.new(:agent_name, :captured_from, :confidence, :content, :expires_at, :force, :metadata, :namespace, :project, :sensitivity, :source, :source_type, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class CaptureRequest
    FIELDS = [
      [:agent_name, "agentName", [:p, "string"], false],
      [:captured_from, "capturedFrom", [:p, "string"], false],
      [:confidence, "confidence", [:p, "float"], false],
      [:content, "content", [:p, "string"], true],
      [:expires_at, "expiresAt", [:p, "datetime"], false],
      [:force, "force", [:p, "bool"], false],
      [:metadata, "metadata", [:m, [:p, "any"]], false],
      [:namespace, "namespace", [:p, "string"], false],
      [:project, "project", [:p, "string"], false],
      [:sensitivity, "sensitivity", [:n, "CaptureRequestSensitivity"], false],
      [:source, "source", [:p, "string"], false],
      [:source_type, "sourceType", [:p, "string"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of CaptureRequestSensitivity. Unknown values from a newer server are kept as strings.
  module CaptureRequestSensitivity
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"
  end

  CaptureResult = Struct.new(:deduplicated, :embedded, :id, :rejected, :superseded, :updated, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class CaptureResult
    FIELDS = [
      [:deduplicated, "deduplicated", [:p, "bool"], false],
      [:embedded, "embedded", [:p, "bool"], false],
      [:id, "id", [:p, "string"], true],
      [:rejected, "rejected", [:p, "string"], false],
      [:superseded, "superseded", [:a, [:p, "string"]], false],
      [:updated, "updated", [:p, "bool"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ChangeFeed = Struct.new(:changes, :next_seq, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ChangeFeed
    FIELDS = [
      [:changes, "changes", [:a, [:n, "ChangeFeedChangesItem"]], true],
      [:next_seq, "nextSeq", [:p, "int64"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ChangeFeedChangesItem = Struct.new(:at, :change, :detail, :entry_id, :project_id, :seq, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ChangeFeedChangesItem
    FIELDS = [
      [:at, "at", [:p, "string"], false],
      [:change, "change", [:n, "ChangeFeedChangesItemChange"], false],
      [:detail, "detail", [:m, [:p, "any"]], false],
      [:entry_id, "entryId", [:p, "string"], false],
      [:project_id, "projectId", [:p, "string"], false],
      [:seq, "seq", [:p, "int64"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of ChangeFeedChangesItemChange. Unknown values from a newer server are kept as strings.
  module ChangeFeedChangesItemChange
    CREATED = "created"
    UPDATED = "updated"
    SUPERSEDED = "superseded"
    DELETED = "deleted"
    EXPIRED = "expired"
  end

  ContextPrefix = Struct.new(:prefix, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ContextPrefix
    FIELDS = [
      [:prefix, "prefix", [:p, "string"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ContextRequest = Struct.new(:as_of, :decompose, :expand_source_chunks, :include_namespaces, :include_projects, :k, :max_sensitivity, :max_tokens, :message, :namespace, :project, :weights, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ContextRequest
    FIELDS = [
      [:as_of, "asOf", [:p, "datetime"], false],
      [:decompose, "decompose", [:p, "bool"], false],
      [:expand_source_chunks, "expandSourceChunks", [:p, "bool"], false],
      [:include_namespaces, "includeNamespaces", [:a, [:p, "string"]], false],
      [:include_projects, "includeProjects", [:a, [:p, "string"]], false],
      [:k, "k", [:p, "int32"], false],
      [:max_sensitivity, "maxSensitivity", [:n, "ContextRequestMaxSensitivity"], false],
      [:max_tokens, "maxTokens", [:p, "int32"], false],
      [:message, "message", [:p, "string"], true],
      [:namespace, "namespace", [:p, "string"], false],
      [:project, "project", [:p, "string"], false],
      [:weights, "weights", [:n, "ContextRequestWeights"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of ContextRequestMaxSensitivity. Unknown values from a newer server are kept as strings.
  module ContextRequestMaxSensitivity
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"
  end

  ContextRequestWeights = Struct.new(:entity, :graph, :keyword, :recency, :vector, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ContextRequestWeights
    FIELDS = [
      [:entity, "entity", [:p, "float"], false],
      [:graph, "graph", [:p, "float"], false],
      [:keyword, "keyword", [:p, "float"], false],
      [:recency, "recency", [:p, "float"], false],
      [:vector, "vector", [:p, "float"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  DecayResult = Struct.new(:demoted, :expired, :promoted, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class DecayResult
    FIELDS = [
      [:demoted, "demoted", [:p, "float"], true],
      [:expired, "expired", [:p, "float"], true],
      [:promoted, "promoted", [:p, "float"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  EntryList = Struct.new(:results, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class EntryList
    FIELDS = [
      [:results, "results", [:a, [:n, "MemoryEntry"]], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  EvaluateReport = Struct.new(:cases, :passed, :suite, :summary, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class EvaluateReport
    FIELDS = [
      [:cases, "cases", [:a, [:n, "EvaluateReportCasesItem"]], true],
      [:passed, "passed", [:p, "bool"], true],
      [:suite, "suite", [:p, "string"], true],
      [:summary, "summary", [:n, "EvaluateReportSummary"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  EvaluateReportCasesItem = Struct.new(:name, :passed, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class EvaluateReportCasesItem
    FIELDS = [
      [:name, "name", [:p, "string"], false],
      [:passed, "passed", [:p, "bool"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  EvaluateReportSummary = Struct.new(:failed, :passed, :total, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class EvaluateReportSummary
    FIELDS = [
      [:failed, "failed", [:p, "float"], false],
      [:passed, "passed", [:p, "float"], false],
      [:total, "total", [:p, "float"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ExportPage = Struct.new(:entries, :next_after_id, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ExportPage
    FIELDS = [
      [:entries, "entries", [:a, [:n, "ExportedEntry"]], true],
      [:next_after_id, "nextAfterId", [:p, "string"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ExportedEntry = Struct.new(:agent_name, :captured_from, :confidence, :content, :created_at, :id, :metadata, :namespace, :project_id, :source, :source_type, :updated_at, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ExportedEntry
    FIELDS = [
      [:agent_name, "agentName", [:p, "string"], true],
      [:captured_from, "capturedFrom", [:p, "string"], true],
      [:confidence, "confidence", [:p, "float"], true],
      [:content, "content", [:p, "string"], true],
      [:created_at, "createdAt", [:p, "string"], true],
      [:id, "id", [:p, "string"], true],
      [:metadata, "metadata", [:m, [:p, "any"]], true],
      [:namespace, "namespace", [:p, "string"], true],
      [:project_id, "projectId", [:p, "string"], true],
      [:source, "source", [:p, "string"], true],
      [:source_type, "sourceType", [:p, "string"], true],
      [:updated_at, "updatedAt", [:p, "string"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ForgetRequest = Struct.new(:id, :project, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ForgetRequest
    FIELDS = [
      [:id, "id", [:p, "string"], true],
      [:project, "project", [:p, "string"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ForgetResult = Struct.new(:cold_delete_ok, :deleted, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ForgetResult
    FIELDS = [
      [:cold_delete_ok, "coldDeleteOk", [:p, "bool"], false],
      [:deleted, "deleted", [:p, "bool"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  Health = Struct.new(:ok, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class Health
    FIELDS = [
      [:ok, "ok", [:p, "bool"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  HygieneReport = Struct.new(:contradiction_candidates, :duplicate_clusters, :low_value, :orphan_candidates, :stale, :summary, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class HygieneReport
    FIELDS = [
      [:contradiction_candidates, "contradictionCandidates", [:a, [:p, "any"]], false],
      [:duplicate_clusters, "duplicateClusters", [:a, [:p, "any"]], false],
      [:low_value, "lowValue", [:a, [:p, "any"]], false],
      [:orphan_candidates, "orphanCandidates", [:a, [:p, "any"]], false],
      [:stale, "stale", [:a, [:p, "any"]], false],
      [:summary, "summary", [:n, "HygieneReportSummary"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  HygieneReportSummary = Struct.new(:contradiction_candidates, :duplicate_clusters, :low_value, :orphan_candidates, :scanned, :stale, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class HygieneReportSummary
    FIELDS = [
      [:contradiction_candidates, "contradictionCandidates", [:p, "float"], false],
      [:duplicate_clusters, "duplicateClusters", [:p, "float"], false],
      [:low_value, "lowValue", [:p, "float"], false],
      [:orphan_candidates, "orphanCandidates", [:p, "float"], false],
      [:scanned, "scanned", [:p, "float"], false],
      [:stale, "stale", [:p, "float"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ImportResult = Struct.new(:deduplicated, :failed, :imported, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ImportResult
    FIELDS = [
      [:deduplicated, "deduplicated", [:p, "int32"], true],
      [:failed, "failed", [:a, [:n, "ImportResultFailedItem"]], true],
      [:imported, "imported", [:p, "int32"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ImportResultFailedItem = Struct.new(:error, :index, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ImportResultFailedItem
    FIELDS = [
      [:error, "error", [:p, "string"], true],
      [:index, "index", [:p, "int32"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  MemberAdded = Struct.new(:added, :user_id, :username, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class MemberAdded
    FIELDS = [
      [:added, "added", [:p, "bool"], true],
      [:user_id, "userId", [:p, "string"], true],
      [:username, "username", [:p, "string"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  MemberList = Struct.new(:members, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class MemberList
    FIELDS = [
      [:members, "members", [:a, [:n, "MemberListMembersItem"]], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  MemberListMembersItem = Struct.new(:joined_at, :role, :user_id, :username, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class MemberListMembersItem
    FIELDS = [
      [:joined_at, "joinedAt", [:p, "string"], false],
      [:role, "role", [:p, "string"], false],
      [:user_id, "userId", [:p, "string"], false],
      [:username, "username", [:p, "string"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  MemberRemoved = Struct.new(:removed, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class MemberRemoved
    FIELDS = [
      [:removed, "removed", [:p, "bool"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  MemoryEntry = Struct.new(:content, :id, :metadata, :namespace, :project, :score, :signals, :source, :tier, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class MemoryEntry
    FIELDS = [
      [:content, "content", [:p, "string"], true],
      [:id, "id", [:p, "string"], true],
      [:metadata, "metadata", [:m, [:p, "any"]], false],
      [:namespace, "namespace", [:p, "string"], false],
      [:project, "project", [:p, "string"], false],
      [:score, "score", [:p, "float"], false],
      [:signals, "signals", [:n, "MemoryEntrySignals"], false],
      [:source, "source", [:p, "string"], false],
      [:tier, "tier", [:n, "MemoryEntryTier"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  MemoryEntrySignals = Struct.new(:entity, :graph, :keyword, :recency, :vector, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class MemoryEntrySignals
    FIELDS = [
      [:entity, "entity", [:p, "float"], false],
      [:graph, "graph", [:p, "float"], false],
      [:keyword, "keyword", [:p, "float"], false],
      [:recency, "recency", [:p, "float"], false],
      [:vector, "vector", [:p, "float"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of MemoryEntryTier. Unknown values from a newer server are kept as strings.
  module MemoryEntryTier
    WARM = "warm"
    COLD = "cold"
  end

  MintTokenRequest = Struct.new(:expires_in_days, :label, :project, :scope, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class MintTokenRequest
    FIELDS = [
      [:expires_in_days, "expiresInDays", [:p, "int32"], false],
      [:label, "label", [:p, "string"], false],
      [:project, "project", [:p, "string"], false],
      [:scope, "scope", [:n, "MintTokenRequestScope"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of MintTokenRequestScope. Unknown values from a newer server are kept as strings.
  module MintTokenRequestScope
    FULL = "full"
    READ_ONLY = "read_only"
  end

  MintedToken = Struct.new(:created_at, :expires_at, :project_id, :scope, :token, :user_id, :warning, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class MintedToken
    FIELDS = [
      [:created_at, "createdAt", [:p, "string"], false],
      [:expires_at, "expiresAt", [:p, "string"], false],
      [:project_id, "projectId", [:p, "string"], false],
      [:scope, "scope", [:p, "string"], false],
      [:token, "token", [:p, "string"], true],
      [:user_id, "userId", [:p, "string"], false],
      [:warning, "warning", [:p, "string"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  NeighborsRequest = Struct.new(:depth, :id, :include_namespaces, :include_projects, :k, :max_sensitivity, :project, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class NeighborsRequest
    FIELDS = [
      [:depth, "depth", [:p, "int32"], false],
      [:id, "id", [:p, "string"], true],
      [:include_namespaces, "includeNamespaces", [:a, [:p, "string"]], false],
      [:include_projects, "includeProjects", [:a, [:p, "string"]], false],
      [:k, "k", [:p, "int32"], false],
      [:max_sensitivity, "maxSensitivity", [:n, "NeighborsRequestMaxSensitivity"], false],
      [:project, "project", [:p, "string"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of NeighborsRequestMaxSensitivity. Unknown values from a newer server are kept as strings.
  module NeighborsRequestMaxSensitivity
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"
  end

  ObserveResult = Struct.new(:log_chars, :observed, :reflected, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ObserveResult
    FIELDS = [
      [:log_chars, "logChars", [:p, "float"], false],
      [:observed, "observed", [:p, "float"], false],
      [:reflected, "reflected", [:p, "bool"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  Project = Struct.new(:created_at, :id, :name, :owner_user_id, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class Project
    FIELDS = [
      [:created_at, "createdAt", [:p, "string"], false],
      [:id, "id", [:p, "string"], true],
      [:name, "name", [:p, "string"], true],
      [:owner_user_id, "ownerUserId", [:p, "string"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ProjectDeleted = Struct.new(:cold_collections_dropped, :deleted, :entries_removed, :graph_cleared, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ProjectDeleted
    FIELDS = [
      [:cold_collections_dropped, "coldCollectionsDropped", [:a, [:p, "string"]], false],
      [:deleted, "deleted", [:p, "bool"], true],
      [:entries_removed, "entriesRemoved", [:p, "float"], false],
      [:graph_cleared, "graphCleared", [:p, "bool"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ProjectList = Struct.new(:projects, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ProjectList
    FIELDS = [
      [:projects, "projects", [:a, [:n, "ProjectListItem"]], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ProjectListItem = Struct.new(:created_at, :id, :name, :owner_user_id, :role, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ProjectListItem
    FIELDS = [
      [:created_at, "createdAt", [:p, "string"], false],
      [:id, "id", [:p, "string"], true],
      [:name, "name", [:p, "string"], true],
      [:owner_user_id, "ownerUserId", [:p, "string"], false],
      [:role, "role", [:p, "string"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  ProvisionUserRequest = Struct.new(:email, :name, :password, :token_expires_in_days, :token_label, :token_scope, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ProvisionUserRequest
    FIELDS = [
      [:email, "email", [:p, "string"], true],
      [:name, "name", [:p, "string"], false],
      [:password, "password", [:p, "string"], true],
      [:token_expires_in_days, "tokenExpiresInDays", [:p, "int32"], false],
      [:token_label, "tokenLabel", [:p, "string"], false],
      [:token_scope, "tokenScope", [:n, "ProvisionUserRequestTokenScope"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of ProvisionUserRequestTokenScope. Unknown values from a newer server are kept as strings.
  module ProvisionUserRequestTokenScope
    FULL = "full"
    READ_ONLY = "read_only"
  end

  ProvisionedUser = Struct.new(:email, :token, :user_id, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class ProvisionedUser
    FIELDS = [
      [:email, "email", [:p, "string"], true],
      [:token, "token", [:p, "string"], false],
      [:user_id, "userId", [:p, "string"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  QuotaResult = Struct.new(:quota, :user_id, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class QuotaResult
    FIELDS = [
      [:quota, "quota", [:n, "QuotaResultQuota"], true],
      [:user_id, "userId", [:p, "string"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  QuotaResultQuota = Struct.new(:max_entries, :writes_per_minute, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class QuotaResultQuota
    FIELDS = [
      [:max_entries, "maxEntries", [:p, "int32"], true],
      [:writes_per_minute, "writesPerMinute", [:p, "int32"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  RecentRequest = Struct.new(:content_mode, :include_namespaces, :include_projects, :k, :max_sensitivity, :namespace, :project, :since, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class RecentRequest
    FIELDS = [
      [:content_mode, "contentMode", [:n, "RecentRequestContentMode"], false],
      [:include_namespaces, "includeNamespaces", [:a, [:p, "string"]], false],
      [:include_projects, "includeProjects", [:a, [:p, "string"]], false],
      [:k, "k", [:p, "int32"], false],
      [:max_sensitivity, "maxSensitivity", [:n, "RecentRequestMaxSensitivity"], false],
      [:namespace, "namespace", [:p, "string"], false],
      [:project, "project", [:p, "string"], false],
      [:since, "since", [:p, "datetime"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of RecentRequestContentMode. Unknown values from a newer server are kept as strings.
  module RecentRequestContentMode
    FULL = "full"
    SNIPPET = "snippet"
    IDS = "ids"
  end

  # Values of RecentRequestMaxSensitivity. Unknown values from a newer server are kept as strings.
  module RecentRequestMaxSensitivity
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"
  end

  RememberResult = Struct.new(:deduplicated, :embedded, :id, :rejected, :superseded, :updated, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class RememberResult
    FIELDS = [
      [:deduplicated, "deduplicated", [:p, "bool"], false],
      [:embedded, "embedded", [:p, "bool"], false],
      [:id, "id", [:p, "string"], true],
      [:rejected, "rejected", [:p, "string"], false],
      [:superseded, "superseded", [:a, [:p, "string"]], false],
      [:updated, "updated", [:p, "bool"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  RevokeResult = Struct.new(:revoked, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class RevokeResult
    FIELDS = [
      [:revoked, "revoked", [:p, "bool"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  SearchRequest = Struct.new(:agent_name, :as_of, :content_mode, :decompose, :expand_source_chunks, :include_namespaces, :include_projects, :k, :max_sensitivity, :max_tokens, :min_vector_score, :namespace, :project, :query, :rerank, :weights, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class SearchRequest
    FIELDS = [
      [:agent_name, "agentName", [:p, "string"], false],
      [:as_of, "asOf", [:p, "datetime"], false],
      [:content_mode, "contentMode", [:n, "SearchRequestContentMode"], false],
      [:decompose, "decompose", [:p, "bool"], false],
      [:expand_source_chunks, "expandSourceChunks", [:p, "bool"], false],
      [:include_namespaces, "includeNamespaces", [:a, [:p, "string"]], false],
      [:include_projects, "includeProjects", [:a, [:p, "string"]], false],
      [:k, "k", [:p, "int32"], false],
      [:max_sensitivity, "maxSensitivity", [:n, "SearchRequestMaxSensitivity"], false],
      [:max_tokens, "maxTokens", [:p, "int32"], false],
      [:min_vector_score, "minVectorScore", [:p, "float"], false],
      [:namespace, "namespace", [:p, "string"], false],
      [:project, "project", [:p, "string"], false],
      [:query, "query", [:p, "string"], true],
      [:rerank, "rerank", [:p, "bool"], false],
      [:weights, "weights", [:n, "SearchRequestWeights"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of SearchRequestContentMode. Unknown values from a newer server are kept as strings.
  module SearchRequestContentMode
    FULL = "full"
    SNIPPET = "snippet"
    IDS = "ids"
  end

  # Values of SearchRequestMaxSensitivity. Unknown values from a newer server are kept as strings.
  module SearchRequestMaxSensitivity
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"
  end

  SearchRequestWeights = Struct.new(:entity, :graph, :keyword, :recency, :vector, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class SearchRequestWeights
    FIELDS = [
      [:entity, "entity", [:p, "float"], false],
      [:graph, "graph", [:p, "float"], false],
      [:keyword, "keyword", [:p, "float"], false],
      [:recency, "recency", [:p, "float"], false],
      [:vector, "vector", [:p, "float"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  SearchResult = Struct.new(:degraded, :results, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class SearchResult
    FIELDS = [
      [:degraded, "degraded", [:p, "bool"], false],
      [:results, "results", [:a, [:n, "MemoryEntry"]], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  SessionRecapRequest = Struct.new(:agent_name, :captured_from, :confidence, :decisions, :force, :metadata, :namespace, :other, :preferences, :project, :project_conventions, :root_causes, :safety_constraints, :sensitivity, :setup_facts, :source, :source_type, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class SessionRecapRequest
    FIELDS = [
      [:agent_name, "agentName", [:p, "string"], false],
      [:captured_from, "capturedFrom", [:p, "string"], false],
      [:confidence, "confidence", [:p, "float"], false],
      [:decisions, "decisions", [:a, [:p, "string"]], false],
      [:force, "force", [:p, "bool"], false],
      [:metadata, "metadata", [:m, [:p, "any"]], false],
      [:namespace, "namespace", [:p, "string"], false],
      [:other, "other", [:a, [:p, "string"]], false],
      [:preferences, "preferences", [:a, [:p, "string"]], false],
      [:project, "project", [:p, "string"], false],
      [:project_conventions, "projectConventions", [:a, [:p, "string"]], false],
      [:root_causes, "rootCauses", [:a, [:p, "string"]], false],
      [:safety_constraints, "safetyConstraints", [:a, [:p, "string"]], false],
      [:sensitivity, "sensitivity", [:n, "SessionRecapRequestSensitivity"], false],
      [:setup_facts, "setupFacts", [:a, [:p, "string"]], false],
      [:source, "source", [:p, "string"], false],
      [:source_type, "sourceType", [:p, "string"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of SessionRecapRequestSensitivity. Unknown values from a newer server are kept as strings.
  module SessionRecapRequestSensitivity
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"
  end

  SessionRecapResult = Struct.new(:results, :saved, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class SessionRecapResult
    FIELDS = [
      [:results, "results", [:a, [:n, "CaptureResult"]], true],
      [:saved, "saved", [:p, "float"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  Stats = Struct.new(:by_namespace, :last_decay_at, :total_cold, :total_warm, :uptime_ms, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class Stats
    FIELDS = [
      [:by_namespace, "byNamespace", [:m, [:n, "StatsByNamespaceValue"]], true],
      [:last_decay_at, "lastDecayAt", [:p, "string"], false],
      [:total_cold, "totalCold", [:p, "float"], true],
      [:total_warm, "totalWarm", [:p, "float"], true],
      [:uptime_ms, "uptimeMs", [:p, "float"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  StatsByNamespaceValue = Struct.new(:cold, :warm, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class StatsByNamespaceValue
    FIELDS = [
      [:cold, "cold", [:p, "float"], false],
      [:warm, "warm", [:p, "float"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  TokenDeleted = Struct.new(:deleted, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class TokenDeleted
    FIELDS = [
      [:deleted, "deleted", [:p, "bool"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  TokenList = Struct.new(:tokens, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class TokenList
    FIELDS = [
      [:tokens, "tokens", [:a, [:m, [:p, "any"]]], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  UpdateRequest = Struct.new(:captured_from, :confidence, :content, :metadata, :namespace, :project, :sensitivity, :source_type, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class UpdateRequest
    FIELDS = [
      [:captured_from, "capturedFrom", [:p, "string"], false],
      [:confidence, "confidence", [:p, "float"], false],
      [:content, "content", [:p, "string"], false],
      [:metadata, "metadata", [:m, [:p, "any"]], false],
      [:namespace, "namespace", [:p, "string"], false],
      [:project, "project", [:p, "string"], false],
      [:sensitivity, "sensitivity", [:n, "UpdateRequestSensitivity"], false],
      [:source_type, "sourceType", [:p, "string"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  # Values of UpdateRequestSensitivity. Unknown values from a newer server are kept as strings.
  module UpdateRequestSensitivity
    PUBLIC = "public"
    INTERNAL = "internal"
    PRIVATE = "private"
    SENSITIVE = "sensitive"
  end

  UpdateResult = Struct.new(:embedding_changed, :id, :updated, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class UpdateResult
    FIELDS = [
      [:embedding_changed, "embeddingChanged", [:p, "bool"], true],
      [:id, "id", [:p, "string"], true],
      [:updated, "updated", [:p, "bool"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  Usage = Struct.new(:entries, :quota, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class Usage
    FIELDS = [
      [:entries, "entries", [:p, "float"], false],
      [:quota, "quota", [:n, "UsageQuota"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  UsageQuota = Struct.new(:max_entries, :writes_per_minute, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class UsageQuota
    FIELDS = [
      [:max_entries, "maxEntries", [:p, "float"], false],
      [:writes_per_minute, "writesPerMinute", [:p, "float"], false],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  UserDeletion = Struct.new(:cold_cleanup, :cold_cleanup_ok, :deleted, :entries_removed, :projects_deleted, :tokens_removed, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class UserDeletion
    FIELDS = [
      [:cold_cleanup, "coldCleanup", [:a, [:p, "string"]], true],
      [:cold_cleanup_ok, "coldCleanupOk", [:p, "bool"], true],
      [:deleted, "deleted", [:p, "bool"], true],
      [:entries_removed, "entriesRemoved", [:p, "int32"], true],
      [:projects_deleted, "projectsDeleted", [:a, [:p, "string"]], true],
      [:tokens_removed, "tokensRemoved", [:p, "int32"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  UserDeletionPreview = Struct.new(:dry_run, :would_delete, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class UserDeletionPreview
    FIELDS = [
      [:dry_run, "dryRun", [:p, "bool"], true],
      [:would_delete, "wouldDelete", [:n, "UserDeletionPreviewWouldDelete"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end

  UserDeletionPreviewWouldDelete = Struct.new(:email, :entries, :owned_projects, :tokens, :user_id, keyword_init: true)

  # Reopened as a class so FIELDS is its own constant (inside a
  # Struct.new block it would land on the enclosing module, shared by all).
  class UserDeletionPreviewWouldDelete
    FIELDS = [
      [:email, "email", [:p, "string"], false],
      [:entries, "entries", [:p, "int32"], true],
      [:owned_projects, "ownedProjects", [:a, [:p, "string"]], true],
      [:tokens, "tokens", [:p, "int32"], true],
      [:user_id, "userId", [:p, "string"], true],
    ].freeze

    def self.from_h(h)
      new(**FIELDS.to_h { |name, wire, spec, _| [name, Wire.from_wire(h[wire], spec)] })
    end

    def to_h_wire
      FIELDS.each_with_object({}) do |(name, wire, spec, required), out|
        v = self[name]
        next if !required && (v.nil? || v == "")

        out[wire] = Wire.to_wire(v, spec)
      end
    end
  end
end
