// Code generated by clients/gen. DO NOT EDIT.
//
// Wire types for the novamem API, generated from docs/api/openapi.json.
// Serialization (Json.Options) leaves out unset and empty optional fields,
// always writes required ones (null when null), and sends timestamps as UTC
// with a Z. Unknown fields are ignored; a missing required field fails.
// Enum-typed fields are plain strings, so an unknown value is kept.
#nullable enable
#pragma warning disable CS1591

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Novamem;

public sealed record ActiveProject
{
    [JsonPropertyName("active")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public ActiveProjectActive? Active { get; init; }
}

public sealed record ActiveProjectActive
{
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Id { get; init; }

    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Name { get; init; }
}

public sealed record AdminUser
{
    [JsonPropertyName("createdAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string CreatedAt { get; init; }

    [JsonPropertyName("email")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Email { get; init; }

    [JsonPropertyName("entryCount")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required int EntryCount { get; init; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Id { get; init; }

    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string? Name { get; init; }

    [JsonPropertyName("role")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Role { get; init; }

    [JsonPropertyName("tokenCount")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required int TokenCount { get; init; }
}

public sealed record AdminUserList
{
    [JsonPropertyName("users")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<AdminUser> Users { get; init; }
}

public sealed record AdoptionReport
{
    [JsonPropertyName("diagnostics")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<Dictionary<string, JsonElement>> Diagnostics { get; init; }

    [JsonPropertyName("features")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, JsonElement>? Features { get; init; }

    [JsonPropertyName("mcp")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Dictionary<string, JsonElement> Mcp { get; init; }

    [JsonPropertyName("refresh")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, JsonElement>? Refresh { get; init; }

    [JsonPropertyName("requestedClient")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string RequestedClient { get; init; }

    [JsonPropertyName("requiredTools")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? RequiredTools { get; init; }

    [JsonPropertyName("server")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Dictionary<string, JsonElement> Server { get; init; }
}

public sealed record CaptureRequest
{
    [JsonPropertyName("agentName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? AgentName { get; init; }

    [JsonPropertyName("capturedFrom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? CapturedFrom { get; init; }

    [JsonPropertyName("confidence")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Confidence { get; init; }

    [JsonPropertyName("content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Content { get; init; }

    [JsonPropertyName("expiresAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(TimestampConverter))]
    public string? ExpiresAt { get; init; }

    [JsonPropertyName("force")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Force { get; init; }

    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, JsonElement>? Metadata { get; init; }

    [JsonPropertyName("namespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Namespace { get; init; }

    [JsonPropertyName("project")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Project { get; init; }

    [JsonPropertyName("sensitivity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Sensitivity { get; init; }

    [JsonPropertyName("source")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Source { get; init; }

    [JsonPropertyName("sourceType")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SourceType { get; init; }
}

/// <summary>Values of CaptureRequestSensitivity. Fields of this type are plain strings.</summary>
public static class CaptureRequestSensitivity
{
    public const string Public = "public";
    public const string Internal = "internal";
    public const string Private = "private";
    public const string Sensitive = "sensitive";
}

public sealed record CaptureResult
{
    [JsonPropertyName("deduplicated")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Deduplicated { get; init; }

    [JsonPropertyName("embedded")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Embedded { get; init; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string? Id { get; init; }

    [JsonPropertyName("rejected")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Rejected { get; init; }

    [JsonPropertyName("superseded")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? Superseded { get; init; }

    [JsonPropertyName("updated")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Updated { get; init; }
}

public sealed record ChangeFeed
{
    [JsonPropertyName("changes")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<ChangeFeedChangesItem> Changes { get; init; }

    [JsonPropertyName("nextSeq")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? NextSeq { get; init; }
}

public sealed record ChangeFeedChangesItem
{
    [JsonPropertyName("at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? At { get; init; }

    [JsonPropertyName("change")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Change { get; init; }

    [JsonPropertyName("detail")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, JsonElement>? Detail { get; init; }

    [JsonPropertyName("entryId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? EntryId { get; init; }

    [JsonPropertyName("projectId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ProjectId { get; init; }

    [JsonPropertyName("seq")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Seq { get; init; }
}

/// <summary>Values of ChangeFeedChangesItemChange. Fields of this type are plain strings.</summary>
public static class ChangeFeedChangesItemChange
{
    public const string Created = "created";
    public const string Updated = "updated";
    public const string Superseded = "superseded";
    public const string Deleted = "deleted";
    public const string Expired = "expired";
}

public sealed record ContextPrefix
{
    [JsonPropertyName("prefix")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Prefix { get; init; }
}

public sealed record ContextRequest
{
    [JsonPropertyName("asOf")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(TimestampConverter))]
    public string? AsOf { get; init; }

    [JsonPropertyName("decompose")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Decompose { get; init; }

    [JsonPropertyName("expandSourceChunks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ExpandSourceChunks { get; init; }

    [JsonPropertyName("includeNamespaces")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? IncludeNamespaces { get; init; }

    [JsonPropertyName("includeProjects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? IncludeProjects { get; init; }

    [JsonPropertyName("k")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? K { get; init; }

    [JsonPropertyName("maxSensitivity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? MaxSensitivity { get; init; }

    [JsonPropertyName("maxTokens")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? MaxTokens { get; init; }

    [JsonPropertyName("message")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Message { get; init; }

    [JsonPropertyName("namespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Namespace { get; init; }

    [JsonPropertyName("project")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Project { get; init; }

    [JsonPropertyName("weights")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ContextRequestWeights? Weights { get; init; }
}

/// <summary>Values of ContextRequestMaxSensitivity. Fields of this type are plain strings.</summary>
public static class ContextRequestMaxSensitivity
{
    public const string Public = "public";
    public const string Internal = "internal";
    public const string Private = "private";
    public const string Sensitive = "sensitive";
}

public sealed record ContextRequestWeights
{
    [JsonPropertyName("entity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Entity { get; init; }

    [JsonPropertyName("graph")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Graph { get; init; }

    [JsonPropertyName("keyword")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Keyword { get; init; }

    [JsonPropertyName("recency")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Recency { get; init; }

    [JsonPropertyName("vector")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Vector { get; init; }
}

public sealed record DecayResult
{
    [JsonPropertyName("demoted")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required double Demoted { get; init; }

    [JsonPropertyName("expired")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required double Expired { get; init; }

    [JsonPropertyName("promoted")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required double Promoted { get; init; }
}

public sealed record EntryList
{
    [JsonPropertyName("results")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<MemoryEntry> Results { get; init; }
}

public sealed record EvaluateReport
{
    [JsonPropertyName("cases")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<EvaluateReportCasesItem> Cases { get; init; }

    [JsonPropertyName("passed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Passed { get; init; }

    [JsonPropertyName("suite")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Suite { get; init; }

    [JsonPropertyName("summary")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required EvaluateReportSummary Summary { get; init; }
}

public sealed record EvaluateReportCasesItem
{
    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Name { get; init; }

    [JsonPropertyName("passed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Passed { get; init; }
}

public sealed record EvaluateReportSummary
{
    [JsonPropertyName("failed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Failed { get; init; }

    [JsonPropertyName("passed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Passed { get; init; }

    [JsonPropertyName("total")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Total { get; init; }
}

public sealed record ExportPage
{
    [JsonPropertyName("entries")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<ExportedEntry> Entries { get; init; }

    [JsonPropertyName("nextAfterId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string? NextAfterId { get; init; }
}

public sealed record ExportedEntry
{
    [JsonPropertyName("agentName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string? AgentName { get; init; }

    [JsonPropertyName("capturedFrom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string? CapturedFrom { get; init; }

    [JsonPropertyName("confidence")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required double Confidence { get; init; }

    [JsonPropertyName("content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Content { get; init; }

    [JsonPropertyName("createdAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string CreatedAt { get; init; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Id { get; init; }

    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Dictionary<string, JsonElement> Metadata { get; init; }

    [JsonPropertyName("namespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Namespace { get; init; }

    [JsonPropertyName("projectId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string? ProjectId { get; init; }

    [JsonPropertyName("source")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Source { get; init; }

    [JsonPropertyName("sourceType")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string? SourceType { get; init; }

    [JsonPropertyName("updatedAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string UpdatedAt { get; init; }
}

public sealed record ForgetRequest
{
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Id { get; init; }

    [JsonPropertyName("project")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Project { get; init; }
}

public sealed record ForgetResult
{
    [JsonPropertyName("coldDeleteOk")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ColdDeleteOk { get; init; }

    [JsonPropertyName("deleted")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Deleted { get; init; }
}

public sealed record Health
{
    [JsonPropertyName("ok")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Ok { get; init; }
}

public sealed record HygieneReport
{
    [JsonPropertyName("contradictionCandidates")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<JsonElement>? ContradictionCandidates { get; init; }

    [JsonPropertyName("duplicateClusters")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<JsonElement>? DuplicateClusters { get; init; }

    [JsonPropertyName("lowValue")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<JsonElement>? LowValue { get; init; }

    [JsonPropertyName("orphanCandidates")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<JsonElement>? OrphanCandidates { get; init; }

    [JsonPropertyName("stale")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<JsonElement>? Stale { get; init; }

    [JsonPropertyName("summary")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required HygieneReportSummary Summary { get; init; }
}

public sealed record HygieneReportSummary
{
    [JsonPropertyName("contradictionCandidates")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? ContradictionCandidates { get; init; }

    [JsonPropertyName("duplicateClusters")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? DuplicateClusters { get; init; }

    [JsonPropertyName("lowValue")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? LowValue { get; init; }

    [JsonPropertyName("orphanCandidates")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? OrphanCandidates { get; init; }

    [JsonPropertyName("scanned")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Scanned { get; init; }

    [JsonPropertyName("stale")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Stale { get; init; }
}

public sealed record ImportResult
{
    [JsonPropertyName("deduplicated")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required int Deduplicated { get; init; }

    [JsonPropertyName("failed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<ImportResultFailedItem> Failed { get; init; }

    [JsonPropertyName("imported")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required int Imported { get; init; }
}

public sealed record ImportResultFailedItem
{
    [JsonPropertyName("error")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Error { get; init; }

    [JsonPropertyName("index")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required int Index { get; init; }
}

public sealed record MemberAdded
{
    [JsonPropertyName("added")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Added { get; init; }

    [JsonPropertyName("userId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string UserId { get; init; }

    [JsonPropertyName("username")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Username { get; init; }
}

public sealed record MemberList
{
    [JsonPropertyName("members")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<MemberListMembersItem> Members { get; init; }
}

public sealed record MemberListMembersItem
{
    [JsonPropertyName("joinedAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? JoinedAt { get; init; }

    [JsonPropertyName("role")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Role { get; init; }

    [JsonPropertyName("userId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? UserId { get; init; }

    [JsonPropertyName("username")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Username { get; init; }
}

public sealed record MemberRemoved
{
    [JsonPropertyName("removed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Removed { get; init; }
}

public sealed record MemoryEntry
{
    [JsonPropertyName("content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Content { get; init; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Id { get; init; }

    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, JsonElement>? Metadata { get; init; }

    [JsonPropertyName("namespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Namespace { get; init; }

    [JsonPropertyName("project")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Project { get; init; }

    [JsonPropertyName("score")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Score { get; init; }

    [JsonPropertyName("signals")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public MemoryEntrySignals? Signals { get; init; }

    [JsonPropertyName("source")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Source { get; init; }

    [JsonPropertyName("tier")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Tier { get; init; }
}

public sealed record MemoryEntrySignals
{
    [JsonPropertyName("entity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Entity { get; init; }

    [JsonPropertyName("graph")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Graph { get; init; }

    [JsonPropertyName("keyword")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Keyword { get; init; }

    [JsonPropertyName("recency")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Recency { get; init; }

    [JsonPropertyName("vector")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Vector { get; init; }
}

/// <summary>Values of MemoryEntryTier. Fields of this type are plain strings.</summary>
public static class MemoryEntryTier
{
    public const string Warm = "warm";
    public const string Cold = "cold";
}

public sealed record MintTokenRequest
{
    [JsonPropertyName("expiresInDays")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? ExpiresInDays { get; init; }

    [JsonPropertyName("label")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Label { get; init; }

    [JsonPropertyName("project")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Project { get; init; }

    [JsonPropertyName("scope")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Scope { get; init; }
}

/// <summary>Values of MintTokenRequestScope. Fields of this type are plain strings.</summary>
public static class MintTokenRequestScope
{
    public const string Full = "full";
    public const string ReadOnly = "read_only";
}

public sealed record MintedToken
{
    [JsonPropertyName("createdAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? CreatedAt { get; init; }

    [JsonPropertyName("expiresAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ExpiresAt { get; init; }

    [JsonPropertyName("projectId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ProjectId { get; init; }

    [JsonPropertyName("scope")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Scope { get; init; }

    [JsonPropertyName("token")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Token { get; init; }

    [JsonPropertyName("userId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? UserId { get; init; }

    [JsonPropertyName("warning")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Warning { get; init; }
}

public sealed record NeighborsRequest
{
    [JsonPropertyName("depth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Depth { get; init; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Id { get; init; }

    [JsonPropertyName("includeNamespaces")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? IncludeNamespaces { get; init; }

    [JsonPropertyName("includeProjects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? IncludeProjects { get; init; }

    [JsonPropertyName("k")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? K { get; init; }

    [JsonPropertyName("maxSensitivity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? MaxSensitivity { get; init; }

    [JsonPropertyName("project")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Project { get; init; }
}

/// <summary>Values of NeighborsRequestMaxSensitivity. Fields of this type are plain strings.</summary>
public static class NeighborsRequestMaxSensitivity
{
    public const string Public = "public";
    public const string Internal = "internal";
    public const string Private = "private";
    public const string Sensitive = "sensitive";
}

public sealed record ObserveResult
{
    [JsonPropertyName("logChars")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? LogChars { get; init; }

    [JsonPropertyName("observed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Observed { get; init; }

    [JsonPropertyName("reflected")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Reflected { get; init; }
}

public sealed record Project
{
    [JsonPropertyName("createdAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? CreatedAt { get; init; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Id { get; init; }

    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Name { get; init; }

    [JsonPropertyName("ownerUserId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? OwnerUserId { get; init; }
}

public sealed record ProjectDeleted
{
    [JsonPropertyName("coldCollectionsDropped")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? ColdCollectionsDropped { get; init; }

    [JsonPropertyName("deleted")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Deleted { get; init; }

    [JsonPropertyName("entriesRemoved")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? EntriesRemoved { get; init; }

    [JsonPropertyName("graphCleared")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? GraphCleared { get; init; }
}

public sealed record ProjectList
{
    [JsonPropertyName("projects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<ProjectListItem> Projects { get; init; }
}

public sealed record ProjectListItem
{
    [JsonPropertyName("createdAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? CreatedAt { get; init; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Id { get; init; }

    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Name { get; init; }

    [JsonPropertyName("ownerUserId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? OwnerUserId { get; init; }

    [JsonPropertyName("role")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Role { get; init; }
}

public sealed record ProvisionUserRequest
{
    [JsonPropertyName("email")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Email { get; init; }

    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Name { get; init; }

    [JsonPropertyName("password")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Password { get; init; }

    [JsonPropertyName("tokenExpiresInDays")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? TokenExpiresInDays { get; init; }

    [JsonPropertyName("tokenLabel")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TokenLabel { get; init; }

    [JsonPropertyName("tokenScope")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TokenScope { get; init; }
}

/// <summary>Values of ProvisionUserRequestTokenScope. Fields of this type are plain strings.</summary>
public static class ProvisionUserRequestTokenScope
{
    public const string Full = "full";
    public const string ReadOnly = "read_only";
}

public sealed record ProvisionedUser
{
    [JsonPropertyName("email")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Email { get; init; }

    [JsonPropertyName("token")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Token { get; init; }

    [JsonPropertyName("userId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string UserId { get; init; }
}

public sealed record QuotaResult
{
    [JsonPropertyName("quota")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required QuotaResultQuota Quota { get; init; }

    [JsonPropertyName("userId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string UserId { get; init; }
}

public sealed record QuotaResultQuota
{
    [JsonPropertyName("maxEntries")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public int? MaxEntries { get; init; }

    [JsonPropertyName("writesPerMinute")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public int? WritesPerMinute { get; init; }
}

public sealed record RecentRequest
{
    [JsonPropertyName("contentMode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ContentMode { get; init; }

    [JsonPropertyName("includeNamespaces")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? IncludeNamespaces { get; init; }

    [JsonPropertyName("includeProjects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? IncludeProjects { get; init; }

    [JsonPropertyName("k")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? K { get; init; }

    [JsonPropertyName("maxSensitivity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? MaxSensitivity { get; init; }

    [JsonPropertyName("namespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Namespace { get; init; }

    [JsonPropertyName("project")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Project { get; init; }

    [JsonPropertyName("since")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(TimestampConverter))]
    public string? Since { get; init; }
}

/// <summary>Values of RecentRequestContentMode. Fields of this type are plain strings.</summary>
public static class RecentRequestContentMode
{
    public const string Full = "full";
    public const string Snippet = "snippet";
    public const string Ids = "ids";
}

/// <summary>Values of RecentRequestMaxSensitivity. Fields of this type are plain strings.</summary>
public static class RecentRequestMaxSensitivity
{
    public const string Public = "public";
    public const string Internal = "internal";
    public const string Private = "private";
    public const string Sensitive = "sensitive";
}

public sealed record RememberResult
{
    [JsonPropertyName("deduplicated")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Deduplicated { get; init; }

    [JsonPropertyName("embedded")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Embedded { get; init; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public string? Id { get; init; }

    [JsonPropertyName("rejected")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Rejected { get; init; }

    [JsonPropertyName("superseded")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? Superseded { get; init; }

    [JsonPropertyName("updated")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Updated { get; init; }
}

public sealed record RevokeResult
{
    [JsonPropertyName("revoked")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Revoked { get; init; }
}

public sealed record SearchRequest
{
    [JsonPropertyName("agentName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? AgentName { get; init; }

    [JsonPropertyName("asOf")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(TimestampConverter))]
    public string? AsOf { get; init; }

    [JsonPropertyName("contentMode")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ContentMode { get; init; }

    [JsonPropertyName("decompose")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Decompose { get; init; }

    [JsonPropertyName("expandSourceChunks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ExpandSourceChunks { get; init; }

    [JsonPropertyName("includeNamespaces")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? IncludeNamespaces { get; init; }

    [JsonPropertyName("includeProjects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? IncludeProjects { get; init; }

    [JsonPropertyName("k")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? K { get; init; }

    [JsonPropertyName("maxSensitivity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? MaxSensitivity { get; init; }

    [JsonPropertyName("maxTokens")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? MaxTokens { get; init; }

    [JsonPropertyName("minVectorScore")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? MinVectorScore { get; init; }

    [JsonPropertyName("namespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Namespace { get; init; }

    [JsonPropertyName("project")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Project { get; init; }

    [JsonPropertyName("query")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Query { get; init; }

    [JsonPropertyName("rerank")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Rerank { get; init; }

    [JsonPropertyName("weights")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public SearchRequestWeights? Weights { get; init; }
}

/// <summary>Values of SearchRequestContentMode. Fields of this type are plain strings.</summary>
public static class SearchRequestContentMode
{
    public const string Full = "full";
    public const string Snippet = "snippet";
    public const string Ids = "ids";
}

/// <summary>Values of SearchRequestMaxSensitivity. Fields of this type are plain strings.</summary>
public static class SearchRequestMaxSensitivity
{
    public const string Public = "public";
    public const string Internal = "internal";
    public const string Private = "private";
    public const string Sensitive = "sensitive";
}

public sealed record SearchRequestWeights
{
    [JsonPropertyName("entity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Entity { get; init; }

    [JsonPropertyName("graph")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Graph { get; init; }

    [JsonPropertyName("keyword")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Keyword { get; init; }

    [JsonPropertyName("recency")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Recency { get; init; }

    [JsonPropertyName("vector")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Vector { get; init; }
}

public sealed record SearchResult
{
    [JsonPropertyName("degraded")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Degraded { get; init; }

    [JsonPropertyName("results")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<MemoryEntry> Results { get; init; }
}

public sealed record SessionRecapRequest
{
    [JsonPropertyName("agentName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? AgentName { get; init; }

    [JsonPropertyName("capturedFrom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? CapturedFrom { get; init; }

    [JsonPropertyName("confidence")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Confidence { get; init; }

    [JsonPropertyName("decisions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? Decisions { get; init; }

    [JsonPropertyName("force")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Force { get; init; }

    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, JsonElement>? Metadata { get; init; }

    [JsonPropertyName("namespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Namespace { get; init; }

    [JsonPropertyName("other")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? Other { get; init; }

    [JsonPropertyName("preferences")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? Preferences { get; init; }

    [JsonPropertyName("project")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Project { get; init; }

    [JsonPropertyName("projectConventions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? ProjectConventions { get; init; }

    [JsonPropertyName("rootCauses")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? RootCauses { get; init; }

    [JsonPropertyName("safetyConstraints")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? SafetyConstraints { get; init; }

    [JsonPropertyName("sensitivity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Sensitivity { get; init; }

    [JsonPropertyName("setupFacts")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? SetupFacts { get; init; }

    [JsonPropertyName("source")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Source { get; init; }

    [JsonPropertyName("sourceType")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SourceType { get; init; }
}

/// <summary>Values of SessionRecapRequestSensitivity. Fields of this type are plain strings.</summary>
public static class SessionRecapRequestSensitivity
{
    public const string Public = "public";
    public const string Internal = "internal";
    public const string Private = "private";
    public const string Sensitive = "sensitive";
}

public sealed record SessionRecapResult
{
    [JsonPropertyName("results")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<CaptureResult> Results { get; init; }

    [JsonPropertyName("saved")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required double Saved { get; init; }
}

public sealed record Stats
{
    [JsonPropertyName("byNamespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Dictionary<string, StatsByNamespaceValue> ByNamespace { get; init; }

    [JsonPropertyName("lastDecayAt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? LastDecayAt { get; init; }

    [JsonPropertyName("totalCold")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required double TotalCold { get; init; }

    [JsonPropertyName("totalWarm")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required double TotalWarm { get; init; }

    [JsonPropertyName("uptimeMs")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? UptimeMs { get; init; }
}

public sealed record StatsByNamespaceValue
{
    [JsonPropertyName("cold")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Cold { get; init; }

    [JsonPropertyName("warm")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Warm { get; init; }
}

public sealed record TokenDeleted
{
    [JsonPropertyName("deleted")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Deleted { get; init; }
}

public sealed record TokenList
{
    [JsonPropertyName("tokens")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<Dictionary<string, JsonElement>> Tokens { get; init; }
}

public sealed record UpdateRequest
{
    [JsonPropertyName("capturedFrom")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? CapturedFrom { get; init; }

    [JsonPropertyName("confidence")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Confidence { get; init; }

    [JsonPropertyName("content")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Content { get; init; }

    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, JsonElement>? Metadata { get; init; }

    [JsonPropertyName("namespace")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Namespace { get; init; }

    [JsonPropertyName("project")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Project { get; init; }

    [JsonPropertyName("sensitivity")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Sensitivity { get; init; }

    [JsonPropertyName("sourceType")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SourceType { get; init; }
}

/// <summary>Values of UpdateRequestSensitivity. Fields of this type are plain strings.</summary>
public static class UpdateRequestSensitivity
{
    public const string Public = "public";
    public const string Internal = "internal";
    public const string Private = "private";
    public const string Sensitive = "sensitive";
}

public sealed record UpdateResult
{
    [JsonPropertyName("embeddingChanged")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool EmbeddingChanged { get; init; }

    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Id { get; init; }

    [JsonPropertyName("updated")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Updated { get; init; }
}

public sealed record Usage
{
    [JsonPropertyName("entries")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? Entries { get; init; }

    [JsonPropertyName("quota")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public UsageQuota? Quota { get; init; }
}

public sealed record UsageQuota
{
    [JsonPropertyName("maxEntries")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? MaxEntries { get; init; }

    [JsonPropertyName("writesPerMinute")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? WritesPerMinute { get; init; }
}

public sealed record UserDeletion
{
    [JsonPropertyName("coldCleanup")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<string> ColdCleanup { get; init; }

    [JsonPropertyName("coldCleanupOk")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool ColdCleanupOk { get; init; }

    [JsonPropertyName("deleted")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Deleted { get; init; }

    [JsonPropertyName("entriesRemoved")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required int EntriesRemoved { get; init; }

    [JsonPropertyName("projectsDeleted")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<string> ProjectsDeleted { get; init; }

    [JsonPropertyName("tokensRemoved")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required int TokensRemoved { get; init; }
}

public sealed record UserDeletionPreview
{
    [JsonPropertyName("dryRun")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool DryRun { get; init; }

    [JsonPropertyName("wouldDelete")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required UserDeletionPreviewWouldDelete WouldDelete { get; init; }
}

public sealed record UserDeletionPreviewWouldDelete
{
    [JsonPropertyName("email")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Email { get; init; }

    [JsonPropertyName("entries")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required int Entries { get; init; }

    [JsonPropertyName("ownedProjects")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required List<string> OwnedProjects { get; init; }

    [JsonPropertyName("tokens")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required int Tokens { get; init; }

    [JsonPropertyName("userId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string UserId { get; init; }
}
