# Code generated by clients/gen. DO NOT EDIT.
"""Scenario dispatch: calls the routes.json method a scenario names, with
the scenario's wire-form args. The same table serves the sync clients and
the async ones (which return awaitables)."""

import novamem as _nm

DISPATCH = {
    "Admin.DeleteUser": lambda c, a: c["Admin"].delete_user(id=a.get("id"), ),
    "Admin.ListUsers": lambda c, a: c["Admin"].list_users(),
    "Admin.PreviewDeleteUser": lambda c, a: c["Admin"].preview_delete_user(id=a.get("id"), ),
    "Admin.ProvisionUser": lambda c, a: c["Admin"].provision_user(request=_nm.ProvisionUserRequest.from_wire(a)),
    "Admin.RevokeUserToken": lambda c, a: c["Admin"].revoke_user_token(token=a.get("token"), ),
    "Admin.SetUserQuota": lambda c, a: c["Admin"].set_user_quota(id=a.get("id"), max_entries=a.get("maxEntries"), writes_per_minute=a.get("writesPerMinute"), ),
    "Client.Capture": lambda c, a: c["Client"].capture(request=_nm.CaptureRequest.from_wire(a)),
    "Client.Context": lambda c, a: c["Client"].context(request=_nm.ContextRequest.from_wire(a)),
    "Client.ContextPrefix": lambda c, a: c["Client"].context_prefix(project=a.get("project"), ),
    "Client.Forget": lambda c, a: c["Client"].forget(request=_nm.ForgetRequest.from_wire(a)),
    "Client.Health": lambda c, a: c["Client"].health(),
    "Client.Neighbors": lambda c, a: c["Client"].neighbors(request=_nm.NeighborsRequest.from_wire(a)),
    "Client.Recent": lambda c, a: c["Client"].recent(request=_nm.RecentRequest.from_wire(a)),
    "Client.Remember": lambda c, a: c["Client"].remember(request=_nm.CaptureRequest.from_wire(a)),
    "Client.Search": lambda c, a: c["Client"].search(request=_nm.SearchRequest.from_wire(a)),
    "Client.SessionRecap": lambda c, a: c["Client"].session_recap(request=_nm.SessionRecapRequest.from_wire(a)),
    "Client.Stats": lambda c, a: c["Client"].stats(),
    "Client.Today": lambda c, a: c["Client"].today(request=_nm.RecentRequest.from_wire(a)),
    "Client.Update": lambda c, a: c["Client"].update(id=a.get("id"), request=_nm.UpdateRequest.from_wire(a)),
    "Management.ActiveProject": lambda c, a: c["Management"].active_project(),
    "Management.AddProjectMember": lambda c, a: c["Management"].add_project_member(id=a.get("id"), email=a.get("email"), role=a.get("role"), ),
    "Management.Adoption": lambda c, a: c["Management"].adoption(client=a.get("client"), ),
    "Management.Changes": lambda c, a: c["Management"].changes(since=a.get("since"), after_seq=a.get("afterSeq"), limit=a.get("limit"), ),
    "Management.ClearActiveProject": lambda c, a: c["Management"].clear_active_project(),
    "Management.CreateProject": lambda c, a: c["Management"].create_project(name=a.get("name"), ),
    "Management.Decay": lambda c, a: c["Management"].decay(effective_days=a.get("effectiveDays"), ),
    "Management.DeleteProject": lambda c, a: c["Management"].delete_project(id=a.get("id"), ),
    "Management.Evaluate": lambda c, a: c["Management"].evaluate(suite=a.get("suite"), ),
    "Management.Export": lambda c, a: c["Management"].export(after_id=a.get("afterId"), limit=a.get("limit"), ),
    "Management.Hygiene": lambda c, a: c["Management"].hygiene(k=a.get("k"), ),
    "Management.Import": lambda c, a: c["Management"].import_(entries=a.get("entries"), ),
    "Management.ListProjectMembers": lambda c, a: c["Management"].list_project_members(id=a.get("id"), ),
    "Management.ListProjects": lambda c, a: c["Management"].list_projects(),
    "Management.ListTokens": lambda c, a: c["Management"].list_tokens(),
    "Management.MintToken": lambda c, a: c["Management"].mint_token(request=_nm.MintTokenRequest.from_wire(a)),
    "Management.Observe": lambda c, a: c["Management"].observe(project=a.get("project"), limit=a.get("limit"), ),
    "Management.RemoveProjectMember": lambda c, a: c["Management"].remove_project_member(id=a.get("id"), user_id=a.get("userId"), ),
    "Management.RemoveProjectMemberByUsername": lambda c, a: c["Management"].remove_project_member_by_username(id=a.get("id"), username=a.get("username"), ),
    "Management.RevokeToken": lambda c, a: c["Management"].revoke_token(hash=a.get("hash"), ),
    "Management.SetActiveProject": lambda c, a: c["Management"].set_active_project(project=a.get("project"), ),
    "Management.Usage": lambda c, a: c["Management"].usage(),
}

ADISPATCH = DISPATCH
