// Code generated by clients/gen. DO NOT EDIT.
//
// Header-only C++17 wrapper over novamem.h: RAII handles, results owned by
// std::unique_ptr (freed with their novamem_<type>_free), and failures
// thrown as novamem::Error. Branch on Error::unavailable before saying
// anything about what is or is not stored.
// Formatting a generated file would fight the generator.
// clang-format off
#ifndef NOVAMEM_HPP
#define NOVAMEM_HPP

#include <chrono>
#include <cstdint>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>

#include "novamem.h"

namespace novamem {

/// A failed call. Never contains the bearer token.
class Error : public std::runtime_error {
  public:
    explicit Error(const novamem_error &e)
        : std::runtime_error(render(e)), op(e.op), status_code(e.status_code), code(e.code), message(e.message),
          unavailable(e.unavailable), retryable(e.retryable), not_found(e.not_found) {}

    std::string op;
    int status_code;
    std::string code;
    std::string message;
    /// The store could not be consulted. Say so; do not claim ignorance.
    bool unavailable;
    /// Calling again could plausibly succeed. The SDK never retries for you.
    bool retryable;
    /// The store answered: that id is not in your scope.
    bool not_found;

  private:
    static std::string render(const novamem_error &e) {
        std::string s = std::string("novamem ") + e.op;
        if (e.status_code) s += ": " + std::to_string(e.status_code);
        if (e.code[0]) s += std::string(" [") + e.code + "]";
        if (e.message[0]) s += std::string(": ") + e.message;
        return s;
    }
};

namespace detail {
inline void check(novamem_status st, const novamem_error &e) {
    if (st != NOVAMEM_OK) throw Error(e);
}
inline const char *opt(const std::optional<std::string> &s) { return s ? s->c_str() : nullptr; }
template <class T> const T *opt(const std::optional<T> &v) { return v ? &*v : nullptr; }
}  // namespace detail

/// A result owned by the caller, freed with its novamem_<type>_free.
template <class T> using owned = std::unique_ptr<T, void (*)(T *)>;


class Client {
  public:
    /// Throws novamem::Error on a bad configuration.
    Client(const std::string &base_url, const std::string &token,
           std::chrono::milliseconds timeout = std::chrono::milliseconds(15000))
        : h_(nullptr, novamem_client_free) {
        novamem_error e{};
        h_.reset(novamem_client_new(base_url.c_str(), token.c_str(), static_cast<uint32_t>(timeout.count()), &e));
        if (!h_) throw Error(e);
    }

    owned<novamem_capture_result> capture(const novamem_capture_request &request) const {
        novamem_error e{};
        novamem_capture_result *out = nullptr;
        detail::check(novamem_client_capture(h_.get(), &request, &out, &e), e);
        return owned<novamem_capture_result>(out, novamem_capture_result_free);
    }

    owned<novamem_search_result> context(const novamem_context_request &request) const {
        novamem_error e{};
        novamem_search_result *out = nullptr;
        detail::check(novamem_client_context(h_.get(), &request, &out, &e), e);
        return owned<novamem_search_result>(out, novamem_search_result_free);
    }

    owned<novamem_context_prefix> context_prefix(const std::optional<std::string> &project = std::nullopt) const {
        novamem_error e{};
        novamem_context_prefix *out = nullptr;
        detail::check(novamem_client_context_prefix(h_.get(), detail::opt(project), &out, &e), e);
        return owned<novamem_context_prefix>(out, novamem_context_prefix_free);
    }

    owned<novamem_forget_result> forget(const novamem_forget_request &request) const {
        novamem_error e{};
        novamem_forget_result *out = nullptr;
        detail::check(novamem_client_forget(h_.get(), &request, &out, &e), e);
        return owned<novamem_forget_result>(out, novamem_forget_result_free);
    }

    bool health() const {
        novamem_error e{};
        bool out = false;
        detail::check(novamem_client_health(h_.get(), &out, &e), e);
        return out;
    }

    owned<novamem_search_result> neighbors(const novamem_neighbors_request &request) const {
        novamem_error e{};
        novamem_search_result *out = nullptr;
        detail::check(novamem_client_neighbors(h_.get(), &request, &out, &e), e);
        return owned<novamem_search_result>(out, novamem_search_result_free);
    }

    owned<novamem_entry_list> recent(const novamem_recent_request &request) const {
        novamem_error e{};
        novamem_entry_list *out = nullptr;
        detail::check(novamem_client_recent(h_.get(), &request, &out, &e), e);
        return owned<novamem_entry_list>(out, novamem_entry_list_free);
    }

    owned<novamem_remember_result> remember(const novamem_capture_request &request) const {
        novamem_error e{};
        novamem_remember_result *out = nullptr;
        detail::check(novamem_client_remember(h_.get(), &request, &out, &e), e);
        return owned<novamem_remember_result>(out, novamem_remember_result_free);
    }

    owned<novamem_search_result> search(const novamem_search_request &request) const {
        novamem_error e{};
        novamem_search_result *out = nullptr;
        detail::check(novamem_client_search(h_.get(), &request, &out, &e), e);
        return owned<novamem_search_result>(out, novamem_search_result_free);
    }

    owned<novamem_session_recap_result> session_recap(const novamem_session_recap_request &request) const {
        novamem_error e{};
        novamem_session_recap_result *out = nullptr;
        detail::check(novamem_client_session_recap(h_.get(), &request, &out, &e), e);
        return owned<novamem_session_recap_result>(out, novamem_session_recap_result_free);
    }

    owned<novamem_stats> stats() const {
        novamem_error e{};
        novamem_stats *out = nullptr;
        detail::check(novamem_client_stats(h_.get(), &out, &e), e);
        return owned<novamem_stats>(out, novamem_stats_free);
    }

    owned<novamem_entry_list> today(const novamem_recent_request &request) const {
        novamem_error e{};
        novamem_entry_list *out = nullptr;
        detail::check(novamem_client_today(h_.get(), &request, &out, &e), e);
        return owned<novamem_entry_list>(out, novamem_entry_list_free);
    }

    owned<novamem_update_result> update(const std::string &id, const novamem_update_request &request) const {
        novamem_error e{};
        novamem_update_result *out = nullptr;
        detail::check(novamem_client_update(h_.get(), id.c_str(), &request, &out, &e), e);
        return owned<novamem_update_result>(out, novamem_update_result_free);
    }

  private:
    std::unique_ptr<novamem_client, void (*)(novamem_client *)> h_;
};

class Management {
  public:
    /// Throws novamem::Error on a bad configuration.
    Management(const std::string &base_url, const std::string &token,
           std::chrono::milliseconds timeout = std::chrono::milliseconds(15000))
        : h_(nullptr, novamem_management_free) {
        novamem_error e{};
        h_.reset(novamem_management_new(base_url.c_str(), token.c_str(), static_cast<uint32_t>(timeout.count()), &e));
        if (!h_) throw Error(e);
    }

    owned<novamem_active_project> active_project() const {
        novamem_error e{};
        novamem_active_project *out = nullptr;
        detail::check(novamem_management_active_project(h_.get(), &out, &e), e);
        return owned<novamem_active_project>(out, novamem_active_project_free);
    }

    owned<novamem_member_added> add_project_member(const std::string &id, const std::string &email, const std::optional<std::string> &role = std::nullopt) const {
        novamem_error e{};
        novamem_member_added *out = nullptr;
        detail::check(novamem_management_add_project_member(h_.get(), id.c_str(), email.c_str(), detail::opt(role), &out, &e), e);
        return owned<novamem_member_added>(out, novamem_member_added_free);
    }

    owned<novamem_adoption_report> adoption(const std::optional<std::string> &client = std::nullopt) const {
        novamem_error e{};
        novamem_adoption_report *out = nullptr;
        detail::check(novamem_management_adoption(h_.get(), detail::opt(client), &out, &e), e);
        return owned<novamem_adoption_report>(out, novamem_adoption_report_free);
    }

    owned<novamem_change_feed> changes(const std::optional<std::string> &since = std::nullopt, std::optional<int64_t> after_seq = std::nullopt, std::optional<int32_t> limit = std::nullopt) const {
        novamem_error e{};
        novamem_change_feed *out = nullptr;
        detail::check(novamem_management_changes(h_.get(), detail::opt(since), detail::opt(after_seq), detail::opt(limit), &out, &e), e);
        return owned<novamem_change_feed>(out, novamem_change_feed_free);
    }

    void clear_active_project() const {
        novamem_error e{};
        detail::check(novamem_management_clear_active_project(h_.get(), &e), e);
    }

    owned<novamem_project> create_project(const std::string &name) const {
        novamem_error e{};
        novamem_project *out = nullptr;
        detail::check(novamem_management_create_project(h_.get(), name.c_str(), &out, &e), e);
        return owned<novamem_project>(out, novamem_project_free);
    }

    owned<novamem_decay_result> decay(std::optional<int32_t> effective_days = std::nullopt) const {
        novamem_error e{};
        novamem_decay_result *out = nullptr;
        detail::check(novamem_management_decay(h_.get(), detail::opt(effective_days), &out, &e), e);
        return owned<novamem_decay_result>(out, novamem_decay_result_free);
    }

    owned<novamem_project_deleted> delete_project(const std::string &id) const {
        novamem_error e{};
        novamem_project_deleted *out = nullptr;
        detail::check(novamem_management_delete_project(h_.get(), id.c_str(), &out, &e), e);
        return owned<novamem_project_deleted>(out, novamem_project_deleted_free);
    }

    owned<novamem_evaluate_report> evaluate(const std::optional<std::string> &suite = std::nullopt) const {
        novamem_error e{};
        novamem_evaluate_report *out = nullptr;
        detail::check(novamem_management_evaluate(h_.get(), detail::opt(suite), &out, &e), e);
        return owned<novamem_evaluate_report>(out, novamem_evaluate_report_free);
    }

    owned<novamem_export_page> export_(const std::optional<std::string> &after_id = std::nullopt, std::optional<int32_t> limit = std::nullopt) const {
        novamem_error e{};
        novamem_export_page *out = nullptr;
        detail::check(novamem_management_export(h_.get(), detail::opt(after_id), detail::opt(limit), &out, &e), e);
        return owned<novamem_export_page>(out, novamem_export_page_free);
    }

    owned<novamem_hygiene_report> hygiene(std::optional<int32_t> k = std::nullopt) const {
        novamem_error e{};
        novamem_hygiene_report *out = nullptr;
        detail::check(novamem_management_hygiene(h_.get(), detail::opt(k), &out, &e), e);
        return owned<novamem_hygiene_report>(out, novamem_hygiene_report_free);
    }

    owned<novamem_import_result> import(const std::string &entries_json) const {
        novamem_error e{};
        novamem_import_result *out = nullptr;
        detail::check(novamem_management_import(h_.get(), entries_json.c_str(), &out, &e), e);
        return owned<novamem_import_result>(out, novamem_import_result_free);
    }

    owned<novamem_member_list> list_project_members(const std::string &id) const {
        novamem_error e{};
        novamem_member_list *out = nullptr;
        detail::check(novamem_management_list_project_members(h_.get(), id.c_str(), &out, &e), e);
        return owned<novamem_member_list>(out, novamem_member_list_free);
    }

    owned<novamem_project_list> list_projects() const {
        novamem_error e{};
        novamem_project_list *out = nullptr;
        detail::check(novamem_management_list_projects(h_.get(), &out, &e), e);
        return owned<novamem_project_list>(out, novamem_project_list_free);
    }

    owned<novamem_token_list> list_tokens() const {
        novamem_error e{};
        novamem_token_list *out = nullptr;
        detail::check(novamem_management_list_tokens(h_.get(), &out, &e), e);
        return owned<novamem_token_list>(out, novamem_token_list_free);
    }

    owned<novamem_minted_token> mint_token(const novamem_mint_token_request &request) const {
        novamem_error e{};
        novamem_minted_token *out = nullptr;
        detail::check(novamem_management_mint_token(h_.get(), &request, &out, &e), e);
        return owned<novamem_minted_token>(out, novamem_minted_token_free);
    }

    owned<novamem_observe_result> observe(const std::optional<std::string> &project = std::nullopt, std::optional<int32_t> limit = std::nullopt) const {
        novamem_error e{};
        novamem_observe_result *out = nullptr;
        detail::check(novamem_management_observe(h_.get(), detail::opt(project), detail::opt(limit), &out, &e), e);
        return owned<novamem_observe_result>(out, novamem_observe_result_free);
    }

    owned<novamem_member_removed> remove_project_member(const std::string &id, const std::string &user_id) const {
        novamem_error e{};
        novamem_member_removed *out = nullptr;
        detail::check(novamem_management_remove_project_member(h_.get(), id.c_str(), user_id.c_str(), &out, &e), e);
        return owned<novamem_member_removed>(out, novamem_member_removed_free);
    }

    owned<novamem_member_removed> remove_project_member_by_username(const std::string &id, const std::string &username) const {
        novamem_error e{};
        novamem_member_removed *out = nullptr;
        detail::check(novamem_management_remove_project_member_by_username(h_.get(), id.c_str(), username.c_str(), &out, &e), e);
        return owned<novamem_member_removed>(out, novamem_member_removed_free);
    }

    owned<novamem_token_deleted> revoke_token(const std::string &hash) const {
        novamem_error e{};
        novamem_token_deleted *out = nullptr;
        detail::check(novamem_management_revoke_token(h_.get(), hash.c_str(), &out, &e), e);
        return owned<novamem_token_deleted>(out, novamem_token_deleted_free);
    }

    owned<novamem_active_project> set_active_project(const std::string &project) const {
        novamem_error e{};
        novamem_active_project *out = nullptr;
        detail::check(novamem_management_set_active_project(h_.get(), project.c_str(), &out, &e), e);
        return owned<novamem_active_project>(out, novamem_active_project_free);
    }

    owned<novamem_usage> usage() const {
        novamem_error e{};
        novamem_usage *out = nullptr;
        detail::check(novamem_management_usage(h_.get(), &out, &e), e);
        return owned<novamem_usage>(out, novamem_usage_free);
    }

  private:
    std::unique_ptr<novamem_management, void (*)(novamem_management *)> h_;
};

class Admin {
  public:
    /// Throws novamem::Error on a bad configuration.
    Admin(const std::string &base_url, const std::string &token,
           std::chrono::milliseconds timeout = std::chrono::milliseconds(15000))
        : h_(nullptr, novamem_admin_free) {
        novamem_error e{};
        h_.reset(novamem_admin_new(base_url.c_str(), token.c_str(), static_cast<uint32_t>(timeout.count()), &e));
        if (!h_) throw Error(e);
    }

    owned<novamem_user_deletion> delete_user(const std::string &id) const {
        novamem_error e{};
        novamem_user_deletion *out = nullptr;
        detail::check(novamem_admin_delete_user(h_.get(), id.c_str(), &out, &e), e);
        return owned<novamem_user_deletion>(out, novamem_user_deletion_free);
    }

    owned<novamem_admin_user_list> list_users() const {
        novamem_error e{};
        novamem_admin_user_list *out = nullptr;
        detail::check(novamem_admin_list_users(h_.get(), &out, &e), e);
        return owned<novamem_admin_user_list>(out, novamem_admin_user_list_free);
    }

    owned<novamem_user_deletion_preview> preview_delete_user(const std::string &id) const {
        novamem_error e{};
        novamem_user_deletion_preview *out = nullptr;
        detail::check(novamem_admin_preview_delete_user(h_.get(), id.c_str(), &out, &e), e);
        return owned<novamem_user_deletion_preview>(out, novamem_user_deletion_preview_free);
    }

    owned<novamem_provisioned_user> provision_user(const novamem_provision_user_request &request) const {
        novamem_error e{};
        novamem_provisioned_user *out = nullptr;
        detail::check(novamem_admin_provision_user(h_.get(), &request, &out, &e), e);
        return owned<novamem_provisioned_user>(out, novamem_provisioned_user_free);
    }

    owned<novamem_revoke_result> revoke_user_token(const std::string &token) const {
        novamem_error e{};
        novamem_revoke_result *out = nullptr;
        detail::check(novamem_admin_revoke_user_token(h_.get(), token.c_str(), &out, &e), e);
        return owned<novamem_revoke_result>(out, novamem_revoke_result_free);
    }

    owned<novamem_quota_result> set_user_quota(const std::string &id, std::optional<int32_t> max_entries = std::nullopt, std::optional<int32_t> writes_per_minute = std::nullopt) const {
        novamem_error e{};
        novamem_quota_result *out = nullptr;
        detail::check(novamem_admin_set_user_quota(h_.get(), id.c_str(), detail::opt(max_entries), detail::opt(writes_per_minute), &out, &e), e);
        return owned<novamem_quota_result>(out, novamem_quota_result_free);
    }

  private:
    std::unique_ptr<novamem_admin, void (*)(novamem_admin *)> h_;
};

#ifdef NOVAMEM_TEST_DISPATCH
/// Test-only: novamem_test_call_by_name, returning the result's JSON or
/// throwing novamem::Error.
inline std::string test_call(const std::string &base_url, const std::string &token, uint32_t timeout_ms,
                             const std::string &method, const std::string &args_json) {
    novamem_error e{};
    char *out = nullptr;
    detail::check(novamem_test_call_by_name(base_url.c_str(), token.c_str(), timeout_ms, method.c_str(),
                                            args_json.c_str(), &out, &e),
                  e);
    std::string s = out ? out : "";
    novamem_string_free(out);
    return s;
}
#endif

}  // namespace novamem

#endif  // NOVAMEM_HPP
