/* Code generated by clients/gen. DO NOT EDIT.
 *
 * C API for novamem, a tiered memory service for agents: a C ABI over the
 * Rust SDK (clients/rust), generated from the same model as the Rust side
 * of the boundary (clients/c/novamem-ffi/src/ffi_types.rs), so the two
 * cannot disagree about layout.
 *
 * Memory: every struct a call returns through an out-parameter is owned by
 * the caller and freed with its novamem_<type>_free (which frees everything
 * inside it). Request structs are only read; the caller keeps them.
 * Strings are UTF-8, NUL-terminated, and declared const so a C++ caller
 * can point a request field at a literal; NULL means absent. (Strings in a
 * returned struct are still owned by it and released by its free.) An optional number
 * or boolean carries a has_<field> flag. JSON-valued fields hold JSON text.
 *
 * Errors: every call returns NOVAMEM_OK or NOVAMEM_ERR and fills the
 * caller's novamem_error, which needs no freeing. `unavailable` means the
 * store could not be consulted — never report that as "nothing stored".
 * The bearer token never appears in an error.
 */
/* Formatting a generated file would fight the generator. */
/* clang-format off */
#ifndef NOVAMEM_H
#define NOVAMEM_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { NOVAMEM_OK = 0, NOVAMEM_ERR = 1 } novamem_status;

typedef struct novamem_error {
    char op[64];
    int32_t status_code;
    char code[64];
    char message[512];
    bool unavailable;
    bool retryable;
    bool not_found;
    bool canceled;
} novamem_error;

typedef struct novamem_client novamem_client;
typedef struct novamem_management novamem_management;
typedef struct novamem_admin novamem_admin;

typedef struct novamem_active_project novamem_active_project;
typedef struct novamem_active_project_active novamem_active_project_active;
typedef struct novamem_admin_user novamem_admin_user;
typedef struct novamem_admin_user_list novamem_admin_user_list;
typedef struct novamem_adoption_report novamem_adoption_report;
typedef struct novamem_capture_request novamem_capture_request;
typedef struct novamem_capture_result novamem_capture_result;
typedef struct novamem_change_feed novamem_change_feed;
typedef struct novamem_change_feed_changes_item novamem_change_feed_changes_item;
typedef struct novamem_context_prefix novamem_context_prefix;
typedef struct novamem_context_request novamem_context_request;
typedef struct novamem_context_request_weights novamem_context_request_weights;
typedef struct novamem_decay_result novamem_decay_result;
typedef struct novamem_entry_list novamem_entry_list;
typedef struct novamem_evaluate_report novamem_evaluate_report;
typedef struct novamem_evaluate_report_cases_item novamem_evaluate_report_cases_item;
typedef struct novamem_evaluate_report_summary novamem_evaluate_report_summary;
typedef struct novamem_export_page novamem_export_page;
typedef struct novamem_exported_entry novamem_exported_entry;
typedef struct novamem_forget_request novamem_forget_request;
typedef struct novamem_forget_result novamem_forget_result;
typedef struct novamem_health novamem_health;
typedef struct novamem_hygiene_report novamem_hygiene_report;
typedef struct novamem_hygiene_report_summary novamem_hygiene_report_summary;
typedef struct novamem_import_result novamem_import_result;
typedef struct novamem_import_result_failed_item novamem_import_result_failed_item;
typedef struct novamem_member_added novamem_member_added;
typedef struct novamem_member_list novamem_member_list;
typedef struct novamem_member_list_members_item novamem_member_list_members_item;
typedef struct novamem_member_removed novamem_member_removed;
typedef struct novamem_memory_entry novamem_memory_entry;
typedef struct novamem_memory_entry_signals novamem_memory_entry_signals;
typedef struct novamem_mint_token_request novamem_mint_token_request;
typedef struct novamem_minted_token novamem_minted_token;
typedef struct novamem_neighbors_request novamem_neighbors_request;
typedef struct novamem_observe_result novamem_observe_result;
typedef struct novamem_project novamem_project;
typedef struct novamem_project_deleted novamem_project_deleted;
typedef struct novamem_project_list novamem_project_list;
typedef struct novamem_project_list_item novamem_project_list_item;
typedef struct novamem_provision_user_request novamem_provision_user_request;
typedef struct novamem_provisioned_user novamem_provisioned_user;
typedef struct novamem_quota_result novamem_quota_result;
typedef struct novamem_quota_result_quota novamem_quota_result_quota;
typedef struct novamem_recent_request novamem_recent_request;
typedef struct novamem_remember_result novamem_remember_result;
typedef struct novamem_revoke_result novamem_revoke_result;
typedef struct novamem_search_request novamem_search_request;
typedef struct novamem_search_request_weights novamem_search_request_weights;
typedef struct novamem_search_result novamem_search_result;
typedef struct novamem_session_recap_request novamem_session_recap_request;
typedef struct novamem_session_recap_result novamem_session_recap_result;
typedef struct novamem_stats novamem_stats;
typedef struct novamem_stats_by_namespace_value novamem_stats_by_namespace_value;
typedef struct novamem_token_deleted novamem_token_deleted;
typedef struct novamem_token_list novamem_token_list;
typedef struct novamem_update_request novamem_update_request;
typedef struct novamem_update_result novamem_update_result;
typedef struct novamem_usage novamem_usage;
typedef struct novamem_usage_quota novamem_usage_quota;
typedef struct novamem_user_deletion novamem_user_deletion;
typedef struct novamem_user_deletion_preview novamem_user_deletion_preview;
typedef struct novamem_user_deletion_preview_would_delete novamem_user_deletion_preview_would_delete;


struct novamem_active_project {
    struct novamem_active_project_active *active;
};
void novamem_active_project_free(novamem_active_project *p);

struct novamem_active_project_active {
    const char *id;
    const char *name;
};
void novamem_active_project_active_free(novamem_active_project_active *p);

struct novamem_admin_user {
    const char *created_at;
    const char *email;
    int32_t entry_count;
    const char *id;
    const char *name;
    const char *role;
    int32_t token_count;
};
void novamem_admin_user_free(novamem_admin_user *p);

struct novamem_admin_user_list {
    struct novamem_admin_user *users;
    size_t users_len;
};
void novamem_admin_user_list_free(novamem_admin_user_list *p);

struct novamem_adoption_report {
    const char *diagnostics;
    const char *features;
    const char *mcp;
    const char *refresh;
    const char *requested_client;
    const char **required_tools;
    size_t required_tools_len;
    const char *server;
};
void novamem_adoption_report_free(novamem_adoption_report *p);

struct novamem_capture_request {
    const char *agent_name;
    const char *captured_from;
    bool has_confidence;
    double confidence;
    const char *content;
    const char *expires_at;
    bool has_force;
    bool force;
    const char *metadata;
    const char *namespace_;
    const char *project;
    const char *sensitivity;
    const char *source;
    const char *source_type;
};
void novamem_capture_request_free(novamem_capture_request *p);

struct novamem_capture_result {
    bool has_deduplicated;
    bool deduplicated;
    bool has_embedded;
    bool embedded;
    const char *id;
    const char *rejected;
    const char **superseded;
    size_t superseded_len;
    bool has_updated;
    bool updated;
};
void novamem_capture_result_free(novamem_capture_result *p);

struct novamem_change_feed {
    struct novamem_change_feed_changes_item *changes;
    size_t changes_len;
    bool has_next_seq;
    int64_t next_seq;
};
void novamem_change_feed_free(novamem_change_feed *p);

struct novamem_change_feed_changes_item {
    const char *at;
    const char *change;
    const char *detail;
    const char *entry_id;
    const char *project_id;
    bool has_seq;
    int64_t seq;
};
void novamem_change_feed_changes_item_free(novamem_change_feed_changes_item *p);

struct novamem_context_prefix {
    const char *prefix;
};
void novamem_context_prefix_free(novamem_context_prefix *p);

struct novamem_context_request {
    const char *as_of;
    bool has_decompose;
    bool decompose;
    bool has_expand_source_chunks;
    bool expand_source_chunks;
    const char **include_namespaces;
    size_t include_namespaces_len;
    const char **include_projects;
    size_t include_projects_len;
    bool has_k;
    int32_t k;
    const char *max_sensitivity;
    bool has_max_tokens;
    int32_t max_tokens;
    const char *message;
    const char *namespace_;
    const char *project;
    struct novamem_context_request_weights *weights;
};
void novamem_context_request_free(novamem_context_request *p);

struct novamem_context_request_weights {
    bool has_entity;
    double entity;
    bool has_graph;
    double graph;
    bool has_keyword;
    double keyword;
    bool has_recency;
    double recency;
    bool has_vector;
    double vector;
};
void novamem_context_request_weights_free(novamem_context_request_weights *p);

struct novamem_decay_result {
    double demoted;
    double expired;
    double promoted;
};
void novamem_decay_result_free(novamem_decay_result *p);

struct novamem_entry_list {
    struct novamem_memory_entry *results;
    size_t results_len;
};
void novamem_entry_list_free(novamem_entry_list *p);

struct novamem_evaluate_report {
    struct novamem_evaluate_report_cases_item *cases;
    size_t cases_len;
    bool passed;
    const char *suite;
    struct novamem_evaluate_report_summary *summary;
};
void novamem_evaluate_report_free(novamem_evaluate_report *p);

struct novamem_evaluate_report_cases_item {
    const char *name;
    bool has_passed;
    bool passed;
};
void novamem_evaluate_report_cases_item_free(novamem_evaluate_report_cases_item *p);

struct novamem_evaluate_report_summary {
    bool has_failed;
    double failed;
    bool has_passed;
    double passed;
    bool has_total;
    double total;
};
void novamem_evaluate_report_summary_free(novamem_evaluate_report_summary *p);

struct novamem_export_page {
    struct novamem_exported_entry *entries;
    size_t entries_len;
    const char *next_after_id;
};
void novamem_export_page_free(novamem_export_page *p);

struct novamem_exported_entry {
    const char *agent_name;
    const char *captured_from;
    double confidence;
    const char *content;
    const char *created_at;
    const char *id;
    const char *metadata;
    const char *namespace_;
    const char *project_id;
    const char *source;
    const char *source_type;
    const char *updated_at;
};
void novamem_exported_entry_free(novamem_exported_entry *p);

struct novamem_forget_request {
    const char *id;
    const char *project;
};
void novamem_forget_request_free(novamem_forget_request *p);

struct novamem_forget_result {
    bool has_cold_delete_ok;
    bool cold_delete_ok;
    bool deleted;
};
void novamem_forget_result_free(novamem_forget_result *p);

struct novamem_health {
    bool ok;
};
void novamem_health_free(novamem_health *p);

struct novamem_hygiene_report {
    const char *contradiction_candidates;
    const char *duplicate_clusters;
    const char *low_value;
    const char *orphan_candidates;
    const char *stale;
    struct novamem_hygiene_report_summary *summary;
};
void novamem_hygiene_report_free(novamem_hygiene_report *p);

struct novamem_hygiene_report_summary {
    bool has_contradiction_candidates;
    double contradiction_candidates;
    bool has_duplicate_clusters;
    double duplicate_clusters;
    bool has_low_value;
    double low_value;
    bool has_orphan_candidates;
    double orphan_candidates;
    bool has_scanned;
    double scanned;
    bool has_stale;
    double stale;
};
void novamem_hygiene_report_summary_free(novamem_hygiene_report_summary *p);

struct novamem_import_result {
    int32_t deduplicated;
    struct novamem_import_result_failed_item *failed;
    size_t failed_len;
    int32_t imported;
};
void novamem_import_result_free(novamem_import_result *p);

struct novamem_import_result_failed_item {
    const char *error;
    int32_t index;
};
void novamem_import_result_failed_item_free(novamem_import_result_failed_item *p);

struct novamem_member_added {
    bool added;
    const char *user_id;
    const char *username;
};
void novamem_member_added_free(novamem_member_added *p);

struct novamem_member_list {
    struct novamem_member_list_members_item *members;
    size_t members_len;
};
void novamem_member_list_free(novamem_member_list *p);

struct novamem_member_list_members_item {
    const char *joined_at;
    const char *role;
    const char *user_id;
    const char *username;
};
void novamem_member_list_members_item_free(novamem_member_list_members_item *p);

struct novamem_member_removed {
    bool removed;
};
void novamem_member_removed_free(novamem_member_removed *p);

struct novamem_memory_entry {
    const char *content;
    const char *id;
    const char *metadata;
    const char *namespace_;
    const char *project;
    bool has_score;
    double score;
    struct novamem_memory_entry_signals *signals;
    const char *source;
    const char *tier;
};
void novamem_memory_entry_free(novamem_memory_entry *p);

struct novamem_memory_entry_signals {
    bool has_entity;
    double entity;
    bool has_graph;
    double graph;
    bool has_keyword;
    double keyword;
    bool has_recency;
    double recency;
    bool has_vector;
    double vector;
};
void novamem_memory_entry_signals_free(novamem_memory_entry_signals *p);

struct novamem_mint_token_request {
    bool has_expires_in_days;
    int32_t expires_in_days;
    const char *label;
    const char *project;
    const char *scope;
};
void novamem_mint_token_request_free(novamem_mint_token_request *p);

struct novamem_minted_token {
    const char *created_at;
    const char *expires_at;
    const char *project_id;
    const char *scope;
    const char *token;
    const char *user_id;
    const char *warning;
};
void novamem_minted_token_free(novamem_minted_token *p);

struct novamem_neighbors_request {
    bool has_depth;
    int32_t depth;
    const char *id;
    const char **include_namespaces;
    size_t include_namespaces_len;
    const char **include_projects;
    size_t include_projects_len;
    bool has_k;
    int32_t k;
    const char *max_sensitivity;
    const char *project;
};
void novamem_neighbors_request_free(novamem_neighbors_request *p);

struct novamem_observe_result {
    bool has_log_chars;
    double log_chars;
    bool has_observed;
    double observed;
    bool has_reflected;
    bool reflected;
};
void novamem_observe_result_free(novamem_observe_result *p);

struct novamem_project {
    const char *created_at;
    const char *id;
    const char *name;
    const char *owner_user_id;
};
void novamem_project_free(novamem_project *p);

struct novamem_project_deleted {
    const char **cold_collections_dropped;
    size_t cold_collections_dropped_len;
    bool deleted;
    bool has_entries_removed;
    double entries_removed;
    bool has_graph_cleared;
    bool graph_cleared;
};
void novamem_project_deleted_free(novamem_project_deleted *p);

struct novamem_project_list {
    struct novamem_project_list_item *projects;
    size_t projects_len;
};
void novamem_project_list_free(novamem_project_list *p);

struct novamem_project_list_item {
    const char *created_at;
    const char *id;
    const char *name;
    const char *owner_user_id;
    const char *role;
};
void novamem_project_list_item_free(novamem_project_list_item *p);

struct novamem_provision_user_request {
    const char *email;
    const char *name;
    const char *password;
    bool has_token_expires_in_days;
    int32_t token_expires_in_days;
    const char *token_label;
    const char *token_scope;
};
void novamem_provision_user_request_free(novamem_provision_user_request *p);

struct novamem_provisioned_user {
    const char *email;
    const char *token;
    const char *user_id;
};
void novamem_provisioned_user_free(novamem_provisioned_user *p);

struct novamem_quota_result {
    struct novamem_quota_result_quota *quota;
    const char *user_id;
};
void novamem_quota_result_free(novamem_quota_result *p);

struct novamem_quota_result_quota {
    bool has_max_entries;
    int32_t max_entries;
    bool has_writes_per_minute;
    int32_t writes_per_minute;
};
void novamem_quota_result_quota_free(novamem_quota_result_quota *p);

struct novamem_recent_request {
    const char *content_mode;
    const char **include_namespaces;
    size_t include_namespaces_len;
    const char **include_projects;
    size_t include_projects_len;
    bool has_k;
    int32_t k;
    const char *max_sensitivity;
    const char *namespace_;
    const char *project;
    const char *since;
};
void novamem_recent_request_free(novamem_recent_request *p);

struct novamem_remember_result {
    bool has_deduplicated;
    bool deduplicated;
    bool has_embedded;
    bool embedded;
    const char *id;
    const char *rejected;
    const char **superseded;
    size_t superseded_len;
    bool has_updated;
    bool updated;
};
void novamem_remember_result_free(novamem_remember_result *p);

struct novamem_revoke_result {
    bool revoked;
};
void novamem_revoke_result_free(novamem_revoke_result *p);

struct novamem_search_request {
    const char *agent_name;
    const char *as_of;
    const char *content_mode;
    bool has_decompose;
    bool decompose;
    bool has_expand_source_chunks;
    bool expand_source_chunks;
    const char **include_namespaces;
    size_t include_namespaces_len;
    const char **include_projects;
    size_t include_projects_len;
    bool has_k;
    int32_t k;
    const char *max_sensitivity;
    bool has_max_tokens;
    int32_t max_tokens;
    bool has_min_vector_score;
    double min_vector_score;
    const char *namespace_;
    const char *project;
    const char *query;
    bool has_rerank;
    bool rerank;
    struct novamem_search_request_weights *weights;
};
void novamem_search_request_free(novamem_search_request *p);

struct novamem_search_request_weights {
    bool has_entity;
    double entity;
    bool has_graph;
    double graph;
    bool has_keyword;
    double keyword;
    bool has_recency;
    double recency;
    bool has_vector;
    double vector;
};
void novamem_search_request_weights_free(novamem_search_request_weights *p);

struct novamem_search_result {
    bool has_degraded;
    bool degraded;
    struct novamem_memory_entry *results;
    size_t results_len;
};
void novamem_search_result_free(novamem_search_result *p);

struct novamem_session_recap_request {
    const char *agent_name;
    const char *captured_from;
    bool has_confidence;
    double confidence;
    const char **decisions;
    size_t decisions_len;
    bool has_force;
    bool force;
    const char *metadata;
    const char *namespace_;
    const char **other;
    size_t other_len;
    const char **preferences;
    size_t preferences_len;
    const char *project;
    const char **project_conventions;
    size_t project_conventions_len;
    const char **root_causes;
    size_t root_causes_len;
    const char **safety_constraints;
    size_t safety_constraints_len;
    const char *sensitivity;
    const char **setup_facts;
    size_t setup_facts_len;
    const char *source;
    const char *source_type;
};
void novamem_session_recap_request_free(novamem_session_recap_request *p);

struct novamem_session_recap_result {
    struct novamem_capture_result *results;
    size_t results_len;
    double saved;
};
void novamem_session_recap_result_free(novamem_session_recap_result *p);

struct novamem_stats {
    const char *by_namespace;
    const char *last_decay_at;
    double total_cold;
    double total_warm;
    bool has_uptime_ms;
    double uptime_ms;
};
void novamem_stats_free(novamem_stats *p);

struct novamem_stats_by_namespace_value {
    bool has_cold;
    double cold;
    bool has_warm;
    double warm;
};
void novamem_stats_by_namespace_value_free(novamem_stats_by_namespace_value *p);

struct novamem_token_deleted {
    bool deleted;
};
void novamem_token_deleted_free(novamem_token_deleted *p);

struct novamem_token_list {
    const char *tokens;
};
void novamem_token_list_free(novamem_token_list *p);

struct novamem_update_request {
    const char *captured_from;
    bool has_confidence;
    double confidence;
    const char *content;
    const char *metadata;
    const char *namespace_;
    const char *project;
    const char *sensitivity;
    const char *source_type;
};
void novamem_update_request_free(novamem_update_request *p);

struct novamem_update_result {
    bool embedding_changed;
    const char *id;
    bool updated;
};
void novamem_update_result_free(novamem_update_result *p);

struct novamem_usage {
    bool has_entries;
    double entries;
    struct novamem_usage_quota *quota;
};
void novamem_usage_free(novamem_usage *p);

struct novamem_usage_quota {
    bool has_max_entries;
    double max_entries;
    bool has_writes_per_minute;
    double writes_per_minute;
};
void novamem_usage_quota_free(novamem_usage_quota *p);

struct novamem_user_deletion {
    const char **cold_cleanup;
    size_t cold_cleanup_len;
    bool cold_cleanup_ok;
    bool deleted;
    int32_t entries_removed;
    const char **projects_deleted;
    size_t projects_deleted_len;
    int32_t tokens_removed;
};
void novamem_user_deletion_free(novamem_user_deletion *p);

struct novamem_user_deletion_preview {
    bool dry_run;
    struct novamem_user_deletion_preview_would_delete *would_delete;
};
void novamem_user_deletion_preview_free(novamem_user_deletion_preview *p);

struct novamem_user_deletion_preview_would_delete {
    const char *email;
    int32_t entries;
    const char **owned_projects;
    size_t owned_projects_len;
    int32_t tokens;
    const char *user_id;
};
void novamem_user_deletion_preview_would_delete_free(novamem_user_deletion_preview_would_delete *p);

/* Handles. base_url is the service root; token is the user's nm_ bearer;
 * timeout_ms bounds every call (0 = 15000). NULL on a bad configuration,
 * with err filled; the error never quotes the token. */
novamem_client *novamem_client_new(const char *base_url, const char *token, uint32_t timeout_ms, novamem_error *err);
void novamem_client_free(novamem_client *h);
novamem_management *novamem_management_new(const char *base_url, const char *token, uint32_t timeout_ms, novamem_error *err);
void novamem_management_free(novamem_management *h);
novamem_admin *novamem_admin_new(const char *base_url, const char *token, uint32_t timeout_ms, novamem_error *err);
void novamem_admin_free(novamem_admin *h);

/* Frees a string this library returned. NULL-safe. */
void novamem_string_free(char *s);

/* Operations. Optional numbers are passed by pointer (NULL = not given);
 * Import takes its entries as a JSON array. */
novamem_status novamem_admin_delete_user(const novamem_admin *h, const char *id, novamem_user_deletion **out, novamem_error *err);
novamem_status novamem_admin_list_users(const novamem_admin *h, novamem_admin_user_list **out, novamem_error *err);
novamem_status novamem_admin_preview_delete_user(const novamem_admin *h, const char *id, novamem_user_deletion_preview **out, novamem_error *err);
novamem_status novamem_admin_provision_user(const novamem_admin *h, const novamem_provision_user_request *request, novamem_provisioned_user **out, novamem_error *err);
novamem_status novamem_admin_revoke_user_token(const novamem_admin *h, const char *token, novamem_revoke_result **out, novamem_error *err);
novamem_status novamem_admin_set_user_quota(const novamem_admin *h, const char *id, const int32_t *max_entries, const int32_t *writes_per_minute, novamem_quota_result **out, novamem_error *err);
novamem_status novamem_client_capture(const novamem_client *h, const novamem_capture_request *request, novamem_capture_result **out, novamem_error *err);
novamem_status novamem_client_context(const novamem_client *h, const novamem_context_request *request, novamem_search_result **out, novamem_error *err);
novamem_status novamem_client_context_prefix(const novamem_client *h, const char *project, novamem_context_prefix **out, novamem_error *err);
novamem_status novamem_client_forget(const novamem_client *h, const novamem_forget_request *request, novamem_forget_result **out, novamem_error *err);
novamem_status novamem_client_health(const novamem_client *h, bool *out, novamem_error *err);
novamem_status novamem_client_neighbors(const novamem_client *h, const novamem_neighbors_request *request, novamem_search_result **out, novamem_error *err);
novamem_status novamem_client_recent(const novamem_client *h, const novamem_recent_request *request, novamem_entry_list **out, novamem_error *err);
novamem_status novamem_client_remember(const novamem_client *h, const novamem_capture_request *request, novamem_remember_result **out, novamem_error *err);
novamem_status novamem_client_search(const novamem_client *h, const novamem_search_request *request, novamem_search_result **out, novamem_error *err);
novamem_status novamem_client_session_recap(const novamem_client *h, const novamem_session_recap_request *request, novamem_session_recap_result **out, novamem_error *err);
novamem_status novamem_client_stats(const novamem_client *h, novamem_stats **out, novamem_error *err);
novamem_status novamem_client_today(const novamem_client *h, const novamem_recent_request *request, novamem_entry_list **out, novamem_error *err);
novamem_status novamem_client_update(const novamem_client *h, const char *id, const novamem_update_request *request, novamem_update_result **out, novamem_error *err);
novamem_status novamem_management_active_project(const novamem_management *h, novamem_active_project **out, novamem_error *err);
novamem_status novamem_management_add_project_member(const novamem_management *h, const char *id, const char *email, const char *role, novamem_member_added **out, novamem_error *err);
novamem_status novamem_management_adoption(const novamem_management *h, const char *client, novamem_adoption_report **out, novamem_error *err);
novamem_status novamem_management_changes(const novamem_management *h, const char *since, const int64_t *after_seq, const int32_t *limit, novamem_change_feed **out, novamem_error *err);
novamem_status novamem_management_clear_active_project(const novamem_management *h, novamem_error *err);
novamem_status novamem_management_create_project(const novamem_management *h, const char *name, novamem_project **out, novamem_error *err);
novamem_status novamem_management_decay(const novamem_management *h, const int32_t *effective_days, novamem_decay_result **out, novamem_error *err);
novamem_status novamem_management_delete_project(const novamem_management *h, const char *id, novamem_project_deleted **out, novamem_error *err);
novamem_status novamem_management_evaluate(const novamem_management *h, const char *suite, novamem_evaluate_report **out, novamem_error *err);
novamem_status novamem_management_export(const novamem_management *h, const char *after_id, const int32_t *limit, novamem_export_page **out, novamem_error *err);
novamem_status novamem_management_hygiene(const novamem_management *h, const int32_t *k, novamem_hygiene_report **out, novamem_error *err);
novamem_status novamem_management_import(const novamem_management *h, const char *entries_json, novamem_import_result **out, novamem_error *err);
novamem_status novamem_management_list_project_members(const novamem_management *h, const char *id, novamem_member_list **out, novamem_error *err);
novamem_status novamem_management_list_projects(const novamem_management *h, novamem_project_list **out, novamem_error *err);
novamem_status novamem_management_list_tokens(const novamem_management *h, novamem_token_list **out, novamem_error *err);
novamem_status novamem_management_mint_token(const novamem_management *h, const novamem_mint_token_request *request, novamem_minted_token **out, novamem_error *err);
novamem_status novamem_management_observe(const novamem_management *h, const char *project, const int32_t *limit, novamem_observe_result **out, novamem_error *err);
novamem_status novamem_management_remove_project_member(const novamem_management *h, const char *id, const char *user_id, novamem_member_removed **out, novamem_error *err);
novamem_status novamem_management_remove_project_member_by_username(const novamem_management *h, const char *id, const char *username, novamem_member_removed **out, novamem_error *err);
novamem_status novamem_management_revoke_token(const novamem_management *h, const char *hash, novamem_token_deleted **out, novamem_error *err);
novamem_status novamem_management_set_active_project(const novamem_management *h, const char *project, novamem_active_project **out, novamem_error *err);
novamem_status novamem_management_usage(const novamem_management *h, novamem_usage **out, novamem_error *err);

#ifdef NOVAMEM_TEST_DISPATCH
/* Test-only (built with the test-dispatch feature): calls a routes.json
 * method by name with wire-form JSON args, through the typed functions
 * above, and returns the result as JSON (free with novamem_string_free). */
novamem_status novamem_test_call_by_name(const char *base_url, const char *token, uint32_t timeout_ms, const char *method,
                                         const char *args_json, char **result_json, novamem_error *err);
#endif

#ifdef __cplusplus
}
#endif

#endif /* NOVAMEM_H */
