#[rustfmt::skip] // generated by clients/gen
mod dispatch;

use serde_json::Value;

pub struct Clients {
    pub client: novamem::Client,
    pub management: novamem::Management,
    pub admin: novamem::Admin,
}

// proved by: deleting an entry from tests/dispatch.rs fails this test, and
// renaming Client::session_recap fails compilation of the dispatch table.
#[test]
fn test_every_route_is_accounted() {
    let dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let routes: Value = serde_json::from_str(
        &std::fs::read_to_string(dir.join("../contract/routes.json")).unwrap(),
    )
    .unwrap();
    for (key, r) in routes.as_object().unwrap() {
        for m in r["methods"].as_array().into_iter().flatten() {
            let name = m["name"].as_str().unwrap();
            assert!(
                dispatch::METHODS.contains(&name),
                "{key}: no dispatch entry for {name}"
            );
        }
    }
}
