//! The shared behaviour suite (clients/contract/scenarios.json, ADR 0009).

#[rustfmt::skip] // generated by clients/gen
mod dispatch;

use novamem::{Admin, Client, Config, Management};
use serde_json::Value;
use std::path::PathBuf;
use std::process::Stdio;
use std::time::Duration;
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::Command;

pub struct Clients {
    pub client: Client,
    pub management: Management,
    pub admin: Admin,
}

fn contract() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../contract")
}

fn is_empty(v: &Value) -> bool {
    v.as_array().is_some_and(|a| a.is_empty())
        || v.get("results")
            .and_then(Value::as_array)
            .is_some_and(|a| a.is_empty())
}

fn subset(want: &Value, got: &Value, path: &str) -> String {
    match want {
        Value::Object(w) => {
            for (k, v) in w {
                let d = subset(
                    v,
                    got.get(k).unwrap_or(&Value::Null),
                    &format!("{path}.{k}"),
                );
                if !d.is_empty() {
                    return d;
                }
            }
            String::new()
        }
        _ if want == got => String::new(),
        _ => format!("{path}: got {got}, want {want}"),
    }
}

// proved by: removing the degraded-empty check in Client::search fails
// search-degraded-empty-is-unavailable; removing the redaction fails
// token-echoed-in-401-is-redacted.
#[tokio::test(flavor = "multi_thread")]
async fn test_scenarios() {
    let scen: Value =
        serde_json::from_str(&std::fs::read_to_string(contract().join("scenarios.json")).unwrap())
            .unwrap();
    let token = scen["token"].as_str().unwrap().to_string();
    let timeout = Duration::from_millis(scen["timeoutMs"].as_u64().unwrap());
    let mut child = Command::new("sh")
        .args(["scenario-server.sh", "-scenarios", "scenarios.json"])
        .current_dir(contract())
        .stdout(Stdio::piped())
        .kill_on_drop(true)
        .spawn()
        .unwrap();
    let mut line = String::new();
    BufReader::new(child.stdout.take().unwrap())
        .read_line(&mut line)
        .await
        .unwrap();
    let parts: Vec<&str> = line.split_whitespace().collect();
    let (url, closed) = (
        parts[1].to_string(),
        parts[2].trim_start_matches("closed=").to_string(),
    );
    let http = reqwest::Client::new();
    let mut failures = Vec::new();

    for s in scen["scenarios"].as_array().unwrap() {
        let id = s["id"].as_str().unwrap();
        let call = &s["call"];
        if s["requires"]
            .as_array()
            .is_some_and(|r| r.iter().any(|x| x == "cancel"))
        {
            println!("skip (dropping a Rust future leaves no outcome to classify): {id}");
            continue;
        }
        let (outcome, result, err): (&str, Value, Option<novamem::Error>) = if call["class"]
            == "ctor"
        {
            let a = &call["args"];
            let r = Client::new(Config {
                base_url: a["baseUrl"].as_str().unwrap().replace("<server>", &url),
                token: a["token"].as_str().unwrap().into(),
                ..Config::default()
            });
            match r {
                Ok(_) => ("ok", Value::Null, None),
                Err(e) => ("error", Value::Null, Some(e)),
            }
        } else {
            let base = if s["respond"].to_string().contains("\"refused\"") {
                format!("http://127.0.0.1:{closed}/s/{id}")
            } else {
                format!("{url}/s/{id}")
            };
            let cfg = || Config {
                base_url: base.clone(),
                token: token.clone(),
                timeout: Some(timeout),
                http: None,
            };
            let c = Clients {
                client: Client::new(cfg()).unwrap(),
                management: Management::new(cfg()).unwrap(),
                admin: Admin::new(cfg()).unwrap(),
            };
            match dispatch::dispatch(&c, call["method"].as_str().unwrap(), &call["args"]).await {
                Ok(v) if is_empty(&v) => ("empty", v, None),
                Ok(v) => ("ok", v, None),
                Err(e) if e.is_unavailable() => ("unavailable", Value::Null, Some(e)),
                Err(e) if e.is_not_found() => ("not_found", Value::Null, Some(e)),
                Err(e) => ("error", Value::Null, Some(e)),
            }
        };
        let exp = &s["expect"];
        if outcome != exp["outcome"].as_str().unwrap() {
            failures.push(format!(
                "{id}: outcome {outcome} (err {err:?}), want {}",
                exp["outcome"]
            ));
        }
        if let Some(e) = &err {
            if e.to_string().contains(&token) || format!("{e:?}").contains(&token) {
                failures.push(format!("{id}: token leaked"));
            }
            if let Some(r) = exp["retryable"].as_bool() {
                if e.is_retryable() != r {
                    failures.push(format!("{id}: retryable = {}", e.is_retryable()));
                }
            }
            if let Some(sc) = exp["statusCode"].as_u64() {
                if u64::from(e.status()) != sc {
                    failures.push(format!("{id}: status = {}", e.status()));
                }
            }
            if let Some(code) = exp["code"].as_str() {
                if e.code() != code {
                    failures.push(format!("{id}: code = {}", e.code()));
                }
            }
            if let Some(m) = exp["messageContains"].as_str() {
                if !e.to_string().to_lowercase().contains(&m.to_lowercase()) {
                    failures.push(format!("{id}: message {e} lacks {m}"));
                }
            }
        }
        if let Some(want) = exp.get("result") {
            let d = subset(want, &result, "$");
            if !d.is_empty() {
                failures.push(format!("{id}: result {d}"));
            }
        }
        if call["class"] != "ctor" {
            let text = http
                .get(format!("{url}/_verdict/{id}"))
                .send()
                .await
                .unwrap()
                .text()
                .await
                .unwrap();
            let v: Value = serde_json::from_str(&text).unwrap();
            if !v["mismatches"].as_array().unwrap().is_empty() {
                failures.push(format!("{id}: mismatches {}", v["mismatches"]));
            }
            if s["expectRequest"].as_array().is_some_and(|a| a.is_empty()) && v["requests"] != 0 {
                failures.push(format!("{id}: expected no request"));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} scenario failure(s):\n{}",
        failures.len(),
        failures.join("\n")
    );
}
