// Code generated by clients/gen. DO NOT EDIT.
//
// Scenario dispatch: calls the routes.json method a scenario names, with the
// scenario's wire-form args. A method taking scalars and a request (Update)
// gets the request without the scalar keys, as a caller would build it.

import type { Admin, Client, Management } from "../src/index.js";

export interface Clients {
  Client: Client;
  Management: Management;
  Admin: Admin;
}

type Args = Record<string, any>;

function omit(a: Args, keys: string[]): Args {
  const out: Args = {};
  for (const [k, v] of Object.entries(a)) if (!keys.includes(k)) out[k] = v;
  return out;
}

export const DISPATCH: Record<string, (c: Clients, a: Args, signal?: AbortSignal) => Promise<unknown>> = {
  "Admin.DeleteUser": (c, a, signal) =>
    c.Admin.deleteUser(a["id"], { signal }),
  "Admin.ListUsers": (c, a, signal) =>
    c.Admin.listUsers({ signal }),
  "Admin.PreviewDeleteUser": (c, a, signal) =>
    c.Admin.previewDeleteUser(a["id"], { signal }),
  "Admin.ProvisionUser": (c, a, signal) =>
    c.Admin.provisionUser(a as any, { signal }),
  "Admin.RevokeUserToken": (c, a, signal) =>
    c.Admin.revokeUserToken(a["token"], { signal }),
  "Admin.SetUserQuota": (c, a, signal) =>
    c.Admin.setUserQuota(a["id"], a["maxEntries"], a["writesPerMinute"], { signal }),
  "Client.Capture": (c, a, signal) =>
    c.Client.capture(a as any, { signal }),
  "Client.Context": (c, a, signal) =>
    c.Client.context(a as any, { signal }),
  "Client.ContextPrefix": (c, a, signal) =>
    c.Client.contextPrefix(a["project"], { signal }),
  "Client.Forget": (c, a, signal) =>
    c.Client.forget(a as any, { signal }),
  "Client.Health": (c, a, signal) =>
    c.Client.health({ signal }),
  "Client.Neighbors": (c, a, signal) =>
    c.Client.neighbors(a as any, { signal }),
  "Client.Recent": (c, a, signal) =>
    c.Client.recent(a as any, { signal }),
  "Client.Remember": (c, a, signal) =>
    c.Client.remember(a as any, { signal }),
  "Client.Search": (c, a, signal) =>
    c.Client.search(a as any, { signal }),
  "Client.SessionRecap": (c, a, signal) =>
    c.Client.sessionRecap(a as any, { signal }),
  "Client.Stats": (c, a, signal) =>
    c.Client.stats({ signal }),
  "Client.Today": (c, a, signal) =>
    c.Client.today(a as any, { signal }),
  "Client.Update": (c, a, signal) =>
    c.Client.update(a["id"], omit(a, ["id"]) as any, { signal }),
  "Management.ActiveProject": (c, a, signal) =>
    c.Management.activeProject({ signal }),
  "Management.AddProjectMember": (c, a, signal) =>
    c.Management.addProjectMember(a["id"], a["email"], a["role"], { signal }),
  "Management.Adoption": (c, a, signal) =>
    c.Management.adoption(a["client"], { signal }),
  "Management.Changes": (c, a, signal) =>
    c.Management.changes(a["since"], a["afterSeq"], a["limit"], { signal }),
  "Management.ClearActiveProject": (c, a, signal) =>
    c.Management.clearActiveProject({ signal }),
  "Management.CreateProject": (c, a, signal) =>
    c.Management.createProject(a["name"], { signal }),
  "Management.Decay": (c, a, signal) =>
    c.Management.decay(a["effectiveDays"], { signal }),
  "Management.DeleteProject": (c, a, signal) =>
    c.Management.deleteProject(a["id"], { signal }),
  "Management.Evaluate": (c, a, signal) =>
    c.Management.evaluate(a["suite"], { signal }),
  "Management.Export": (c, a, signal) =>
    c.Management.export(a["afterId"], a["limit"], { signal }),
  "Management.Hygiene": (c, a, signal) =>
    c.Management.hygiene(a["k"], { signal }),
  "Management.Import": (c, a, signal) =>
    c.Management.import(a["entries"], { signal }),
  "Management.ListProjectMembers": (c, a, signal) =>
    c.Management.listProjectMembers(a["id"], { signal }),
  "Management.ListProjects": (c, a, signal) =>
    c.Management.listProjects({ signal }),
  "Management.ListTokens": (c, a, signal) =>
    c.Management.listTokens({ signal }),
  "Management.MintToken": (c, a, signal) =>
    c.Management.mintToken(a as any, { signal }),
  "Management.Observe": (c, a, signal) =>
    c.Management.observe(a["project"], a["limit"], { signal }),
  "Management.RemoveProjectMember": (c, a, signal) =>
    c.Management.removeProjectMember(a["id"], a["userId"], { signal }),
  "Management.RemoveProjectMemberByUsername": (c, a, signal) =>
    c.Management.removeProjectMemberByUsername(a["id"], a["username"], { signal }),
  "Management.RevokeToken": (c, a, signal) =>
    c.Management.revokeToken(a["hash"], { signal }),
  "Management.SetActiveProject": (c, a, signal) =>
    c.Management.setActiveProject(a["project"], { signal }),
  "Management.Usage": (c, a, signal) =>
    c.Management.usage({ signal }),
};
